### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by Malaga82** [albertogeniola/meross-homeassistant#103]
Hello,
i had issue today, i updated to latest version and there was no way to saw plugs ( worked before updating ).
This was causing nodered addon to not connecting to HA.
So i decided to remove completely the custom component and reinstall it.
But i can't complete the integration process via UI.
This is the log:
`2020-06-24 10:44:48 ERROR (MainThread) [aiohttp.server] Error handling request

ValueError: 1004 is not a valid ErrorCodes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 102, in _authenticated_post

    result_code = ErrorCodes(code)

  File "/usr/local/lib/python3.7/enum.py", line 310, in __call__

    return cls.__new__(cls, value)

  File "/usr/local/lib/python3.7/enum.py", line 564, in __new__

    raise exc

  File "/usr/local/lib/python3.7/enum.py", line 548, in __new__

    result = cls._missing_(value)

  File "/usr/local/lib/python3.7/enum.py", line 577, in _missing_

    raise ValueError("%r is not a valid %s" % (value, cls.__name__))

ValueError: 1004 is not a valid ErrorCodes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start

    resp = await task

  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle

    resp = await handler(request)

  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle

    result = await result

  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post

    return await super().post(request, flow_id)

  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper

    result = await method(view, request, *args, **kwargs)

  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post

    result = await self._flow_mgr.async_configure(flow_id, data)

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure

    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step

    result: Dict = await getattr(flow, method)(user_input)

  File "/config/custom_components/meross_cloud/config_flow.py", line 48, in async_step_user

    self._test_authorization, username, password

  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/meross_cloud/config_flow.py", line 75, in _test_authorization

    client = MerossHttpClient.from_user_password(email=username, password=password)

  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 42, in from_user_password

    creds = cls.login(email, password)

  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 48, in login

    response_data = cls._authenticated_post(_LOGIN_URL, params_data=data)

  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 121, in _authenticated_post

    raise AuthenticatedPostException("Failed request to API. Response was: %s" % str(jsondata))

meross_iot.api.AuthenticatedPostException: Failed request to API. Response was: {'apiStatus': 1004, 'sysStatus': 0, 'data': None, 'info': 'A', 'timeStamp': '2020-06-24 08:44:48'}`

and the screen from HA integration:
![image](https://user-images.githubusercontent.com/3518802/85524250-4ad9c200-b608-11ea-8760-5b3116c4c88e.png)

**Comment by Malaga82** [comment]
The issue is the password: **must be up to 10 chars**...don't know why it's not stated anywhere they changed this.
