### ISSUE TITLE
Can't find device with firmware under V3

### ISSUE THREAD

**Issue by Gobolin80** [albertogeniola/meross-homeassistant#110]
Hi Alberto,
I have 2 valve with firmware v3 and another one with v1.
Integration doesn't show the last one (v1).
Is it a limit of Meross Cloud o is a bug?
Thank for your work!

**Comment by albertogeniola** [comment]
Hi @Gobolin80 ,

can you post the logs of HomeAssistant? That will reveal us if the device is "seen" from the low-level MerossIot library.

**Comment by Gobolin80** [comment]
Hi @albertogeniola ,
this is my log.
How you can see it founds only 2 device (the v3 device) but desn't find my only V1 device.
Thanks for you support

`2020-07-26 18:18:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. 
This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-07-26 18:18:42 INFO (MainThread) [custom_components.meross_cloud.version] MerossCloudVersion: 0.4.0.0
2020-07-26 18:18:42 INFO (MainThread) [homeassistant.setup] Setting up meross_cloud
2020-07-26 18:18:43 INFO (MainThread) [homeassistant.setup] Setup of domain meross_cloud took 1.6 seconds
2020-07-26 18:18:44 INFO (MainThread) [custom_components.meross_cloud] Found application token issued on 2020-07-10 23:38:05.844023 to xxxxxxxxxx@gmail.com. Using it.
2020-07-26 18:18:45 WARNING (MainThread) [custom_components.meross_cloud] 
Meross Cloud Custom component
https://github.com/albertogeniola/meross-homeassistant/issues
2020-07-26 18:18:45 INFO (MainThread) [custom_components.meross_cloud] Starting meross manager
2020-07-26 18:18:45 INFO (MainThread) [meross_iot.manager] Initializing the MQTT connection...
2020-07-26 18:18:46 WARNING (Thread-12) [meross_iot.manager] Subscribed to topics, updating state for already known devices...
2020-07-26 18:18:46 INFO (MainThread) [custom_components.meross_cloud] Discovering Meross devices...
2020-07-26 18:18:46 INFO (MainThread) [meross_iot.manager] 
2020-07-26 18:18:46 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {}
2020-07-26 18:18:46 INFO (MainThread) [meross_iot.manager] The following devices are new to me: [<meross_iot.model.http.device.HttpDeviceInfo object at 0xaca3b3e8>]
2020-07-26 18:18:46 INFO (MainThread) [meross_iot.manager] Updating 0 known devices form HTTPINFO and fetching data from 1 newly discovered devices...
2020-07-26 18:18:46 WARNING (MainThread) [meross_iot.device_factory] Device Smart Hub (msh300, uuid xxxxxxxxxxxxxxxxxxxx) reported ability Appliance.Digest.Hub. Assuming this is a full-featured HUB.
2020-07-26 18:18:46 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-26 18:18:47 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-07-26 18:18:47 INFO (MainThread) [meross_iot.manager] 
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.light] Setting up light.meross_cloud
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.switch] Setting up switch.meross_cloud
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.cover] Setting up cover.meross_cloud
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.meross_cloud
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.climate] Setting up climate.meross_cloud
2020-07-26 18:18:47 INFO (MainThread) [homeassistant.components.fan] Setting up fan.meross_cloud
2020-07-26 18:18:47 WARNING (MainThread) [custom_components.meross_cloud.sensor] Found 2 devices that require polling. Setting polling interval to 0:00:30
2020-07-26 18:18:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:18:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo cucina (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:19:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:19:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo cucina (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:19:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:19:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:20:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:20:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:20:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:21:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:21:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:21:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:22:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:22:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:22:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:23:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:23:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:23:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:24:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:24:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:24:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:25:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:25:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:25:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:26:17 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Termo bagno (mts100v3) - temperature sensor (°C, 0) as its value is recent enough
2020-07-26 18:26:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo bagno (mts100v3) - temperature sensor (°C, 0)
2020-07-26 18:26:47 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Termo cucina (mts100v3) - temperature sensor (°C, 0)
`

**Comment by dustardly** [comment]
Me too v1 version no entities found

**Comment by pista73** [comment]
Ciao a tutti e grazie per il vostro aiuto , sono anche io nella stessa condizione mi vede la valvola v3 ma non più la valvola v2 che prima andava .....

**Comment by albertogeniola** [comment]
Hi guys,
yeah, the new version of the library has been developed to support ThermostatV3. Unfortunately I do not own any Thermostat V1 or V2, so it is really difficult to me to "guess" how they work. In any case, you can contribute to the cause by collecting the data exchanged between the Meross App and the device, by using the Sniffing Tool that I've just released (please updat to v 0.4.0.2).

[Have a look at here](https://albertogeniola.github.io/MerossIot/advanced-topics.html#sniff-device-data). Would you mind uploading the sniffed data so that I can inspect that and try to add support for that?

**Comment by Gobolin80** [comment]
Hi @albertogeniola .
unfortunately I haven't PC with Linux installed.
I suppose that I can use your sniffer only with Linux. It's right?

**Comment by albertogeniola** [comment]
Hi @Gobolin80 , 
I actually run it on windows without any problem. You just have to install the library and then run the appropriate command. You can do that from the command prompt as follows:

```bash
pip install meross_iot --upgrade
meross_sniffer
```

**Comment by Gobolin80** [comment]
Ah ok @albertogeniola !
I will try in the next day.
Thank you

**Comment by Gobolin80** [comment]
> Hi @Gobolin80 ,
> I actually run it on windows without any problem. You just have to install the library and then run the appropriate command. You can do that from the command prompt as follows:
> 
> ```shell
> pip install meross_iot --upgrade
> meross_sniffer
> ```

Hi @albertogeniola ,
I'm trying to run meross_sniffer but I recive thi error:

C:\Windows\system32>meross_sniffer
Traceback (most recent call last):
  File "c:\users\XXXX\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\XXXX\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\Scripts\meross_sniffer.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'utilities'

I'm very very noob in Python, so I'm sorry if I made a stupid mistake :)

**Comment by Gobolin80** [comment]
Hi @albertogeniola ,
I'm not sure if you saw mi previous comment, so I repost it.
Thank you so much


> Hi @albertogeniola ,
> I'm trying to run meross_sniffer but I recive thi error:
> 
> C:\Windows\system32>meross_sniffer
> Traceback (most recent call last):
> File "c:\users\XXXX\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "c:\users\XXXX\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\XXXX\AppData\Local\Programs\Python\Python38\Scripts\meross_sniffer.exe__main__.py", line 4, in
> ModuleNotFoundError: No module named 'utilities'
> 
> I'm very very noob in Python, so I'm sorry if I made a stupid mistake :)

**Comment by albertogeniola** [comment]
Hi @Gobolin80 ,
I've doublechecked and actually you spotted a bug. I've released MerossIot v0.4.1.0rc5 which should solve the issue. Can you please go ahead installing that version and invoking the meross_sniffer again?

**Comment by MrLuppolo** [comment]
hi all

Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.1.0rc7

i've this log:
- Smart Hub (msh300) - OnlineStatus.ONLINE
.......

2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Device Smart Hub (msh300, uuid 1811066957078229086034298f17cf49) reported ability Appliance.Digest.Hub. Assuming this is a full-featured HUB.
2020-12-21 14:42:33 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.
2020-12-21 14:42:33 WARNING (MainThread) [meross_iot.device_factory] Could not find any specific subdevice class for type mts100. Applying generic SubDevice class.

Only discover HUB but not termostats (i've 6 termostats), the meross app working fine. Any solution?

Regards
Francesco

**Comment by gluca** [comment]
Hi Alberto,
I have both V1 and V3 smart valves and have some programming background. How can I contribute to resolve this issue with old V1 thermostat?

**Comment by gluca** [comment]
Here some sniff (up/down target temperature, sensor on/off, calibration up/down)

INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '5b57d1b015790286e4fdc071fbe90f99', 'method': 'SET', 'namespace': 'Appliance.Hub.Mts100.Temperature', 'payloadVersion': 1, 'sign': 'd03f31f876488435db97ccb44c06ace3', 'timestamp': 1608764533, 'triggerSrc': 'Android'}, 'payload': {'temperature': [{'custom': 225, 'id': '0000150C'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '3c83545420a60cbfa143365ff7ee8018', 'method': 'SET', 'namespace': 'Appliance.Hub.Mts100.Temperature', 'payloadVersion': 1, 'sign': '894bf9c5f85c37569c93f83a7be02683', 'timestamp': 1608764539, 'triggerSrc': 'Android'}, 'payload': {'temperature': [{'custom': 200, 'id': '0000150C'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': 'b9b2f5b690615f59c02639e9132c4f9d', 'method': 'SET', 'namespace': 'Appliance.Hub.Mts100.Temperature', 'payloadVersion': 1, 'sign': 'b9353f685742b4e3800c69f45c502ced', 'timestamp': 1608764541, 'triggerSrc': 'Android'}, 'payload': {'temperature': [{'custom': 215, 'id': '0000150C'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '398e66128049a86fc5be9a67253fd9ee', 'method': 'SET', 'namespace': 'Appliance.Hub.ToggleX', 'payloadVersion': 1, 'sign': '566a362adcc1d1c0c2c70800bb7b32c4', 'timestamp': 1608764551, 'triggerSrc': 'Android'}, 'payload': {'togglex': [{'channel': 0, 'id': '0000150C', 'onoff': 0}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '7ed1142f53844295ddc96498e7665c67', 'method': 'SET', 'namespace': 'Appliance.Hub.ToggleX', 'payloadVersion': 1, 'sign': 'c9b689cb9e3586edb5268dbcf25fce2e', 'timestamp': 1608764555, 'triggerSrc': 'Android'}, 'payload': {'togglex': [{'channel': 0, 'id': '0000150C', 'onoff': 1}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': 'b2af27fd2cba4d2b30f9ddb4fed50049', 'method': 'GET', 'namespace': 'Appliance.Hub.Mts100.Adjust', 'payloadVersion': 1, 'sign': '5a89d137129aea4c8fd7df530d187337', 'timestamp': 1608764567, 'triggerSrc': 'Android'}, 'payload': {'adjust': [{'id': '0000150C'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '596fa6bf1f92b1fd0de0647b46819e68', 'method': 'SET', 'namespace': 'Appliance.Hub.Mts100.Adjust', 'payloadVersion': 1, 'sign': 'd4abc96c7180b5f7861da6d5b77bd2e4', 'timestamp': 1608764580, 'triggerSrc': 'Android'}, 'payload': {'adjust': [{'id': '0000150C', 'temperature': -350}]}}
INFO:USER-TOPIC (/app/514789/subscribe) <- {'header': {'timestampMs': 792, 'timestamp': 1608764581, 'sign': 'e4b8e451d8dbd545ad7f787835d2ef08', 'payloadVersion': 1, 'namespace': 'Appliance.Hub.Mts100.Temperature', 'method': 'PUSH', 'messageId': 'd2c5fa0efec51a338554f789921ecf22', 'from': '/appliance/1811067604072929086034298f17cfee/publish'}, 'payload': {'temperature': [{'room': 200, 'id': '0000150C'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': 'a2ff782b03b97121028f8016939e00c9', 'method': 'GET', 'namespace': 'Appliance.Hub.Mts100.Adjust', 'payloadVersion': 1, 'sign': 'ed5dcb0186a49ea41faacb55f6b224be', 'timestamp': 1608764584, 'triggerSrc': 'Android'}, 'payload': {'adjust': [{'id': '0000150C'}]}}
INFO:USER-TOPIC (/app/514789/subscribe) <- {'header': {'timestampMs': 569, 'timestamp': 1608764587, 'sign': '841924d5b4547e0379adc30f3443ed8a', 'payloadVersion': 1, 'namespace': 'Appliance.Hub.ToggleX', 'method': 'PUSH', 'messageId': '421da346e409f02df869657c0178e5c1', 'from': '/appliance/1811067604072929086034298f17cfee/publish'}, 'payload': {'togglex': [{'onoff': 1, 'id': '0000150C'}]}}
INFO:USER-TOPIC (/app/514789/subscribe) <- {'header': {'timestampMs': 630, 'timestamp': 1608764588, 'sign': '61748235ecd0a3f8692632509759d535', 'payloadVersion': 1, 'namespace': 'Appliance.Hub.Mts100.Temperature', 'method': 'PUSH', 'messageId': '4dac07098c69ef2dc732531232da1d4f', 'from': '/appliance/1811067604072929086034298f17cfee/publish'}, 'payload': {'temperature': [{'id': '0000150C', 'economy': 200, 'custom': 215, 'currentSet': 215, 'comfort': 230}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '02184df33da97d509af572e4fa55ccc9', 'method': 'SET', 'namespace': 'Appliance.Hub.Mts100.Adjust', 'payloadVersion': 1, 'sign': 'c18d0975d9e7e64483301ea4363ad125', 'timestamp': 1608764590, 'triggerSrc': 'Android'}, 'payload': {'adjust': [{'id': '0000150C', 'temperature': -500}]}}
INFO:USER-TOPIC (/app/514789/subscribe) <- {'header': {'timestampMs': 429, 'timestamp': 1608764590, 'sign': 'ea9b95d560a0a6f68bd907da0106eb9d', 'payloadVersion': 1, 'namespace': 'Appliance.Hub.Mts100.Temperature', 'method': 'PUSH', 'messageId': 'a8f4cd0de507f252c3de722339bc9d7b', 'from': '/appliance/1811067604072929086034298f17cfee/publish'}, 'payload': {'temperature': [{'room': 185, 'id': '0000150C'}]}}

**Comment by gluca** [comment]
here the refresh command, produced this output:

INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '933a0fa036c29e080f1be54f97b00692', 'method': 'GET', 'namespace': 'Appliance.System.All', 'payloadVersion': 1, 'sign': 'acb9c0cc801b5e31152df6986b2d235f', 'timestamp': 1608764848, 'triggerSrc': 'Android'}, 'payload': {}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '6ef044df70910dec11a25089e64a18a3', 'method': 'GET', 'namespace': 'Appliance.Hub.Mts100.All', 'payloadVersion': 1, 'sign': '0839b8be58b456d6a0aec656aea50cf6', 'timestamp': 1608764848, 'triggerSrc': 'Android'}, 'payload': {'all': [{'id': '0000150C'}, {'id': '0000153E'}, {'id': '000015C5'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '9ee9bbf14513bf99768f80baa905314a', 'method': 'GET', 'namespace': 'Appliance.Hub.Mts100.All', 'payloadVersion': 1, 'sign': '727a126ab0bcaf907ad7980f2e7c5a3e', 'timestamp': 1608764849, 'triggerSrc': 'Android'}, 'payload': {'all': [{'id': '01000875'}, {'id': '01005D50'}, {'id': '01005D62'}, {'id': '0100CCFA'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': 'aef71045023e45d3f34d27b5af745fb5', 'method': 'GET', 'namespace': 'Appliance.Hub.Battery', 'payloadVersion': 1, 'sign': '249626f12349677be0893f0b27d003ea', 'timestamp': 1608764849, 'triggerSrc': 'Android'}, 'payload': {'battery': [{'id': '0000150C'}, {'id': '0000153E'}, {'id': '000015C5'}]}}
INFO:DEVICE-TOPIC (/appliance/1811067604072929086034298f17cfee/subscribe) <- {'header': {'from': '/app/514789-0ef160ab12300ffa474c0839d26a4749/subscribe', 'messageId': '8a7f6799b7611f337707f26e7159d01c', 'method': 'GET', 'namespace': 'Appliance.Hub.Battery', 'payloadVersion': 1, 'sign': 'eee20af36963deacf09833c6008a9ad3', 'timestamp': 1608764849, 'triggerSrc': 'Android'}, 'payload': {'battery': [{'id': '01000875'}, {'id': '01005D50'}, {'id': '01005D62'}, {'id': '0100CCFA'}]}}
INFO:USER-TOPIC (/app/514789/subscribe) <- {'header': {'timestampMs': 370, 'timestamp': 1608764858, 'sign': '95334893ead7727e30affa4b640a1727', 'payloadVersion': 1, 'namespace': 'Appliance.Hub.Mts100.Temperature', 'method': 'PUSH', 'messageId': '4beb6cc427802e7e1add249fc9fa29b9', 'from': '/appliance/1811067604072929086034298f17cfee/publish'}, 'payload': {'temperature': [{'room': 225, 'id': '01005D62', 'heating': 0}]}}
