### ISSUE TITLE
Unknown error when setting up integration after upgrade

### ISSUE THREAD

**Issue by bwohl** [albertogeniola/meross-homeassistant#114]
I just upgraded to v 1.0.0. and when I try to add the integration again it says "An unknown error occured" after typing in my meross login details. 
This is what I could find in the log file:

  File "/usr/local/lib/python3.7/site-packages/meross_iot/http_api.py", line 98, in async_login
    response_data = await cls._async_authenticated_post(_LOGIN_URL, params_data=data)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/http_api.py", line 157, in _async_authenticated_post
    raise AuthenticatedPostException(f"Unknown/Unhandled response code received from API. "
meross_iot.model.http.exception.AuthenticatedPostException: Unknown/Unhandled response code received from API. Response was: {'apiStatus': 1004, 'sysStatus': 0, 'data': None, 'info': 'A', 'timeStamp': '2020-07-12 16:56:32'}

**Comment by bwohl** [comment]
Ok, I was typing in the wrong password, so it was correct to give an error. 
A more meaningful error message ("Incorrect username or password") would be helpful :)

**Comment by albertogeniola** [comment]
The last versions of the component do provide specific errors for bad logins

**Comment by brillo83** [comment]
Hi Alberto,

after updating my custom_component folder with the latest of meross_cloud version I get the error "An unknown error occured". If I restore the previous version (2020-05-01) the integration works but no entity is found in home assistant. Any suggestion?

**Comment by brillo83** [comment]
The homeassistant log:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/config_flow.py", line 49, in async_step_user
    creds = await self._test_authorization(username, password)
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/config_flow.py", line 74, in _test_authorization
    client = await MerossHttpClient.async_from_user_password(email=username, password=password)
  File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/http_api.py", line 102, in async_from_user_password
    creds = await cls.async_login(email, password)
  File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/http_api.py", line 132, in async_login
    response_data = await cls._async_authenticated_post(_LOGIN_URL, params_data=data, mask_params_in_log=True)
  File "/srv/homeassistant/lib/python3.8/site-packages/meross_iot/http_api.py", line 183, in _async_authenticated_post
    async with session.post(url, data=payload, headers=headers) as response:
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1057, in _create_direct_connection
    raise last_exc
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1026, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 977, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host iot.meross.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Home Assistant si è avviato!
