### ISSUE TITLE
Lost switch entity <fails ValueError: 0 is not a valid OnlineStatus>

### ISSUE THREAD

**Issue by antivirus68** [albertogeniola/meross-homeassistant#115]
Hi Alberto,

I've installed today the new release v1.0.0 on HA 0.112.2.
You did a really a nice job with this new version.

But I have a problem.
It started fine, every single entity is discoved and everything works fine, till few hours later when a switch entity got "unavailable".
The power entities for the same power outlet are still working, but not the switch (Device Presa addolcitore (mss310r).

Here is the log, you'll see the error 2020-07-14 13:24:40 ERROR (MainThread) [homeassistant.helpers.entity]

```
2020-07-14 13:24:30 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (W, 0) reported online event.
2020-07-14 13:24:30 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (A, 0) reported online event.
2020-07-14 13:24:30 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (V, 0) reported online event.
2020-07-14 13:24:30 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Presa addolcitore (mss310r) - Main channel reported online event.
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f722bbe90>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:30 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f7cc251d0>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:31 INFO (MainThread) [custom_components.meross_cloud.switch] Skipping device <Entity Presa addolcitore (mss310r) - Main channel: on> as it was already added to registry once.
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f77020950>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:31 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (W, 0): 4.602> as it was already added to registry once.
2020-07-14 13:24:31 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (A, 0): 0.078> as it was already added to registry once.
2020-07-14 13:24:31 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (V, 0): 241.9> as it was already added to registry once.
2020-07-14 13:24:31 WARNING (MainThread) [custom_components.meross_cloud.sensor] Found 15 devices that require polling. Setting polling interval to 0:03:45
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f72ce6410>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:31 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:32 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN "uuid:4d696e69-444c-164e-9d42-9c3dcff54426" not found, aborting
2020-07-14 13:24:32 INFO (MainThread) [homeassistant.components.upnp] Unable to create UPnP/IGD, aborting
2020-07-14 13:24:32 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds.
2020-07-14 13:24:32 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f75e60610>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:32 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:32 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:32 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:32 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:39 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (W, 0) reported online event.
2020-07-14 13:24:39 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (A, 0) reported online event.
2020-07-14 13:24:39 WARNING (MainThread) [custom_components.meross_cloud.sensor] Device Presa addolcitore (mss310r) - power sensor (V, 0) reported online event.
2020-07-14 13:24:39 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Presa addolcitore (mss310r) - Main channel reported online event.
2020-07-14 13:24:39 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:39 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Presa addolcitore (mss310r) - power sensor (W, 0)
2020-07-14 13:24:40 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa addolcitore (mss310r) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:40 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa addolcitore (mss310r) - power sensor (V, 0) as its value is recent enough
2020-07-14 13:24:40 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.presa_addolcitore_mss310r_main_channel fails
ValueError: 0 is not a valid OnlineStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/system.py", line 27, in async_update
    await self.async_handle_update(namespace=Namespace.SYSTEM_ALL, data=result)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/system.py", line 45, in async_handle_update
    status = OnlineStatus(int(online_data.get("status")))
  File "/usr/local/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/local/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 0 is not a valid OnlineStatus
2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f71d93c10>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:40 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f76306310>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:41 INFO (MainThread) [custom_components.meross_cloud.switch] Skipping device <Entity Presa addolcitore (mss310r) - Main channel: on> as it was already added to registry once.
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f75c9aad0>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (W, 0): 4.602> as it was already added to registry once.
2020-07-14 13:24:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (A, 0): 0.076> as it was already added to registry once.
2020-07-14 13:24:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Presa addolcitore (mss310r) - power sensor (V, 0): 240.0> as it was already added to registry once.
2020-07-14 13:24:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Found 15 devices that require polling. Setting polling interval to 0:03:45
2020-07-14 13:24:41 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f763b3b90>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1908027427194439087648e1e950c246 -------
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f770a8e90>: <meross_iot.device_factory.mss310r:2.0.0:2.1.4 object at 0x7f76169b90>}
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-14 13:24:42 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa addolcitore (mss310r) - power sensor (W, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa addolcitore (mss310r) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa addolcitore (mss310r) - power sensor (V, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Presa Tv Sala (mss310h) - power sensor (W, 0)
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa Tv Sala (mss310h) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa Tv Sala (mss310h) - power sensor (V, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Presa Tv Cucina (mss310h) - power sensor (W, 0)
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa Tv Cucina (mss310h) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa Tv Cucina (mss310h) - power sensor (V, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Lavastoviglie (mss310) - power sensor (W, 0)
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Lavastoviglie (mss310) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Lavastoviglie (mss310) - power sensor (V, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Refreshing instant metrics for device Presa tavernetta (mss310r) - power sensor (W, 0)
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa tavernetta (mss310r) - power sensor (A, 0) as its value is recent enough
2020-07-14 13:24:44 INFO (MainThread) [custom_components.meross_cloud.sensor] Skipping data refresh for Presa tavernetta (mss310r) - power sensor (V, 0) as its value is recent enough
```

Hope this can help to solve the problem.

Bye Marco

**Comment by mansbo** [comment]
I'm getting the same thing since upgrading to v1.0.0.  A switch becomes Unavailable and there is "ValueError: 0 is not a valid OnlineStatus" in the log.  One device today stayed unavailable until I restarted HA, but another came back online after a few hours without me having to do anything.  Both are MSS310s, and the power readings continue to work even though the switch (the main channel) was unavailable.

Thanks for all your hard work Alberto - it is very much appreciated!

**Comment by nosfevil** [comment]
Hi, i have same issue and problem.

**Comment by albertogeniola** [comment]
Hi guys,

thanks for reporting the bug. This is due to specific old device firmwares using 0 as "offline" status instead of 2. I will get this fixed as soon as the new low-level MerossIot library is released.

**Comment by albertogeniola** [comment]
Hi guys,

can you please test the pre-release v1.0.1rc and report back if the problem is now solved?

**Comment by antivirus68** [comment]
Hi Alberto,

I've just installed it.
I'll let you know if I'll have problems, so far so good.

Thanks Marco

**Comment by mansbo** [comment]
Hi Alberto,

I've been running the new version since last night and so far this error has not appeared, so looks good!

Thanks!

**Comment by nosfevil** [comment]
Nessun problema riscontrato da quando ho aggiornato. Grazie per il tuo lavoro.

**Comment by albertogeniola** [comment]
Good, so I'll soon promote this version to 1.0.1 stable. Thanks a lot to everyone and stay tuned!

**Comment by antivirus68** [comment]
Hi Alberto,

I just got home and I found another plug with the same error. I got the error this morning:

Meross 1.0.1rc 
HA 113.1

```
2020-07-29 10:20:40 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1911019187899325186848e1e910e075 -------
2020-07-29 10:20:41 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.presa_lavastoviglie_mss310_main_channel fails
ValueError: 0 is not a valid OnlineStatus

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 27, in async_update
    await self.async_handle_update(namespace=Namespace.SYSTEM_ALL, data=result)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/toggle.py", line 65, in async_handle_update
    super_handled = await super().async_handle_update(namespace=namespace, data=data)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 45, in async_handle_update
    status = OnlineStatus(int(online_data.get("status")))
  File "/usr/local/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/local/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 0 is not a valid OnlineStatus
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f6fd44dc0>: <meross_iot.device_factory.mss310:2.0.0:2.1.14 object at 0x7f757618e0>}
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1911019187899325186848e1e910e075 -------
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f6fd448e0>: <meross_iot.device_factory.mss310:2.0.0:2.1.14 object at 0x7f757618e0>}
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-29 10:20:41 INFO (MainThread) [custom_components.meross_cloud.switch] Skipping device <Entity Lavastoviglie (mss310) - Main channel: on> as it was already added to registry once.
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1911019187899325186848e1e910e075 -------
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f76b3aeb0>: <meross_iot.device_factory.mss310:2.0.0:2.1.14 object at 0x7f757618e0>}
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-29 10:20:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Lavastoviglie (mss310) - power sensor (W, 0): 0.0> as it was already added to registry once.
2020-07-29 10:20:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Lavastoviglie (mss310) - power sensor (A, 0): 0.0> as it was already added to registry once.
2020-07-29 10:20:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Lavastoviglie (mss310) - power sensor (V, 0): 238.7> as it was already added to registry once.
2020-07-29 10:20:41 WARNING (MainThread) [custom_components.meross_cloud.sensor] Found 15 devices that require polling. Setting polling interval to 0:03:45
2020-07-29 10:20:41 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1911019187899325186848e1e910e075 -------
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f74d02760>: <meross_iot.device_factory.mss310:2.0.0:2.1.14 object at 0x7f757618e0>}
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------

2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] 

------- Triggering HTTP discovery, filter_device: 1911019187899325186848e1e910e075 -------
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] The following devices were already known to me: {<meross_iot.model.http.device.HttpDeviceInfo object at 0x7f78c98df0>: <meross_iot.device_factory.mss310:2.0.0:2.1.14 object at 0x7f757618e0>}
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] The following devices are new to me: []
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] Updating 1 known devices form HTTPINFO and fetching data from 0 newly discovered devices...
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] Fetch and update done
2020-07-29 10:20:42 INFO (MainThread) [meross_iot.manager] 
------- HTTP discovery ended -------
```

Sorry, I couldn't reply earlier.

Bye
Marco
