### ISSUE TITLE
Timeout occurred while waiting a response for message

### ISSUE THREAD

**Issue by ccorderod** [albertogeniola/meross-homeassistant#117]
Hi @albertogeniola 
I found those errors on my log today. Devices are still operational.

```
2020-07-20 15:23:25 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/340546-e53ea49b3c5f49b3e0117dae468a8527/subscribe", "messageId": "885ba9dfba023b6b9ceb949b437c5318", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "28fbfd30ce149ad0de30c2c2959949b6", "timestamp": 1595251400}, "payload": {"channel": 0}}' sent to device uuid 19082967718555251h1248e1e9009b31. Timeout was: 5 seconds
2020-07-20 15:23:25 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.0.0
Device info: 
	Name: Plug13_xeon
	UUID: 19082967718555251h1248e1e9009b31
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.14
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 536, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 230, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/device.py", line 200, in _execute_command
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 530, in async_execute_cmd
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 540, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2020-07-20 15:23:30 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/340546-e53ea49b3c5f49b3e0117dae468a8527/subscribe", "messageId": "1a99103f14d23f94edc8d3cfd740a08f", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "bd44425b44063b369368cdc3e0c62f3c", "timestamp": 1595251405}, "payload": {"channel": 0}}' sent to device uuid 19082967718555251h1248e1e9009b31. Timeout was: 5 seconds
2020-07-20 15:23:30 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.0.0
Device info: 
	Name: Plug13_xeon
	UUID: 19082967718555251h1248e1e9009b31
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.14
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 536, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 264, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/device.py", line 200, in _execute_command
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 530, in async_execute_cmd
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 540, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2020-07-20 15:23:35 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/340546-e53ea49b3c5f49b3e0117dae468a8527/subscribe", "messageId": "c31a30de0a9c3ac843f07d3f10904bcc", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "24b14d4acd0a5ace7c52c0c234e8b450", "timestamp": 1595251410}, "payload": {"channel": 0}}' sent to device uuid 19082967718555251h1248e1e9009b31. Timeout was: 5 seconds
2020-07-20 15:23:35 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.0.0
Device info: 
	Name: Plug13_xeon
	UUID: 19082967718555251h1248e1e9009b31
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.14
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 536, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 299, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/device.py", line 200, in _execute_command
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 530, in async_execute_cmd
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 540, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2020-07-20 15:23:40 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/340546-e53ea49b3c5f49b3e0117dae468a8527/subscribe", "messageId": "5699d74818ab8bc0bfd8a207825bf49f", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "686585c75ef1dd347f5fc16b687cf957", "timestamp": 1595251415}, "payload": {"channel": 0}}' sent to device uuid 19082921242461251h1248e1e9009c95. Timeout was: 5 seconds
2020-07-20 15:23:40 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.0.0
Device info: 
	Name: Plug11_salon
	UUID: 19082921242461251h1248e1e9009c95
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.14
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 536, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 230, in _sensor_async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command("GET", Namespace.CONTROL_ELECTRICITY, {'channel': channel})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/controller/device.py", line 200, in _execute_command
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 530, in async_execute_cmd
    timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 540, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

**Comment by albertogeniola** [comment]
Hi @ccorderod ,

as long as the devices are still operational, this is not an issue. Simply, the connection was interrupted (could either be the meross plug or your homeassistant). However, the library recovered from thenetwork error, and that's the way it should be. You could ignore such errors.
