### ISSUE TITLE
Meross integration doesn't show the entities

### ISSUE THREAD

**Issue by eagle-phoenix** [albertogeniola/meross-homeassistant#122]
Hello, here are some logs of the integration in my homeassistant. The problem is that I can't find any meross entity. In Configurations > Integrations there is no one entity, in entities or devices the same. I looked for old entities (the previous version did work reallly well) but they don't exist anymore.

LOG 1: 
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:140
Integration: Meross Cloud IoT (documentation)
First occurred: 7:52:04 (44 occurrences)
Last logged: 9:28:40

Error occurred. ------------------------------------- Component version: 0.4.0.0 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 140, in async_setup_entry
    await manager.async_init()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 170, in async_init
    self._mqtt_client.connect(host=self._domain, port=self._port, keepalive=30)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

LOG 2: I think this is OK, I don't know why the entities don't show up in the configuration>integrations section.
Detalles de registro (WARNING)
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:138
Integration: Meross Cloud IoT (documentation)
First occurred: 7:51:04 (44 occurrences)
Last logged: 9:27:40

=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level library version: 0.4.0.0 ------------------------------- This custom component is under development and not yet ready for production use. In case of errors/misbehave, please report it here: https://github.com/albertogeniola/meross-homeassistant/issues If you like this extension and you want to support it, please consider donating. ------------------------------- List of devices reported by HTTP API: - Luz (mss310) - OnlineStatus.ONLINE - Estufa grande (mss210) - OnlineStatus.OFFLINE - Riego (mss210) - OnlineStatus.OFFLINE - Radiador de Aceite (mss310) - OnlineStatus.OFFLINE ===============================
=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level library version: 0.4.0.0 ------------------------------- This custom component is under development and not yet ready for production use. In case of errors/misbehave, please report it here: https://github.com/albertogeniola/meross-homeassistant/issues If you like this extension and you want to support it, please consider donating. ------------------------------- List of devices reported by HTTP API: - Luz (mss310) - OnlineStatus.ONLINE - Estufa grande (mss210) - OnlineStatus.ONLINE - Riego (mss210) - OnlineStatus.ONLINE - Radiador de Aceite (mss310) - OnlineStatus.ONLINE ===============================

Thanks very much in advance, and thank you Alberto for your work.

**Comment by albertogeniola** [comment]
Hi @eagle-phoenix ,

from the first log it looks like that device was unable to reach the internet. The second log seems ok, though. I'd advice to fully remove the Meross integration, reboot and then reinstall it and reboot once again. This will produce a clean installation. Can you try that?

**Comment by albertogeniola** [comment]
Closing for inactivity. In case this still persists, feel free to re-open it.
