### ISSUE TITLE
MSS210HK Plugs not found

### ISSUE THREAD

**Issue by c0nt4x** [albertogeniola/meross-homeassistant#129]
Hi

I installed the integration and have two MSS210HK smart plugs but neither are showing in the integration. 

I have done a clean install of the integration and the plugs (via Meross app and HomeKit) and the plugs only show in HA entities as device trackers but still not showing in the Integration.

Can you please advise?

**Comment by Manfredi93** [comment]
Hi, I have the same issue.
This is my log:
`List of devices reported by HTTP API:
- Piantana Salotto (mss210) - OnlineStatus.ONLINE
- Piantana Letto (mss210) - OnlineStatus.ONLINE
===============================
2020-08-29 20:23:24 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
-------------------------------------
Component version: 0.4.0.0
Device info: 
<Unavailable>
Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 140, in async_setup_entry
    await manager.async_init()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 170, in async_init
    self._mqtt_client.connect(host=self._domain, port=self._port, keepalive=30)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2020-08-29 20:23:24 WARNING (MainThread) [homeassistant.config_entries] Config entry for meross_cloud not ready yet. Retrying in 5 seconds
2020-08-29 20:23:29 WARNING (MainThread) [custom_components.meross_cloud] `

**Comment by c0nt4x** [comment]
After uninstalling and reinstalling the integration for about the 8th time the Meross Integration tile/card now shows 2 devices and 2 entities, which is correct. 

However, they are still not showing anywhere in the HA device list And only show as device_tracker in HA entities list.

**Comment by c0nt4x** [comment]
Just had a play about with this. And I ended up doing a reboot instead of restart and that had resolved the issue.

**Comment by Manfredi93** [comment]
@c0nt4x I fix it disabling modem firewall...
