### ISSUE TITLE
Erreur with 0.116

### ISSUE THREAD

**Issue by msaphoto** [albertogeniola/meross-homeassistant#148]
Hello, 
I am an error.

Logger: homeassistant.config_entries
Source: custom_components/meross_cloud/__init__.py:197
First occurred: 22:09:40 (1 occurrences)
Last logged: 22:09:40

Error unloading entry atxxxxxxxx@gmail.com for meross_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 316, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/meross_cloud/__init__.py", line 197, in async_unload_entry
    hass.data[PLATFORM][plat].clear()
KeyError: 'light'

Tkt you

**Comment by Pawel128** [comment]
Hello
exactly the same for me:
Logger: homeassistant.config_entries
Source: custom_components/meross_cloud/__init__.py:197
First occurred: 22:13:55 (1 occurrences)
Last logged: 22:13:55

Error unloading entry yyy@zzz.xxx for meross_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 316, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/meross_cloud/__init__.py", line 197, in async_unload_entry
    hass.data[PLATFORM][plat].clear()
KeyError: 'light'

**Comment by Scialla** [comment]
same problem here; with 0.116 custom component don't work anymore...
```
Oct  7 22:13:07 raspberrypi hass[28001]: ===============================
Oct  7 22:13:07 raspberrypi hass[28001]: Meross Cloud Custom component
Oct  7 22:13:07 raspberrypi hass[28001]: Developed by Alberto Geniola
Oct  7 22:13:07 raspberrypi hass[28001]: Low level library version: 0.4.0.1
Oct  7 22:13:07 raspberrypi hass[28001]: -------------------------------
Oct  7 22:13:07 raspberrypi hass[28001]: This custom component is under development and not yet ready for production use.
Oct  7 22:13:07 raspberrypi hass[28001]: In case of errors/misbehave, please report it here:
Oct  7 22:13:07 raspberrypi hass[28001]: https://github.com/albertogeniola/meross-homeassistant/issues
Oct  7 22:13:07 raspberrypi hass[28001]: If you like this extension and you want to support it, please consider donating.
Oct  7 22:13:07 raspberrypi hass[28001]: -------------------------------
Oct  7 22:13:07 raspberrypi hass[28001]: List of devices reported by HTTP API:
Oct  7 22:13:07 raspberrypi hass[28001]: - Meross (mss425e) - OnlineStatus.ONLINE
Oct  7 22:13:07 raspberrypi hass[28001]: ===============================#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [custom_components.meross_cloud] Starting meross manager#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [meross_iot.manager] Initializing the MQTT connection...#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {}#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[33m2020-10-07 22:13:07 WARNING (Thread-7) [meross_iot.manager] Subscribed to topics, updating state for already known devices...#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[31m2020-10-07 22:13:07 ERROR (Thread-7) [root] Uncaught exception#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: Traceback (most recent call last):
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/thread.py", line 22, in run
Oct  7 22:13:07 raspberrypi hass[28001]:     run_old(*args, **kwargs)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Oct  7 22:13:07 raspberrypi hass[28001]:     self._target(*self._args, **self._kwargs)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
Oct  7 22:13:07 raspberrypi hass[28001]:     self.loop_forever(retry_first_connection=True)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
Oct  7 22:13:07 raspberrypi hass[28001]:     rc = self.loop(timeout, max_packets)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 1181, in loop
Oct  7 22:13:07 raspberrypi hass[28001]:     rc = self.loop_read(max_packets)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read
Oct  7 22:13:07 raspberrypi hass[28001]:     rc = self._packet_read()
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
Oct  7 22:13:07 raspberrypi hass[28001]:     rc = self._packet_handle()
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 2944, in _packet_handle
Oct  7 22:13:07 raspberrypi hass[28001]:     return self._handle_suback()
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 3151, in _handle_suback
Oct  7 22:13:07 raspberrypi hass[28001]:     self, self._userdata, mid, granted_qos)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/manager.py", line 349, in _on_subscribe
Oct  7 22:13:07 raspberrypi hass[28001]:     results = asyncio.gather(*tasks)
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/usr/lib/python3.7/asyncio/tasks.py", line 659, in gather
Oct  7 22:13:07 raspberrypi hass[28001]:     loop = events.get_event_loop()
Oct  7 22:13:07 raspberrypi hass[28001]:   File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
Oct  7 22:13:07 raspberrypi hass[28001]:     % threading.current_thread().name)
Oct  7 22:13:07 raspberrypi hass[28001]: RuntimeError: There is no current event loop in thread 'Thread-7'.#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (SyncWorker_12) [homeassistant.loader] Loaded systemmonitor from homeassistant.components.systemmonitor#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 1.5 seconds#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (SyncWorker_17) [homeassistant.loader] Loaded air_quality from homeassistant.components.air_quality#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [custom_components.meross_cloud] Discovering Meross devices...#033[0m
Oct  7 22:13:07 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:07 INFO (MainThread) [meross_iot.manager]
```

```
Oct  7 22:13:14 raspberrypi hass[28001]: #033[31m2020-10-07 22:13:14 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/107633-53227247c349d7e17963e683adda0011/subscribe", "messageId": "f49a560fc74810103bdaf54ed4321bb5", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "2b3f31db9d6f41266cb5de916260f3d3", "timestamp": 1602101589}, "payload": {}}' sent to device uuid 1810220467069629085334298f16f8dc. Timeout was: 5.0 seconds#033[0m
Oct  7 22:13:14 raspberrypi hass[28001]: #033[31m2020-10-07 22:13:14 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Meross (1810220467069629085334298f16f8dc). This device won't be enrolled.#033[0m
Oct  7 22:13:14 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:14 INFO (MainThread) [meross_iot.manager] Fetch and update done#033[0m
Oct  7 22:13:14 raspberrypi hass[28001]: #033[32m2020-10-07 22:13:14 INFO (MainThread) [meross_iot.manager]
Oct  7 22:13:14 raspberrypi hass[28001]: ------- HTTP discovery ended -------
Oct  7 22:13:14 raspberrypi hass[28001]: #033[0m
```

**Comment by Keltere** [comment]
On custom_components/meross_cloud/manifest.json
replace the 0.4.0.1 version with 0.4.0.5
"requirements": ["meross-iot==0.4.0.1"],
to
"requirements": ["meross-iot==0.4.0.5"],
then restart home assistant from the control panel

using visual studio code it will be really easy

**Comment by Pawel128** [comment]
It works for me, thank you

**Comment by Pawel128** [comment]
Unfortunately, it doesn't work for me again.

**Comment by msaphoto** [comment]
> Unfortunately, it doesn't work for me again.

Same for me.
Ok yesterday, no today

**Comment by albertogeniola** [comment]
Closing in favor of #149
