### ISSUE TITLE
Exception starting meross manager

### ISSUE THREAD

**Issue by hijackindie** [albertogeniola/meross-homeassistant#15]
I really would like this to work as I want to use the Meross power strips for a few places in my house.
Hassio 0.99.2
Installed via HACS.
Added meross credentials.
On restart of Hassio I see these errors in log:
2019-09-21 13:55:37 ERROR (MainThread) [custom_components.meross_cloud] An exception occurred while setting up the meross manager.
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 130, in async_setup
    manager.start()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 45, in start
    self._cloud_client.connect()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 167, in connect
    self._mqtt_client.connect(self._domain, self._port, keepalive=30)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

**Comment by albertogeniola** [comment]
Hey @hijackindie , 
the error seems to be related to network connectivity. Are you 100% sure the device is correctly connected to Internet? Is there any firewall preventing it from contacting the Meross AWS servers?

**Comment by albertogeniola** [comment]
Closing since no reply received in 30 days
