### ISSUE TITLE
Meross no longer starting

### ISSUE THREAD

**Issue by TheCellMC** [albertogeniola/meross-homeassistant#16]
Hi,
First of all, thanks for the amazing work. However, my meross devices don't seem to be connecting to the cloud.
Here is the log:

```
2019-09-22 18:58:32 ERROR (MainThread) [meross.manager] An unhandled error occurred while invoking callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 174, in _fire_event
    c(eventobj)
  File "/config/custom_components/meross_cloud/__init__.py", line 69, in event_handler
    enroll_device(self._hass, self._conf, evt.device)
  File "/config/custom_components/meross_cloud/__init__.py", line 42, in enroll_device
    if device.online and device.supports_consumption_reading():
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 162, in supports_consumption_reading
    return CONSUMPTIONX in self.get_abilities()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 134, in get_abilities
    self._abilities = self.execute_command("GET", ABILITY, {})['ability']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

What do you think is going on.

**Comment by TheCellMC** [comment]
Issue fixed on latest version
