### ISSUE TITLE
Component doesn't reconnect after error

### ISSUE THREAD

**Issue by jacekpaszkowski** [albertogeniola/meross-homeassistant#161]
When there is a problem with my iternet connection  i get this error:
```
2020-11-13 10:09:54 ERROR (MainThread) [homeassistant] Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 663, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET", namespace=Namespace.SYSTEM_ALL, payload={})
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 207, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 654, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 667, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

But after the connction is back again component doesn't reconnect my devices.

**Comment by coolguymatt** [comment]
I also have this issue

**Comment by albertogeniola** [comment]
Hi @jacekpaszkowski ,

that was handled in v1.0.4. Can you update and check if that solves the issue?

**Comment by jacekpaszkowski** [comment]
yes, it seems that now it's working ok.
