### ISSUE TITLE
"Timeout occurred while waiting a response for message" / "Failed to retrieve abilities for device"

### ISSUE THREAD

**Issue by dougware** [albertogeniola/meross-homeassistant#164]
I know there is an open issue for similar issues that were fixed by updating the manifest.json to
"requirements": ["meross-iot==0.4.0.5"]

Mine was already set to 0.4.0.5, I've also tried with 0.4.0.6. 

This is a new install, I'm attempting to leave SmartThings behind.  I can say that the Meross switches and the HA Pi are both on the same VLAN/subnet, but that it's a separate VLAN/subnet from the system I'm using to access the web GUI.

```2020-11-16 19:41:45 WARNING (MainThread) [custom_components.meross_cloud] 
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.0.5
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Living Room TV (mss110) - OnlineStatus.ONLINE
- Counter Lights (mss110) - OnlineStatus.ONLINE
- Office Dashboard TV (mss110) - OnlineStatus.ONLINE
- Office Roku TV (mss110) - OnlineStatus.ONLINE
===============================
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/REMOVED/subscribe", "messageId": "4779b272258dcf5340f164ecf5b57789", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "REMOVED", "timestamp": 1605555709}, "payload": {}}' sent to device uuid 2005157295453151800448e1e91c0dd4. Timeout was: 5.0 seconds
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Living Room TV (REMOVED). This device won't be enrolled.
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/REMOVED/subscribe", "messageId": "4b894343cb2f5bd8cd411e97df303469", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "REMOVED", "timestamp": 1605555709}, "payload": {}}' sent to device uuid 2005155116957351800448e1e91c038a. Timeout was: 5.0 seconds
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Counter Lights (REMOVED). This device won't be enrolled.
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/REMOVED/subscribe", "messageId": "3da1734a3b91e1608938214b72f878b8", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "REMOVED", "timestamp": 1605555709}, "payload": {}}' sent to device uuid 2005154115122351800448e1e91c13cb. Timeout was: 5.0 seconds
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Office Dashboard TV (REMOVED). This device won't be enrolled.
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/REMOVED/subscribe", "messageId": "1e7c4e70f11dac72b0673d689a205246", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "REMOVED", "timestamp": 1605555709}, "payload": {}}' sent to device uuid 2005153528757451800448e1e91c031b. Timeout was: 5.0 seconds
2020-11-16 19:41:53 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Office Roku TV (REMOVED). This device won't be enrolled.```

**Comment by jacekpaszkowski** [comment]
Similar errors in my case. 

```
2020-11-17 03:06:07 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/694293-13fbe8b4771c19e9cfca64c8af44d817/subscribe", "messageId": "72072d564613b8c77a9d78232a956c27", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "ba79ebb373bcb971f4b426ab7095b60f", "timestamp": 1605578763}, "payload": {}}' sent to device uuid 1909187877389490801748e1e951dc3f. Timeout was: 5 seconds.
2020-11-17 03:06:07 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.4.0.6.post2
Device info: 
	Name: Smart Outdoor Plug
	UUID: 1909187877389490801748e1e951dc3f
	Type: mss620
	HW Version: 3.0.0
	FW Version: 3.1.7
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 715, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET", namespace=Namespace.SYSTEM_ALL, payload={})
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 209, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 706, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 719, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

**Comment by smashley3000** [comment]
Similar errors here starting today, though my version is a bit older. Noticed others getting same errors, must be a change on HA side? I haven't updated meross in a while, was about to do so when I saw others with more current version have same problem.


===============================,
Meross Cloud Custom component,
Developed by Alberto Geniola,
Low level library version: 0.4.0.0,
This custom component is under development and not yet ready for production use.,
-------------------------------,
In case of errors/misbehave, please report it here: ,
If you like this extension and you want to support it, please consider donating.,
https://github.com/albertogeniola/meross-homeassistant/issues,
List of devices reported by HTTP API:,
- Living room shelf lights (mss110) - OnlineStatus.ONLINE,
- Printrbot (mss110) - OnlineStatus.OFFLINE,
- Living room lamp (mss110) - OnlineStatus.ONLINE,
- br (msl120b) - OnlineStatus.ONLINE,
- Kitchen lamp (msl120b) - OnlineStatus.ONLINE,
2020-11-19 20:16:52 WARNING (Thread-6) [meross_iot.manager] Subscribed to topics, updating state for already known devices...,
2020-11-19 20:16:58 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/REDACTED/subscribe", "messageId": "d2b26651f9a249ee9dc39a94f56a70eb", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "REDACTED", "timestamp": 1605831413}, "payload": {}}' sent to device uuid REDACTED. Timeout was: 5.0 seconds,
2020-11-19 20:16:58 ERROR (MainThread) [meross_iot.manager] Failed to retrieve abilities for device Living room shelf lights (REDACTED). This device won't be enrolled.
......


2020-11-19 20:16:58 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform meross_cloud.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by albertogeniola** [comment]
Hi @dougware : does the Meross APP work correctly when connected to the same network as Homeassistant is?

**Comment by albertogeniola** [comment]
About @smashley3000 's post, latest version v1.0.4 fixes some problems with HA 0.118.3: can you test that version please?

**Comment by smashley3000** [comment]
> About @smashley3000 's post, latest version v1.0.4 fixes some problems with HA 0.118.3: can you test that version please?

You rock! Updated both meross and HA (to 118.4 actually) and all is working again. I do get some warnings about api rate limits now but I believe that is probably expected at startup:


2020-11-27 12:20:05 WARNING (MainThread) [meross_iot.manager] Rate limit reached (RateLimitResult.GlobalLimitReached): api call will be delayed by 0.5 seconds,
2020-11-27 12:20:05 WARNING (MainThread) [meross_iot.manager] Rate limit reached (RateLimitResult.GlobalLimitReached): api call will be delayed by 1.0 seconds

**Comment by albertogeniola** [comment]
Hi @smashley3000 ,

I am glad it works now. The API rate limit messages are perfectly fine as you correctly guessed. In the near future they will be removed (severity lowered to INFO), but for now it is important to log that.

**Comment by dougware** [comment]
> Hi @dougware : does the Meross APP work correctly when connected to the same network as Homeassistant is?

Hello,

I'm running 2 VLANs, 2 subnets that are connected via the same router, there are no restrictions on them.

On my IOT subnet, I'm running the Meross devices as well as SmartThings (which I'm trying to leave behind ASAP).  I have the smartphone app on my regular VLAN.  Both SmartThings and the app work with the Meross devices.

**Comment by albertogeniola** [comment]
HI @dougware ,

can you test v1.0.4 please?

**Comment by dougware** [comment]
> HI @dougware ,
> 
> can you test v1.0.4 please?

Seems to be working now, thanks!

**Comment by albertogeniola** [comment]
I'm glad it does!
