### ISSUE TITLE
Errors in logs and device is unavailable

### ISSUE THREAD

**Issue by jacekpaszkowski** [albertogeniola/meross-homeassistant#165]
please see the erros i get. i think aftere those error device never becomes available, i have to restart HA or reload component

```
2020-11-22 04:30:26 WARNING (Thread-4) [meross_iot.manager] Client has been disconnected, however auto_reconnect flag is set. Won't stop the looping thread, as it will retry to connect.
2020-11-22 04:30:26 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Smart Outdoor Plug (mss620) - Main channel reported online event.
2020-11-22 04:30:26 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Smart Outdoor Plug (mss620) - Switch 1 reported online event.
2020-11-22 04:30:26 WARNING (MainThread) [custom_components.meross_cloud.switch] Device Smart Outdoor Plug (mss620) - Switch 2 reported online event.
2020-11-22 04:30:28 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2944, in _packet_handle
    return self._handle_suback()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3150, in _handle_suback
    self.on_subscribe(
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 506, in _on_subscribe
    _LOGGER.info(f"Updated {len(list(results))} devices.")
RuntimeError: await wasn't used with future
```
```
2020-11-22 04:30:33 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/694293-d4fcf056ae248f42792f130d87bd7463/subscribe", "messageId": "539299d75b9e36f70b3d4a99cf5f1d41", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "c0cb50c6c3a24af7b697a624e0819a27", "timestamp": 1606019428}, "payload": {}}' sent to device uuid 1909187877389490801748e1e951dc3f. Timeout was: 5 seconds.
2020-11-22 04:30:33 ERROR (Thread-1) [homeassistant] Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 715, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET", namespace=Namespace.SYSTEM_ALL, payload={})
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 209, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 706, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 719, in _async_send_and_wait_ack
    raise CommandTimeoutError()

```

**Comment by ucalegonte** [comment]
Having same error on my Meross msg100 device. Here is the log:
```
2020-11-22 23:54:36 WARNING (Thread-5) [meross_iot.manager] Client has been disconnected, however auto_reconnect flag is set. Won't stop the                                                                                                                                                       
 looping thread, as it will retry to connect.                                                                                                                                                                                                                                                      
2020-11-22 23:54:36 WARNING (Thread-5) [meross_iot.manager] Client has been disconnected, however auto_reconnect flag is set. Won't stop the                                                                                                                                                       
 looping thread, as it will retry to connect.                                                                                                                                                                                                                                                      
2020-11-22 23:54:36 WARNING (MainThread) [custom_components.meross_cloud.cover] Device Garage (msg100) - Main channel reported online event.                                                                                                                                                       
2020-11-22 23:54:36 WARNING (MainThread) [custom_components.meross_cloud.cover] Device Garage (msg100) - Main channel reported online event.                                                                                                                                                       
2020-11-22 23:54:37 ERROR (Thread-5) [root] Uncaught thread exception                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                                                                                                                                                      
    self.run()                                                                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.8/threading.py", line 870, in run                                                                                                                                                                                                                                   
    self._target(*self._args, **self._kwargs)                                                                                                                                                                                                                                                      
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main                                                                                                                                                                                                    
    self.loop_forever(retry_first_connection=True)                                                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever                                                                                                                                                                                                    
    rc = self.loop(timeout, max_packets)                                                                                                                                                                                                                                                           
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop                                                                                                                                                                                                            
    rc = self.loop_read(max_packets)                                                                                                                                                                                                                                                               
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read                                                                                                                                                                                                       
    rc = self._packet_read()                                                                                                                                                                                                                                                                       
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read                                                                                                                                                                                                    
    rc = self._packet_handle()                                                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2944, in _packet_handle                                                                                                                                                                                                  
    return self._handle_suback()                                                                                                                                                                                                                                                                   
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3150, in _handle_suback                                                                                                                                                                                                  
    self.on_subscribe(                                                                                                                                                                                                                                                                             
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 459, in _on_subscribe                                                                                                                                                                                                  
    _LOGGER.info(f"Updated {len(list(results))} devices.")                                                                                                                                                                                                                                         
RuntimeError: await wasn't used with future                                                                                                                                                                                                                                                        
2020-11-22 23:54:42 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/ap                                                                                                                                                       
p/671358-157910b4391cd0f7b9e64c802d47e8ea/subscribe", "messageId": "39026bc6ea0416dd2cf5dcf3b160dbfe", "method": "GET", "namespace": "Applia                                                                                                                                                       
nce.System.All", "payloadVersion": 1, "sign": "b31691cf52bc8e6ed706affa588df341", "timestamp": 1606085678}, "payload": {}}' sent to device u                                                                                                                                                       
uid 1911085403370690804648e1f91139b8. Timeout was: 5 seconds                                                                                                                                                                                                                                       
2020-11-22 23:54:42 ERROR (Thread-1) [homeassistant] Error doing job: _GatheringFuture exception was never retrieved                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 663, in _async_send_and_wait_ack                                                                                                                                                                                       
    return await asyncio.wait_for(future, timeout, loop=self._loop)                                                                                                                                                                                                                                
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for                                                                                                                                                                                                                          
    raise exceptions.TimeoutError()                                                                                                                                                                                                                                                                
asyncio.exceptions.TimeoutError                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                   
During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update                                                                                                                                                                                   
    result = await self._execute_command(method="GET", namespace=Namespace.SYSTEM_ALL, payload={})                                                                                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 207, in _execute_command                                                                                                                                                                                     
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,                                                                                                                                                                                                                
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 654, in async_execute_cmd                                                                                                                                                                                              
    response = await self._async_send_and_wait_ack(future=fut,                                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 667, in _async_send_and_wait_ack                                                                                                                                                                                       
    raise CommandTimeoutError()                                                                                                                                                                                                                                                                    
meross_iot.model.exception.CommandTimeoutError
```

**Comment by benderunit22** [comment]
saw the same after upgrading to HA 0.118.3.  Reverted back to 0.117.4 and all seems to be working again without disconnects.

**Comment by tahlequawesome** [comment]
On 0.118.3 hassos install I have to restart the integration repeatedly and eventually it will come online.

**Comment by benderunit22** [comment]
> On 0.118.3 hassos install I have to restart the integration repeatedly and eventually it will come online.

For me, the restart didn't help.  it would only come back online for a few hours and again become unavailable.  All my automation would break.

**Comment by miroivo** [comment]
Have tried everything, after reverted back to 0.117.4 is working again...

**Comment by atzbert** [comment]
Same here, reloading the integration helps, but only temporarily.. :\

**Comment by BenLaeft** [comment]
I assume I have the same issue 
`2020-11-27 15:58:59 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/738947-db930bfe9d90c00136345a5941005014/subscribe", "messageId": "bb2ad74f49eb0851c4536a9853cfcee8", "method": "GET", "namespace": "Appliance.System.Ability", "payloadVersion": 1, "sign": "1c812625219220c0fd47623bc5007110", "timestamp": 1606489134}, "payload": {}}' sent to device uuid 2006030644633251801048e1e91e22fe. Timeout was: 5.0 seconds`

**Comment by albertogeniola** [comment]
Hi @jacekpaszkowski ,

I was able to replicate the bug. The problem occurs when the connection to Meross cloud is temporary lost: when it comes back alive, the component tries to reload all the data for its entities (as their state might have changed) and waits for that. That operation is particularly heavy and the Meross cloud tends to "kick" the component out because of its traffic spike. That causes an exception that makes you experience the issue.

The latest version () should solve this issue. Please update and let me know if that happens again.

**Comment by jacekpaszkowski** [comment]
Hi @albertogeniola,

latest varsion works stable, thank you!
