### ISSUE TITLE
Inconsistent state MSS425E

### ISSUE THREAD

**Issue by hexahis** [albertogeniola/meross-homeassistant#171]
Recently I was facing the usual disconecitions issue on all my devices. With recent updates it seems it is fixed, but now I'm facing this error only in my MSS424E:

2020-11-30 21:40:13 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Server) before accessing its state. Failure to do so may result in inconsistent state.
2020-11-30 21:40:18 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/674975-a694c23055ff7f25b53d2b15aa103156/subscribe", "messageId": "56d724496996b851383aa4608ffb187e", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "27e7453a660b224585285abee42ffcc6", "timestamp": 1606768814, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 2007163922700490819948e1e9257c9c. Timeout was: 5 seconds.
2020-11-30 21:40:18 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.4.1.0rc7
Device info: 
	Name: Server
	UUID: 2007163922700490819948e1e9257c9c
	Type: mss425e
	HW Version: 3.0.0
	FW Version: 3.1.3
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

Integration is unable to determine the proper state of each switch on MSS425E after a reboot and then I'm not able to turn on/off them with hassio

**Comment by albertogeniola** [comment]
Hi, the error is not related to the inconsistent state. Instead, the TimeoutError might be the cause of the inconsistent state of the device on HomeAssistant. In you case, what's the wifi signal strenght of the device?

**Comment by hexahis** [comment]
Hi Alberto,

It's not a wifi issue, the device is really really close to the router. I'm able to manage the device from meross app and I also was able to do it until I updated to 1.0.4-post. Now I'm in 1.0.5 and the issue still happens

**Comment by albertogeniola** [comment]
I see. The app you are using is connected over WiFi or 4g?

**Comment by hexahis** [comment]
I'm able to manage the device trough 4G with the app

**Comment by albertogeniola** [comment]
Ok, then it might be an IP blacklist problem. It looks like Meross cloud does ban specific IPs. For instance, they banned Azure and GitHub workers (that I used for automated testing). You can double check this by using a different connection from HomeAssistant. For instance you could configure your HomeAssistant device to use your smartphone's tethered 4g connection. This is pretty straight forward if you installed HA on a raspberry PI3+/4 or on an Intel NUC or on any system that is WIFI enabled. 

Can you try that?

**Comment by hexahis** [comment]
I hace other meross devices that I can properly manage with hassio
As I said, the issue is only happening with this device after installing 1.0.4 I was able to manage It with prior releases

**Comment by albertogeniola** [comment]
> I hace other meross devices that I can properly manage with hassio
> As I said, the issue is only happening with this device after installing 1.0.4 I was able to manage It with prior releases

have you tried rolling back to 1.0.4 to see if that's still the case?

**Comment by hexahis** [comment]
A rollback to 1.0.3 solves the issue with MSS424E. But then I have the issue related to entities not availables of all devices
