### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by meszimark** [albertogeniola/meross-homeassistant#173]
```
Logger: aiohttp.server
Source: custom_components/meross_cloud/config_flow.py:74
First occurred: 2020. december 1. 14:15:28 (4 occurrences)
Last logged: 16:09:02
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/meross_cloud/config_flow.py", line 49, in async_step_user
    creds = await self._test_authorization(username, password)
  File "/config/custom_components/meross_cloud/config_flow.py", line 74, in _test_authorization
    client = await MerossHttpClient.async_from_user_password(email=username, password=password)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 102, in async_from_user_password
    creds = await cls.async_login(email, password)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 132, in async_login
    response_data = await cls._async_authenticated_post(_LOGIN_URL, params_data=data, mask_params_in_log=True)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 210, in _async_authenticated_post
    raise BadLoginException("Invalid username/Password combination")
meross_iot.model.http.exception.BadLoginException: Invalid username/Password combination
```
Login failed and I get this message. The data is correct.

**Comment by albertogeniola** [comment]
Some users have reported that usage of special characters might be problematic when attempting the login. May I  ask you to temporarily change your account password with one with no special characters and try that again?

**Comment by meszimark** [comment]
In the meantime, I saw that it was still my fault. I didn’t notice on the phone that a letter was missing from my email address. I'm sorry. I managed to log in like this. (I only dealt with the password, I didn't check the email address to see if I registered correctly).

Thanks.

**Comment by albertogeniola** [comment]
Glad you solved it!
