### ISSUE TITLE
Unhandled exception when timing out

### ISSUE THREAD

**Issue by wsw70** [albertogeniola/meross-homeassistant#183]
**Describe the bug**

From time to time, the connection to the MEROSS cloud fails (this is at least my understanding). This generates a big error entry in the HA log because the exception is not handled.

**Your environment**
HomeAssistant version: 2020.12.0
Hassio Version (if applicable): N/A
Hardware environment: HA running in a docker with the `latest` tag

**Logs taken when the issue happened**

Up to the `Traceback` line the messages are in red

```
2020-12-16 19:51:31 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/737703-17ee452578193785302e0807e2d80c93/subscribe", "messageId": "49ab7f373f3e5efc84c39aa16b00128d", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "8e0482f57b95c04415a765e21b75c70f", "timestamp": 1608144687, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 2005281078830290814148e1e91d807b. Timeout was: 5 seconds.
2020-12-16 19:51:31 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.4.1.0rc7
Device info:
        Name: salon multiprise fond
        UUID: 2005281078830290814148e1e91d807b
        Type: mss425f
        HW Version: 3.0.0
        FW Version: 3.1.2
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
```

**Comment by Crissup** [comment]
I think this is the same as Issue #180, I added a few notes about what I'm seeing over there when I have the same problem.

**Comment by albertogeniola** [comment]
Hi @wsw70 ,

thaat is exactly how it is meant to be. Exception should be handled only if there is a way to "recover" from them. When a connection times or the internet connection goes away, then there is little we can do to recover from that.

**Comment by wsw70** [comment]
@albertogeniola 

> thaat is exactly how it is meant to be. Exception should be handled only if there is a way to "recover" from them. When a connection times or the internet connection goes away, then there is little we can do to recover from that.

I do not think so. The exception should be caught and the appropriate error message should be displayed (and the rest aborted). Something like

```
2020-12-16 19:51:31 ERROR (MainThread) [custom_components.meross_cloud.switch] Device "salon multiprise fond" (2005281078830290814148e1e91d807b) timed out.
```

Why the whole traceback? This is useful for a developer or someone who reports a bug, never for an end user.

**Comment by albertogeniola** [comment]
Indeed, this component is not yet considered stable and ready for production, as mentioned by the very first log lines being displayed at boot: full trace stacks are vital for me to debug: end users would be able to simply copy paste errors on GitHub. The other way around would require users to increase the log verbosity level, which is something that the average ha user is not able to do on his own.

**Comment by wsw70** [comment]
Yes this is very much understandable - and by the way your component is fantastic.

What I mean is that once a malfunction is known it should be caught, even if the "recovery" means aborting.

I have a lot of code that relies on `requests` and I embed the call in something like

```
try:
    r = requests.get(url)
    r.raise_for_status()
except Exception as e:
    log.error(f"cannot connect to {url}: {e}")
    # recovery code, up to sys.exit()
```

This way I know that there is a problem (and the exact issue can be reported by a user). This would cover all unexpected cases when the call fails (cannot resolve the URL, timeout, wrong code, whatever, ...)
