### ISSUE TITLE
Exception and Timeout Error for Meross Devices

### ISSUE THREAD

**Issue by kaouk** [albertogeniola/meross-homeassistant#203]
After working flawlessly for months I think an update of HA has caused an issue with the Meross Integration. I'm running the 1.0.6beta but getting the following error in my logs when trying to use my Meross Switches or Garage door:

 Logger: custom_components.meross_cloud.switch
Source: custom_components/meross_cloud/switch.py:57
Integration: Meross Cloud IoT (documentation)
First occurred: 19:58:58 (4 occurrences)
Last logged: 20:01:55

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Garage Lighting UUID: 20051857713104258h1448e1e91c3e8f Type: mss710 HW Version: 3.0.0 FW Version: 3.1.6 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Back Garden Lighting UUID: 20051837173334258h1448e1e91c2ac3 Type: mss710 HW Version: 3.0.0 FW Version: 3.1.6 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 57, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 603, in async_execute_cmd
    return await self.async_execute_cmd(destination_device_uuid=destination_device_uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 603, in async_execute_cmd
    return await self.async_execute_cmd(destination_device_uuid=destination_device_uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

I've tried re-installing the component and it works flawlessly from the Meross app itself, just this integration that has an issue

**Comment by portbusy** [comment]
I am having the same issue with the stable version (v1.0.5) and it affects also my light's brightness control beyond the light's toggle command. I have also tried re-installing the same version but the problem still remains.

**Comment by g40matt** [comment]
Agree, something broke my entire Meross integration in the last few weeks.  I've reinstalled tonight, and initially things connected, but now it's failed.

36 of these timeout errors are in the log:
Timeout occurred while waiting a response for message b

**Comment by k41zen** [comment]
Same issues here. I'm pretty certain I had entities of a switch too as I used to control these plugs through automations turning them off and on. But now my logs are filled with timeout errors for all 3 plugs. 2 of the 3 don't show values for watts either but all seem to be reporting fine in the Merros app:

Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:355 
Integration: Meross Cloud IoT (documentation) 
First occurred: 11:39:00 (34 occurrences) 
Last logged: 11:50:00

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Washing Machine UUID: 20091191306404251h5748e1e9334bcc Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Car Charger UUID: 20091119350676251h5748e1e933542e Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Dishwasher UUID: 20091172652673251h5748e1e9335420 Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 355, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by carltstein** [comment]
I just bought 4 MSS310 wifi plugs. I have installed 1.0.5 and the integration recognized my plugs but am having no luck getting any data and am getting identical timeout errors to others above. 

`Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Dryer UUID: 21020321306564251h6048e1e94aaf84 Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 322, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError`


Additional errors:

`Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:632
First occurred: 12:57:49 PM (8 occurrences)
Last logged: 12:58:29 PM

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1326625-26fe28b2f1d3d6381f438631c8297a64/subscribe", "messageId": "f75e678bd508b67e142bd7367d17a172", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "a54bc14b5b13bd39ed8ec34dffd275d8", "timestamp": 1620010674, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 21020321306564251h6048e1e94aaf84. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1326625-26fe28b2f1d3d6381f438631c8297a64/subscribe", "messageId": "666d7a844bb94433da700745bd3dd98c", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "2651570939458433c45eba4c766bbdf8", "timestamp": 1620010674, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 21020321306564251h6048e1e94aaf84. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1326625-26fe28b2f1d3d6381f438631c8297a64/subscribe", "messageId": "df54e6414c791214c6561227270d0354", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "3088d8775f37a42046076c13cf31d9fd", "timestamp": 1620010679, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 21020321306564251h6048e1e94aaf84. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1326625-26fe28b2f1d3d6381f438631c8297a64/subscribe", "messageId": "3b6314de12fffec7bf534e9ca4c7fa36", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "bf79a8faa9630d2d528312a11afc3f06", "timestamp": 1620010699, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 21020321306564251h6048e1e94aaf84. Timeout was: 5 seconds.
Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1326625-26fe28b2f1d3d6381f438631c8297a64/subscribe", "messageId": "beea3bef9f3e897b5d9693e05023ed3a", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "2577ed1e41aba18d410c1faa63455e30", "timestamp": 1620010704, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 21020321306564251h6048e1e94aaf84. Timeout was: 5 seconds.`
