### ISSUE TITLE
Fan Issue

### ISSUE THREAD

**Issue by robyevolution** [albertogeniola/meross-homeassistant#205]
with the new home assistant update you have to change something about the fan configuration, the component gives me this error

2021-03-04 00:06:15 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform meross_cloud
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 601, in state_attributes
    data[ATTR_PERCENTAGE] = self.percentage
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 463, in percentage
    return self.speed_to_percentage(self.speed)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 547, in speed_to_percentage
    raise NotValidSpeedError(f"The speed {speed} is not a valid speed.")
homeassistant.components.fan.NotValidSpeedError: The speed OFF is not a valid speed.
2021-03-04 00:06:16 ERROR (MainThread) [homeassistant.components.fan] Error while setting up meross_cloud platform for fan
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 208, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 601, in state_attributes
    data[ATTR_PERCENTAGE] = self.percentage
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 463, in percentage
    return self.speed_to_percentage(self.speed)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/fan/__init__.py", line 547, in speed_to_percentage
    raise NotValidSpeedError(f"The speed {speed} is not a valid speed.")
homeassistant.components.fan.NotValidSpeedError: The speed OFF is not a valid speed.

**Comment by Raul-7-7** [comment]
Having similar issue with mss110 (FW 2.1.21). However, my ms310 (FW 1.1.18) is running fine on latest HA (core-2021.3.0)
Source: /usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py:56
Please invoke async_update() for this device before accessing its state. Failure to do so may result in inconsistent state.

Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:541
Uncaught push notification Namespace.CONTROL_TOGGLEX.

**Comment by frapaego** [comment]
Hola.

Yo tenía el mismo problema y lo he solucionado añadiendo la siguiente property al fichero /meross_cloud/fan.py:

@property
    def percentage(self) -> Optional[str]:
        mode = self._device.get_current_mode(channel=self._channel_id)
        if mode is None:
            return 0
        elif mode == SprayMode.CONTINUOUS:
            return 50
        else:
            return 100

Espero que sirva de ayuda.
Saludos.!!!.

**Comment by robyevolution** [comment]
I re-open this discussion because with the new update the integration only shows the light entity of the fan (msxh0)

**Comment by robyevolution** [comment]
with the new update it doesn't work again ..
