### ISSUE TITLE
MSG100 Not working

### ISSUE THREAD

**Issue by mbrihed** [albertogeniola/meross-homeassistant#206]
**Describe the bug**
When I try and open or close the garage door I get Failed to Call Service cover/open...
My entity gets the following name: "cover.front_gate_msg100_main_channel"

It works perfectly from my phone app (Meross App).

**Your environment**
HomeAssistant version: Home Assistant OS 5.12
Hassio Version (if applicable): core-2021.3.2, supervisor-2021.03.4
Hardware environment: Proxmox VM

**Logs taken when the issue happened**

2021-03-07 09:12:36 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1218027-7645483471d28a623769cc381d1a8854/subscribe", "messageId": "56d7a1740b675369038d1c9c9b74c125", "method": "SET", "namespace": "Appliance.GarageDoor.State", "payloadVersion": 1, "sign": "7e78c67395e0858bb86cb68656dc4e4b", "timestamp": 1615108352, "triggerSrc": "Android"}, "payload": {"state": {"channel": 0, "open": 1, "uuid": "2008149559715936100348e1e92b2403"}}}' sent to device uuid 2008149559715936100348e1e92b2403. Timeout was: 5 seconds.
2021-03-07 09:12:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139643523567728] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/cover.py", line 129, in async_open_cover
    await self._device.async_open(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 67, in async_open
    await self._async_operate(state=True, channel=channel, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 81, in _async_operate
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by mbrihed** [comment]
Captured logs again:

this is the core.entity_registry
 
            {                        
                "entity_id": "cover.front_gate_1_msg100_main_channel",
                "config_entry_id": "dc0aa16afef07dddbc680e7416f7997a",
                "device_id": "d9491b041c05f041826240ae7c9bd14d",
                "area_id": "0f5faab3faff401582c3e7db837a6362",
                "unique_id": "cover:#BASE:2008149559715936100348e1e92b2403:0",
                "platform": "meross_cloud",
                "name": null,               
                "icon": null,           
                "disabled_by": null, 
                "capabilities": {},
                "supported_features": 3,
                "device_class": "garage",  
                "unit_of_measurement": null,                          
                "original_name": "Front Gate 1 (msg100) - Main channel",
                "original_icon": null
            },                       


=========================================

Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:632 
First occurred: 11:54:39 AM (1 occurrences) 
Last logged: 11:54:39 AM

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1218027-303762f59cd53947ff9593a9a960c995/subscribe", "messageId": "2840f189b971cdccc4d13c85e9127b21", "method": "SET", "namespace": "Appliance.GarageDoor.State", "payloadVersion": 1, "sign": "90c7165afb6df093405aa4435cc23f05", "timestamp": 1618473275, "triggerSrc": "Android"}, "payload": {"state": {"channel": 0, "open": 1, "uuid": "2008149559715936100348e1e92b2403"}}}' sent to device uuid 2008149559715936100348e1e92b2403. Timeout was: 5 seconds.

===========================================

==========================================

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/meross_cloud/cover.py:129 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:54:39 AM (1 occurrences) 
Last logged: 11:54:39 AM

[139994765056608]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/cover.py", line 129, in async_open_cover
    await self._device.async_open(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 67, in async_open
    await self._async_operate(state=True, channel=channel, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 81, in _async_operate
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

==========================================================

**Comment by mbrihed** [comment]
Has this custom component add-on been end-of-life?

It seems to be very difficult to get help since it seems it is broken and I keep getting errors on calling service when ever I try to open close. The MSG100's gets added to HA but that is all it does.

**Comment by highlandtran** [comment]
> Has this custom component add-on been end-of-life?
> 
> It seems to be very difficult to get help since it seems it is broken and I keep getting errors on calling service when ever I try to open close. The MSG100's gets added to HA but that is all it does.

do you have any update on this mate?

**Comment by mbrihed** [comment]
I have installed the addd-on and it discovers my two MSG100 and can read the status when it is open or closed. I can open and close it through the Meross App. The problem is when I try and open or close the MSG100 from HA I get the failure:
"Failed to call service cover/open"
The failure shows in HA when I try it.

Let me know if there is a specific detail I can share.

**Comment by mbrihed** [comment]
I got nowhere with this and I think the problem has to do with the add-on and how it parses data between the add-on and the service call function in HA. My device name does not have channel 0 in the naming as an example where I have seen others have and when trying to understand the log to me it seems it does not send the right data to the service call. 

I have given up on this add-on and will look at other solutions since I didn't get any help either to try and trouble shoot the issue.

I will probably end up buying new devices that integrates well into HA and stay away from Meross devices. ( I have two MSG100 so a bit disappointing I can't use them in HA) As of now I use the Meross App on my phone and Apple Watch to control them and I use HA to check if they are closed at night so I haven't forgotten to close them. 

My understanding is that the Meross Local Add0n is now available but then you need to reset and reconfigure your MSG's to use MQTT. I could be wrong... To me it is a bit of a hack (work around) and not sure I want to do that and rather get something else that just works.

**Comment by mbrihed** [comment]
Hi! I have tested the MSG100 and both of them now work :-) Thanks a million for fixing this.

**Comment by albertogeniola** [comment]
That's great! Are you using v1.1.3 or v1.1.4?

**Comment by mbrihed** [comment]
it worked with 1.1.2 and now I am on 1.1.4 and works fine.

**Comment by albertogeniola** [comment]
I'm glad to hear that. Closing.

**Comment by Noext** [comment]
Hi

just installed the 1.1.4 version and my msg100 is not working

**Comment by albertogeniola** [comment]
Hi @Noext : is the MSG100 the only device causing errors with your version? Have you uninstalled the component completely, rebooted and re-installed it again ?

**Comment by mbrihed** [comment]
HI!

I did remove it completely and reinstalled fresh and then it worked. I did install 1.1.2 and the it worked. Upgraded to 1.1.4 and still works.
Try re-install the add-on.

**Comment by Noext** [comment]
> Hi @Noext ,
> is the MSG100 the only device causing errors with your version? Have you uninstalled the component completely, rebooted and re-installed it again ?

i have only one MSG100 on my setup, i will try to re install today, but its already a fresh home assistant install

**Comment by Noext** [comment]
still the same issue
i keep seeing "Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu.meross.com:443.Global manager stats (last minute): Issued -> 3, Delayed -> 0, Dropped -> 0"

On the log file 

what is mqtt-eu.meross.com ? its a local address on my network or a remote address to meross server ? because if its remote it seems down since 2 days
