### ISSUE TITLE
mss310 Timeout no on off switch

### ISSUE THREAD

**Issue by Selmaks** [albertogeniola/meross-homeassistant#219]
**Describe the bug**

**Your environment**
HomeAssistant version: -- core-2021.3.4 --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- Debian GNU/Linux 10  --

**Logs taken when the issue happened**
```
Component version: 0.4.1.0rc7
Device info: 
	Name: Switch
	UUID: 20111295006867251h5948e1e93ac688
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.16
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 357, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError


Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:322
First occurred: 1:42:01 PM (1 occurrences)
Last logged: 1:42:01 PM

Device Switch (20111295006867251h5948e1e93ac688) is online, but timeout occurred when fetching its abilities.
```

**Comment by userMak** [comment]
same problem here. Sadly the integration looks abandoned.

**Comment by Selmaks** [comment]
Sadly it's looking that way unfortunately.

**Comment by mbrihed** [comment]
It seems I get the same error message in the log when trying to open or close the garage door (MSG100).

==========================================

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/meross_cloud/cover.py:129 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:54:39 AM (1 occurrences) 
Last logged: 11:54:39 AM

[139994765056608]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/cover.py", line 129, in async_open_cover
    await self._device.async_open(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 67, in async_open
    await self._async_operate(state=True, channel=channel, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/garage.py", line 81, in _async_operate
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

==========================================================

**Comment by carltstein** [comment]
No love for me either for MSS310 plug integration. It recognized the devices but no ability to toggle plugs or see any power usage data at all. The logs show various timeout errors similar to the above.

`Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:322
Integration: Meross Cloud IoT (documentation)
First occurred: 12:57:59 PM (114 occurrences)
Last logged: 1:54:29 PM

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Dryer UUID: 21020321306564251h6048e1e94aaf84 Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 322, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError`
