### ISSUE TITLE
Problem on new Meross added to cloud / HA

### ISSUE THREAD

**Issue by Cippo2019** [albertogeniola/meross-homeassistant#220]
Hello
first of all sorry for my bad English !

I have add a meross plug and always was perfect
After that I delete plug for cloud and add it again (with another wifi)
Device is again in cloud app (android) and it work perfeclty.
Into app I have also other meross devices and all work perfectrly without error in App e/o HA

log below..

any idea how to solve ?

thanks a lot
Tiziano

HomeAssistant version: --core-2021.3.4
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: - vmware-

LOGS

For this one (deleted and added) under Home Assistant I see sometimes (without regular timing) this error

2021-04-05 18:43:05 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Doppia (mss310) - power sensor (W, 0): 0.0> as it was already added to registry once.
2021-04-05 18:43:05 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Doppia (mss310) - power sensor (A, 0): 0.0> as it was already added to registry once.
2021-04-05 18:43:05 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Doppia (mss310) - power sensor (V, 0): 229.3> as it was already added to registry once.
2021-04-05 18:43:06 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Singola (mss310) - power sensor (W, 0): 0.0> as it was already added to registry once.
2021-04-05 18:43:06 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Singola (mss310) - power sensor (A, 0): 0.0> as it was already added to registry once.
2021-04-05 18:43:06 WARNING (MainThread) [custom_components.meross_cloud.sensor] Skipping device <Entity Batteria_Singola (mss310) - power sensor (V, 0): 231.2> as it was already added to registry once.
2021-04-05 18:43:10 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/142f30c539/subscribe", "messageId": "17e1537d654bbf", "method": "GET", "namespace": "Appliance.Control.Electricity", "payloadVersion": 1, "sign": "f536089f6d", "timestamp": 1617640985, "triggerSrc": "Android"}, "payload": {"channel": 0}}' sent to device uuid 19******97da. Timeout was: 5 seconds.
2021-04-05 18:43:10 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
Component version: 0.4.1.0rc7
Device info:
Name: Batteria_Doppia
UUID: 17da
Type: mss310
HW Version: 2.0.0
FW Version: 2.1.16
Error Message: "An exception occurred"
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
return await asyncio.wait_for(future, timeout, loop=self._loop)
File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/meross_cloud/sensor.py", line 288, in async_update
await self._device.async_get_instant_metrics(channel=self._channel_id)
File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
result = await self._execute_command(method="GET",
File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
response = await self._async_send_and_wait_ack(future=fut,
File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2021-04-05 18:43:10 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/142f30c539/subscribe", "messageId": "e67047a6b1500", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "78e3f5", "timestamp": 1617640985, "triggerSrc": "Android"}, "payload": {}}' sent to device uuid 1997da.
Timeout was: 5 seconds.
2021-04-05 18:43:10 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.

**Comment by Cippo2019** [comment]
my fault
