### ISSUE TITLE
newly added MSS425F not working in HA

### ISSUE THREAD

**Issue by aaamoeder** [albertogeniola/meross-homeassistant#226]
just bought and paired a meross MSS425F surge protector-plug combo
Added it in the meross app (android) without issues and working fine

Added this integration to HA and it was able to find the plugs fine but they are not responding to switch on/off request and are not reporting current state.

Error log gives me the following:
`2021-05-03 19:33:42 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/subscribe", "messageId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "method": "SET", "namespace": "Appliance.Control.ToggleX", "payloadVersion": 1, "sign": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "timestamp": 1620063217, "triggerSrc": "Android"}, "payload": {"togglex": {"onoff": 1, "channel": 4}}}' sent to device uuid 2006287138789890816648e1e9212204. Timeout was: 5 seconds.
2021-05-03 19:33:42 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx): entity_id=['switch.stopcontacten_veranda_mss425f_switch_4']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/switch.py", line 107, in async_turn_on
    await self._device.async_turn_on(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/toggle.py", line 106, in async_turn_on
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2021-05-03 19:33:47 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/subscribe", "messageId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "method": "SET", "namespace": "Appliance.Control.ToggleX", "payloadVersion": 1, "sign": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "timestamp": 1620063222, "triggerSrc": "Android"}, "payload": {"togglex": {"onoff": 1, "channel": 5}}}' sent to device uuid xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Timeout was: 5 seconds.
2021-05-03 19:33:47 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:c755d9b933d9e3cfa16c0ce88ffa3808): entity_id=['switch.stopcontacten_veranda_mss425f_usb']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/switch.py", line 107, in async_turn_on
    await self._device.async_turn_on(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/toggle.py", line 106, in async_turn_on
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError`

**Comment by PachangaDad** [comment]
I recently purchased and integrated my unit with the phone app, I was first concerned because of all the HomeKit referencing. When I began the processed I was notified it was now added successfully in the android app and it asked me if I wanted HomeKit to control it. I declined this prompt and directed it to be controlled by Meross /eHomeLife app to continue control of it. Not sure if this helps. I was even able to rename the device in the app and it synchronized into HA after a reboot of HA.
Best of luck, I had no errors.

**Comment by Odinlistening** [comment]
Firstly, thanks for all the incredible and hard work on this integration - so the following is not a complaint at all.

I too have a MSS425F which until recently worked without problem with your Integration. This now fails. Not detected.

All other Meross devices detected and working perfectly. I have reinstalled a number of times, stripped out previous references etc. 

Not a huge problem for me - but it would be great if a solution was found. Just a heads-up really. I realise how complex this is.

Thanks again for the hard work.

**Comment by albertogeniola** [comment]
Hi! Which version of the integration are you using? Have you tested v1.1.2?
