### ISSUE TITLE
Meross integration stop working after update

### ISSUE THREAD

**Issue by galamarco** [albertogeniola/meross-homeassistant#228]
**as [reported 6 months ago](https://github.com/albertogeniola/meross-homeassistant/issues/184), updating HomeAssistant to the latest version Meross integration stop working**

With this version working well
- Home Assistant 0.117.6
- OS 5.8
- Meross 1.0.3

With this version stop working
- Home Assistant 2021.5.0
- OS 5.13
- Meross 1.0.5

In log i found:
```The current API rate exceeds the
 overquota limit (1000.000000 %). The call will be dropped.
8:48:05 – (ERRORE) /usr/local/lib/python3.8/site-packages/meross_iot/manager.py - il messaggio si è verificato per la prima volta alle 7:41:04 e compare 312 volte
```
```
This error originated from a custom integration.
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:140
Integration: Meross Cloud IoT
First occurred: 7:41:04 (52 occurrences)
Last logged: 8:48:04

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 140, in async_setup_entry
    await manager.async_device_discovery()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 262, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 316, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(destination_device_uuid=device_info.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 609, in async_execute_cmd
    raise RateLimitExceeded()
meross_iot.model.exception.RateLimitExceeded
```

```
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:54
Integration: Meross Cloud IoT
First occurred: 7:41:03 (52 occurrences)
Last logged: 8:48:04

=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level library version: 0.4.1.0rc7 ------------------------------- This custom component is under development and not yet ready for production use. In case of errors/misbehave, please report it here: https://github.com/albertogeniola/meross-homeassistant/issues If you like this extension and you want to support it, please consider donating. ------------------------------- List of devices reported by HTTP API: - ciabatta cose (mss425f) - OnlineStatus.ONLINE - Tapparella fornello (mrs100) - OnlineStatus.ONLINE - Tapparella cucina (mrs100) - OnlineStatus.ONLINE - Ciabatta ospiti (mss425e) - OnlineStatus.ONLINE - Esterna balcone piccolo (mss620) - OnlineStatus.ONLINE - Esterna balcone grande (mss620) - OnlineStatus.ONLINE - Tapparella salotto (mrs100) - OnlineStatus.ONLINE - Tapparella camera da letto (mrs100) - OnlineStatus.ONLINE - ciabatta tv (mss425f) - OnlineStatus.ONLINE - Specchio bagno (mss710) - OnlineStatus.ONLINE - misuratore fornelli (mss310h) - OnlineStatus.ONLINE - stireria (mss310) - OnlineStatus.OFFLINE - misuratore smartphone (mss310) - OnlineStatus.ONLINE - Misuratore computer (mss310) - OnlineStatus.ONLINE - palestra (mss310h) - OnlineStatus.ONLINE - misuratore cucina (mss310) - OnlineStatus.ONLINE - ciabatta cucina (mss425f) - OnlineStatus.ONLINE - misuratore tv (mss310) - OnlineStatus.ONLINE - lavatrice (mss310) - OnlineStatus.ONLINE - aria (mss310h) - OnlineStatus.ONLINE - boiler (mss310h) - OnlineStatus.ONLINE - ciabatta PC corridoio (mss425f) - OnlineStatus.ONLINE - Termocoperta Marco (mss310h) - OnlineStatus.ONLINE - Termocoperta Aldo (mss310h) - OnlineStatus.ONLINE - Misuratore cucina 2 (mss310r) - OnlineStatus.ONLINE - Misuratore bagno (mss310r) - OnlineStatus.ONLINE - Ciabatta corridoio (mss425e) - OnlineStatus.ONLINE - ciabatta computer (mss425e) - OnlineStatus.ONLINE - Aroma (msxh0) - OnlineStatus.OFFLINE
```

```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:541
First occurred: 8:29:01 (157 occurrences)
Last logged: 8:29:21

Uncaught push notification Namespace.CONTROL_TOGGLEX. Raw data: {"togglex": {"onoff": 1, "lmTime": 1620282541, "channel": 5}}
Uncaught push notification Namespace.CONTROL_TOGGLEX. Raw data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 1}}
Uncaught push notification Namespace.CONTROL_TOGGLEX. Raw data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 2}}
Uncaught push notification Namespace.CONTROL_TOGGLEX. Raw data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 3}}
Uncaught push notification Namespace.CONTROL_TOGGLEX. Raw data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 4}}
```
```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:499
First occurred: 8:29:01 (157 occurrences)
Last logged: 8:29:21

Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2005280256576090814148e1e91d7d82
Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 1810220951285029085334298f16f43a
```
```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:483
First occurred: 8:29:01 (157 occurrences)
Last logged: 8:29:21

Received a push notification (Namespace.CONTROL_TOGGLEX, raw_data: {"togglex": {"onoff": 1, "lmTime": 1620282541, "channel": 5}}) for device(s) (2005280256576090814148e1e91d7d82) that are not available in the local registry. Trigger a discovery to intercept those events.
Received a push notification (Namespace.CONTROL_TOGGLEX, raw_data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 1}}) for device(s) (1810220951285029085334298f16f43a) that are not available in the local registry. Trigger a discovery to intercept those events.
Received a push notification (Namespace.CONTROL_TOGGLEX, raw_data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 2}}) for device(s) (1810220951285029085334298f16f43a) that are not available in the local registry. Trigger a discovery to intercept those events.
Received a push notification (Namespace.CONTROL_TOGGLEX, raw_data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 3}}) for device(s) (1810220951285029085334298f16f43a) that are not available in the local registry. Trigger a discovery to intercept those events.
Received a push notification (Namespace.CONTROL_TOGGLEX, raw_data: {"togglex": {"onoff": 1, "lmTime": 1620282558, "channel": 4}}) for device(s) (1810220951285029085334298f16f43a) that are not available in the local registry. Trigger a discovery to intercept those events.
```
```
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:466
First occurred: 8:24:59 (104 occurrences)
Last logged: 8:25:34

Push notification parsing failed. That message won't be dispatched.
```
```
Logger: meross_iot.model.enums
Source: /usr/local/lib/python3.8/site-packages/meross_iot/model/enums.py:98
First occurred: 8:24:59 (104 occurrences)
Last logged: 8:25:34

Namespace Appliance.RollerShutter.State is not currently handled/recognized.
Namespace Appliance.RollerShutter.Position is not currently handled/recognized.
```

After 6 months I think it is urgent to solve this problem.

Best regards
Marco

**Comment by tarheelz** [comment]
Your assessment of urgency may not match the volunteer author's.

Possible Solution:  Delete the integration and all references to Meross devices, including all entities or devices.  Clear out everything (including Lovelace cards).  The reinstall the latest version.

The current version is notorious for become unavailable after a time but there are workarounds (e.g. rebooting Home Assistant each time).

**Comment by Cippo2019** [comment]
> Your assessment of urgency may not match the volunteer author's.
> 
> Possible Solution: Delete the integration and all references to Meross devices, including all entities or devices. Clear out everything (including Lovelace cards). The reinstall the latest version.
> 
> The current version is notorious for become unavailable after a time but there are workarounds (e.g. rebooting Home Assistant each time).

Hi Tarheelz

first of all sorry for my bad English. But which is the last version of Meross integration coming from Alberto ? 
isnt't it 0.4.1.0rc7   ?

wbr
Tiziano

**Comment by CTJohnK** [comment]
Perhaps this part of the error is a clue, "meross_iot.model.exception.RateLimitExceeded".  Any chance you are excessively hitting the Meross servers with Automations?

**Comment by albertogeniola** [comment]
Hi,
@CTJohnK definetely spotted the issue: your integration is hitting high rate limits. 
However, last v1.1.2 version of the custom component allows rate limiting configuration. Please update it and configure rate limits accordingly.
