### ISSUE TITLE
New MSG100 is recognized as online but timeout occurred when fetching its abilities

### ISSUE THREAD

**Issue by DeadDjembe** [albertogeniola/meross-homeassistant#230]
**Describe the bug**
Setting up a new garage door opener MSG100.  HA can see the door opener but is unable to get the state or communicate with it.  Gives an async_update() error

**Your environment**
HomeAssistant version:  2021.5.1
Hassio Version (if applicable): core-2021.5.1
Hardware environment: VM on UNRAID

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Logger: meross_iot.manager**
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:332
First occurred: 11:11:31 AM (1 occurrences)
Last logged: 11:11:31 AM

Device Garage Door (2011195189736636100948e1e93ce6fb) was built statically via known types, because we failed to retrieve updated abilities for the given device.

**1. Logger: meross_iot.manager**
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:322
First occurred: 11:11:31 AM (1 occurrences)
Last logged: 11:11:31 AM

Device Garage Door (2011195189736636100948e1e93ce6fb) is online, but timeout occurred when fetching its abilities.

**2. This error originated from a custom integration.**

Logger: custom_components.meross_cloud.cover
Source: custom_components/meross_cloud/cover.py:52
Integration: Meross Cloud IoT
First occurred: 11:11:36 AM (1 occurrences)
Last logged: 11:11:36 AM

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Garage Door UUID: 2011195189736636100948e1e93ce6fb Type: msg100 HW Version: 3.5.0 FW Version: 3.1.15 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/cover.py", line 52, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**3. This error originated from a custom integration.**

Logger: custom_components.meross_cloud.cover
Source: custom_components/meross_cloud/cover.py:52
Integration: Meross Cloud IoT
First occurred: 11:11:36 AM (1 occurrences)
Last logged: 11:11:36 AM

Error occurred. ------------------------------------- Component version: 0.4.1.0rc7 Device info: Name: Garage Door UUID: 2011195189736636100948e1e93ce6fb Type: msg100 HW Version: 3.5.0 FW Version: 3.1.15 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/cover.py", line 52, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/system.py", line 21, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by albertogeniola** [comment]
This should be fixed with the latest version of the low-level meross_iot library . Can you test version 1.1.2 and let us know if the problem still occurs?
