### ISSUE TITLE
One switch is consistently logging error

### ISSUE THREAD

**Issue by silviudc** [albertogeniola/meross-homeassistant#232]
**Describe the bug**
I have added a new smart plug to my HA instance and this one keeps throwing errors whenever I toggle it on or off but it does actually succeed. 
Possibly due to core-2021.5.2 update as I do not remember seeing this previously. 

**Your environment**
HomeAssistant version: core-2021.5.2
Hassio Version (if applicable): core-2021.5.2
Hardware environment: Rpi4 with HA OS

**Logs taken when the issue happened**
```
Component version: 0.4.1.0rc7
Device info: 
	Name: EV Charger
	UUID: 19010860319316251a1334298f1479ea
	Type: mss310
	HW Version: 2.0.0
	FW Version: 2.1.14
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 288, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 603, in async_execute_cmd
    return await self.async_execute_cmd(destination_device_uuid=destination_device_uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 603, in async_execute_cmd
    return await self.async_execute_cmd(destination_device_uuid=destination_device_uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2021-05-11 10:47:36 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/63513-45fdeb09c148480e14ad64d2c0ea8e64/subscribe", "messageId": "fb477afa4deacc8968d299baf8fa092a", "method": "SET", "namespace": "Appliance.Control.ToggleX", "payloadVersion": 1, "sign": "f5346f0b3cd46e73a4d9e1805d99dded", "timestamp": 1620726452, "triggerSrc": "Android"}, "payload": {"togglex": {"onoff": 0, "channel": 0}}}' sent to device uuid 19010860319316251a1334298f1479ea. Timeout was: 5 seconds.
2021-05-11 10:47:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547501455104] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/switch.py", line 104, in async_turn_off
    await self._device.async_turn_off(channel=self._channel_id)
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/mixins/toggle.py", line 88, in async_turn_off
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError
2021-05-11 10:47:36 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (EV Charger) before accessing its state. Failure to do so may result in inconsistent state.
```

**Comment by ThomYoung** [comment]
I think I have the same issue.

This error originated from a custom integration.

Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:288
Integration: Meross Cloud IoT
First occurred: 8:54:52 AM (2 occurrences)
Last logged: 8:55:37 AM

Error occurred. ------------------------------------- Component version: 0.4.1.1rc1 Device info: Name: Toaster Plug UUID: 20091168279784251h5748e1e9335df0 Type: mss310 HW Version: 2.0.0 FW Version: 2.1.15 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 288, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/electricity.py", line 38, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by albertogeniola** [comment]
Hi,
can you test version v1.1.0?
