### ISSUE TITLE
"Unknown error occurred" when trying to login after initial install.

### ISSUE THREAD

**Issue by OrangeLoon** [albertogeniola/meross-homeassistant#237]
After setting up the garage door opener on my iPhone, installed and configured the iPhone software, and installed the Meross Cloud IoT, when I go to perform the integration I fill in my Fill in your "Meross login information" the same username/password (verified twice) I used on the iPhone software, I get "Unknown error occurred" which the logs shows to be:

"meross_iot.model.http.exception.BadLoginException: Invalid username/Password combination"

**Your environment**
HomeAssistant version: -- PHome Assistant 2021.5.5 --
Hassio Version (if applicable): -- N/A --
Hardware/Software environment: -- Lamota opener, with eWiseHome (which comes from meross.com)  --

**Logs taken when the issue happened**
log shows: 
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 199, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 257, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/meross_cloud/config_flow.py", line 49, in async_step_user
creds = await self._test_authorization(username, password)
File "/config/custom_components/meross_cloud/config_flow.py", line 74, in _test_authorization
client = await MerossHttpClient.async_from_user_password(email=username, password=password)
File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 102, in async_from_user_password
creds = await cls.async_login(email, password)
File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 132, in async_login
response_data = await cls._async_authenticated_post(_LOGIN_URL, params_data=data, mask_params_in_log=True)
File "/usr/local/lib/python3.8/site-packages/meross_iot/http_api.py", line 210, in _async_authenticated_post
raise BadLoginException("Invalid username/Password combination")
meross_iot.model.http.exception.BadLoginException: Invalid username/Password combination

**Comment by OrangeLoon** [comment]
OK - same device, same model, same hardware provider (Meross), different company.  Seems Meross and Lamota have different services.
