### ISSUE TITLE
Not working on latest Hassio on raspberry-pi3

### ISSUE THREAD

**Issue by salvoc81** [albertogeniola/meross-homeassistant#24]
Hello,
I have followed the guide on the readme but cannot get it work.

I am using a mms310 smart plug (hardware 1.0.0, firmware 1.1.18)

Following is the log from home-assistant:
ModuleNotFoundError: No module named 'meross_iot'
2019-11-12 20:57:33 ERROR (MainThread) [homeassistant.components.hassio] Component error: meross_cloud - Integration 'meross_cloud' not found.
2019-11-12 20:57:38 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-11-12 20:57:38 WARNING (MainThread) [asyncio] socket.send() raised exception.
2019-11-12 20:59:46 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.meross_cloud. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/__init__.py", line 11, in <module>
    from meross_iot.api import UnauthorizedException
ModuleNotFoundError: No module named 'meross_iot'
2019-11-12 20:59:46 ERROR (MainThread) [homeassistant.components.hassio] Component error: meross_cloud - Integration 'meross_cloud' not found.

Thanks a lot in advance.

**Comment by albertogeniola** [comment]
Hi Salvo,

the error complains about meross_iot library not being found on the system. You'd probably need to reinstall the component again so that the library is pulled.

Would you mind retrying and let us know?

**Comment by salvoc81** [comment]
Hello Alberto. The library was missing and now the switches are now working.
I am just not sure on how to visualize the energy consumption.
Do I need to add anything specific in the config file or lovelace?

**Comment by salvoc81** [comment]
Never mind, I found it :)
Thanks a lot, looking forward to see it integrated in home assistant.

**Comment by albertogeniola** [comment]
Glad you solved it!
