### ISSUE TITLE
Tons of errors after integration in Home Assistant

### ISSUE THREAD

**Issue by mfabiani53** [albertogeniola/meross-homeassistant#27]
I just installed the MSS310R smart plug into HA and got these errors that make the log file grows speedly.
```
2019-12-06 13:03:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:03:47 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:04:49 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:04:49 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 370, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 64, in turn_off
    self._device.turn_off_channel(self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 154, in turn_off_channel
    return self._channel_control_impl(c, 0, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 35, in _channel_control_impl
    return self._togglex(channel, status, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 29, in _togglex
    return self.execute_command("SET", TOGGLEX, payload, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:07:55 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:08:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2019-12-06 13:09:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.presa_meross fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 40, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 136, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```

The switch and the sensor created seems to work well as i can turn on/off the switch and see the power usage. Why those errors?
My configuration is:

meross_cloud:
  username: !secret meross_username
  password: !secret meross_password
And installed the custom component via HACS.

EDIT: When the plug is off i noticed also this error:

```
2019-12-06 13:19:44 ERROR (Thread-2) [meross.power_plugs] Unknown/Unsupported namespace/command: Appliance.Control.TimerX
```
After a restart i got this:
```
2019-12-06 16:04:32 ERROR (MainThread) [meross.manager] An unhandled error occurred while invoking callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 174, in _fire_event
    c(eventobj)
  File "/config/custom_components/meross_cloud/__init__.py", line 70, in event_handler
    enroll_device(self._hass, self._conf, evt.device)
  File "/config/custom_components/meross_cloud/__init__.py", line 43, in enroll_device
    if device.online and device.supports_consumption_reading():
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 162, in supports_consumption_reading
    return CONSUMPTIONX in self.get_abilities()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 134, in get_abilities
    self._abilities = self.execute_command("GET", ABILITY, {})['ability']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 300, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
```
And the sensor.presa_meross disappeared...

**Comment by xavipolo** [comment]
It seems that when it try to access the Meross website it takes more than 10 seconds to respond and get timeout error.

The integration with Home Assistant is based on the Meross IoT library (https://github.com/albertogeniola/MerossIot), and I think the MSS310R is not supported.

Put a message in MerossIot about MSS310R.

**Comment by xavipolo** [comment]
The integration with Home Assistant is based on the Meross IoT library (https://github.com/albertogeniola/MerossIot), and I think the MSS310R is not supported.

Write a message in MerossIot about MSS310R.

There seems to be an error sending a mqtt message to the broker.
Does the log show something like "Client connected to MQTT broker and subscribed to relevant topics"? to see if MQTT has started well.

**Comment by mfabiani53** [comment]
There is no error like that in my logfile, but i am having a big doubt.
Do i need to configure mqtt to use this library with meross?
I just followed the guide about the custom component and nothing more.....
Sorry if it's a stupid question, but i am really a newbie about these things....
More, how to send a message in Merossslot?

**Comment by xavipolo** [comment]
> There is no error like that in my logfile, but i am having a big doubt.
> Do i need to configure mqtt to use this library with meross?
> I just followed the guide about the custom component and nothing more.....
> Sorry if it's a stupid question, but i am really a newbie about these things....
> More, how to send a message in Merossslot?

There is no need to configure mqtt.

I'm using the Home Assistant installation from Python, and there are two things to install, merossiot and meross-homeassistant.

The message I was telling you indicates that the mqtt has started well. If it doesn't appear, something is wrong.

Try opening a new issue in merossiot, with the error.

**Comment by albertogeniola** [comment]
Hi,

from the logs you provided, it seems there was an network issue preventing the communication between the plug and the library. Are you sure both the MSS310R and the homeassistant device were connected to the internet?

**Comment by albertogeniola** [comment]
Closing for inactivity/stale. Feel free to reopen if needed.
