### ISSUE TITLE
Failed to called service switch/turn_on.

### ISSUE THREAD

**Issue by thibautd88** [albertogeniola/meross-homeassistant#271]
**Describe the bug**
I was perfectly working since yesterday.
But, right now, I just succeed to get the status of the plug. 
I can not call service like turn on_on or turn_off :-(
I restarted Home assistant several times.

If you have any idea, it will be appreciated ;-) 

**Your environment**
HomeAssistant version: -- core-2021.9.4 
Hassio Version (if applicable): -- Home Assistant OS 6.3 --
Hardware environment: -- raspberry 3B+ --

**Logs taken when the issue happened**

--- PASTE LOGS HERE ---
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/meross_cloud/switch.py:108
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:14:04 (9 occurrences)
Last logged: 21:47:34

[547385956336]
[547518048288]
[547503465760]
[547371996832]

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/switch.py", line 108, in async_turn_on
    await self._device.async_turn_on(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/toggle.py", line 106, in async_turn_on
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

**Comment by mlazzarotto** [comment]
I've been having the same issue since 3/4 days ago.
I have the same error as @thibautd88 and also the following
`Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1159087-3512a18a5cf5c6175d00f250d5bd09ba/subscribe", "messageId": "58c14f652ba224579b12a6a31bb43415", "method": "SET", "namespace": "Appliance.Control.ToggleX", "payloadVersion": 1, "sign": "18429deefcc231c7ea505c0845307c10", "timestamp": 1631181416}, "payload": {"togglex": {"onoff": 1, "channel": 3}}}' sent to device uuid 2007168255736390820048e1e92594d7. Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.Global manager stats (last minute): Issued -> 1, Delayed -> 0, Dropped -> 0`

**Comment by myrulezzz** [comment]
Same issue here with merros switch

**Comment by pskillen** [comment]
I had the same issue the past 24h. Resolved by updating to latest Meross plugin (`v1.1.4`)

**Comment by thibautd88** [comment]
So, I solved my problem by switching to the Meross LAN integtation : https://github.com/krahabb/meross_lan

**Comment by myrulezzz** [comment]
I have solved as well by upgrading home assistant.it seems to be an issue
as well withe meross app as one of my wifi switches unpaired from meross
app and i couldn’t repair it.after updating the meross app i was able to
repair it and after upgraded home assistant i was able to add it there as
well

**Comment by thibautd88** [comment]
No real improvement between both integrations. Just the second one is working in my place :p
