### ISSUE TITLE
https://iot.meross.com Meross Cloud IoT Nuovo tentativo di configurazione: None

### ISSUE THREAD

**Issue by LoRacolo** [albertogeniola/meross-homeassistant#280]
**Describe the bug**
Impossibile utilizzare l'integrazione dopo il passaggio a HA Core 2021.10.6

**Your environment**
HomeAssistant version: HA Core 2021.10.6 / Python 3.10
Hassio Version (if applicable): --
Hardware environment: Raspberry PI4 - Raspbian 5.10.63-v7l+

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:252
Integration: Meross Cloud IoT
First occurred: 16:32:58 (5 occurrences)
Last logged: 16:34:15

Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/__init__.py", line 252, in async_setup_entry
    await manager.async_device_discovery()
  File "/srv/homeassistant/lib/python3.10/site-packages/meross_iot/manager.py", line 374, in async_device_discovery
    enrolled_devices = await asyncio.gather(*tasks, loop=self._loop)
TypeError: gather() got an unexpected keyword argument 'loop'

-------------------------------------------------------------------

Logger: homeassistant
Source: /srv/homeassistant/lib/python3.10/site-packages/homeassistant/runner.py:90
First occurred: 16:32:58 (70 occurrences)
Last logged: 16:34:38

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/meross_iot/manager.py", line 456, in _async_enroll_new_http_dev
    res_abilities = await self.async_execute_cmd(
  File "/srv/homeassistant/lib/python3.10/site-packages/meross_iot/manager.py", line 837, in async_execute_cmd
    client = await self._async_get_create_mqtt_client(domain=mqtt_hostname, port=mqtt_port)
  File "/srv/homeassistant/lib/python3.10/site-packages/meross_iot/manager.py", line 162, in _async_get_create_mqtt_client
    conn_evt = asyncio.Event(loop=self._loop)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 167, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary

**Comment by EdoZullo** [comment]
Hi, i have the same issue! Did you solved?
