### ISSUE TITLE
Timeout errors and temperatures not set from HA

### ISSUE THREAD

**Issue by thunder2k** [albertogeniola/meross-homeassistant#282]
**Describe the bug**
Timeout errors and temperatures not set from HA

**Your environment**
HomeAssistant version: core-2021.10.7
Hassio Version (if applicable): N/A
Hardware environment: RaspberryPi 3b+

**Logs taken when the issue happened**
```
Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:296
Integration: Meross Cloud IoT
First occurred: November 2, 2021, 4:07:45 PM (1813 occurrences)
Last logged: 9:53:10 AM

Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Baby Room UUID: 2010090697747326280748e1e9353f69 Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Living Room UUID: 2010090697747326280748e1e9353f69 Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Bedroom UUID: 2010090697747326280748e1e9353f69 Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Living Room 2 UUID: 2010090697747326280748e1e9353f69 Type: mts100v3 HW Version: unknown FW Version: unknown Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 919, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 296, in async_update
    await self._device.async_get_temperature()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/known/subdevice.py", line 235, in async_get_temperature
    res = await self._hub._execute_command(method="GET", namespace=Namespace.HUB_MTS100_TEMPERATURE,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 934, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
```

**Comment by WarC0zes** [comment]
Same problem, since today.

core-2021.11.0b5
supervisor-2021.10.8
Home Assistant OS 6.6

`Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Chauffage salle de bain UUID: 2004231560296225189848e1e91ab790 Type: mss210 HW Version: 2.0.0 FW Version: 2.2.2 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 919, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 53, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 934, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError`

`Logger: meross_iot.manager
Source: /usr/local/lib/python3.9/site-packages/meross_iot/manager.py:926
First occurred: 12:42:14 (1 occurrences)
Last logged: 12:42:14

Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1130872-09b5cab72e21502ce93786f0972b76d5/subscribe", "messageId": "79a4327bbb339e3e510755937175a14b", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "9f9317248bff0741d8a786b428f1d936", "timestamp": 1635939725}, "payload": {}}' sent to device uuid 2004231560296225189848e1e91ab790. Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.Global manager stats (last minute): Issued -> 1, Delayed -> 0, Dropped -> 0`

**Comment by WarC0zes** [comment]
it's back to normal, in my opinion a problem with the cloud meross.

**Comment by Gobolin80** [comment]
Hi,
same problem for me.
I saw this errore few days ago for the first time and now it's a constant error.
