### ISSUE TITLE
Home assistant update 2021.11.4

### ISSUE THREAD

**Issue by robertolamm** [albertogeniola/meross-homeassistant#286]
I am not sure this is a common issue:
Somebody has installed the release 2021.11.4 ?

I got problems with the Meross devices: during the boot seems that not all the devices are recognized as entity and I have a lot of errors.

After a downgrade to the HA 2021.10.6 the integration work well. When I switch back to the new one 2021.11.6 the problem appears again. In some rare circumstances the boot is good and the system work, but at the new boot of HA the problem appears again.

HomeAssistant version: 
2021.11.4
Dockers under Windows10

I am the only one?
Thx

**Comment by patrick-blom** [comment]
I had the same problem after the update today. 

HomeAssistant version:
2021.11.4
Hassio on the HomeAssistant Blue

A downgrade to 2021.11.1 solves the problem for me.
 
Will try to setup a test instance to get some detailed logs.

Cheers Patrick

**Comment by patrick-blom** [comment]
Today I fired up a brand new HA VM with the official vdi image and installed the latest version of meross-homeassistant using hacs. It not possible to control the devices. I was able to take a screen shot and to grab the logs from the core. Looks like something ssl related.

#### Screenshot
![error](https://user-images.githubusercontent.com/4736591/142478419-b1de8627-9700-4616-9d78-418730a3b202.png)


#### Log entry
```  result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 915, in _async_send_and_wait_ack
    message_info = client.publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)
2021-11-18 19:43:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.deko_lampe_mss310_power_sensor_v_0 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/meross_cloud/sensor.py", line 401, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/electricity.py", line 43, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 915, in _async_send_and_wait_ack
    message_info = client.publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)
2021-11-18 19:43:46 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140446010174384] EOF occurred in violation of protocol (_ssl.c:2483)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/switch.py", line 103, in async_turn_on
    await self._device.async_turn_on(channel=self._channel_id, skip_rate_limits=True)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/toggle.py", line 107, in async_turn_on
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 915, in _async_send_and_wait_ack
    message_info = client.publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)
```


@albertogeniola If you need further information or logs, feel free to ping me.

Cheers Patrick

**Comment by Raul-7-7** [comment]
Having same issue as mentioned.

**Comment by Raul-7-7** [comment]
My issue got resolved on its own! all working now :)

**Comment by patrick-blom** [comment]
Can confirm it @Raul-7-7 
On my test instance the switches are working again. 

@robertolamm can you confirm it too?

Cheers Patrick

**Comment by robertolamm** [comment]
Hi Patrick,
unfortunately with the 11.4 version I got the same problem again …..

Have you installed the 11.5 to solve?

Thx
Roberto

**Comment by robertolamm** [comment]
> Can confirm it @Raul-7-7 
> 
> On my test instance the switches are working again. 
> 
> 
> 
> @robertolamm can you confirm it too?
> 
> 
> 
> Cheers Patrick

Hi again @patrick-blom, I tested also the 2021.11.5. Quite better, but seems to be not stable (boot with some entities not initialized and problem with the switch).

The Meross cloud seems became a nightmare, reverted to 2021.10.6 who does not miss a shot :)

Keep in touch
Roberto

**Comment by Raul-7-7** [comment]
@robertolamm I am on core-2021.11.4 and its working without issue. Have you tried removing and then readding the integration?

**Comment by patrick-blom** [comment]
@robertolamm I tried it with 2021.11.4 on a tests instance. Thats seams magical to work now. Have'nt tried 2021.11.5. Will give it a shot. 

If that works as well, it's maybe related to the meross server in a special region 🤔 Don't know, but I already enjoyed several sever outages from the service in the past🙄

Cheers Patrick

**Comment by patrick-blom** [comment]
@robertolamm I updated to version 2021.11.4 and  2021.11.5 today on my blue. 

I had the same error as described before, *but* I could solve it by reloading the integration! After the reload. The control problem seems to be solved. I'm also able to collect sensor information from my plug sockets which can monitor  powerusage etc. I will monitor the new version and share the results.

Cheers Patrick

**Comment by robertolamm** [comment]
Hi Patrick,
I will try to reload the integration in the new version and I will come back to you with the results.

Thx
Roberto

Inviato da iPhone

**Comment by patrick-blom** [comment]
Hi Roberto,
bad news, I tested the new version the whole day and I had several outages. That's super unreliable and frustrating. Some times it works some times not. I don't get whats going on there -.- 

I'm now back on 2021.11.1 which seems to me the stablest version at the moment.

Will do some more research, maybe there is something else we could do or an alternative integration. 

Cheers Patrick

**Comment by Raul-7-7** [comment]
I am not having any issues now,  but you guys can try https://github.com/krahabb/meross_lan see if that works better for you?
@patrick-blom @robertolamm

**Comment by patrick-blom** [comment]
@Raul-7-7 yeah, I also took a look on that integration. Don't know if all my devices are supported, but will give it a try.

Thx :)

**Comment by barcus** [comment]
i disabled API rate limite in the integration then no more "EOF occurred in violation of protocol"

**Comment by patrick-blom** [comment]
@barcus What did you mean by disable the rate limit? By default the rate limits are disabled in my case (checkbox) or did you change the values instead?

But anyways I noticed that, in my case, the values differ between my test and production home assistant. So I will investigate this.

Cheers Patrick

**Comment by barcus** [comment]
yes the checkbox, i enabled it few weeks ago. 
firstly i downgraded core component but i had the same issue (protocol violation) with 2021.10.06. Then i realized that some of my meross devices work and after many reboots the devices unavailable were not the same each time. 
finally i disabled using checkbox the rate limit. no more error then i updated core to 2021.11.05 again !

**Comment by barcus** [comment]
Sorry, maybe i'm wrong. I enabled API rate limite again. Firstly i received some 'rate exceeded' then i increase values and its seems to be working without 'protocol violation' ATM. Let's see i next hours !

**Comment by robertolamm** [comment]
Dear @barcus and @patrick-blom, I think the problem is that in the new version has been changed somethings that change the calls to the Meross Iot site (https://iot.meross.com). Seems also the HA boot is much more quick than the previous. My suspect is that the Meross entities work fine till a kind of "ban" is triggered and from this time I have the "banned" sensors values "freezed" and the "banned" switch "not changing the state". I restart the HA, then all work for some time and then stop working.

In synthesis, the latest usable version of HA with Meross based environ is the 2021.10.6 (or 2021.11.1 as told by Patrick)

keep in touch

**Comment by patrick-blom** [comment]
@robertolamm That sounds like and explanation. It would also explain, why the rate limit described by @barcus has an impact of the behavior. 

In the meanwhile I tested the Meros Lan integration on my test instance https://github.com/krahabb/meross_lan . This integration seems to work with the new version, but requires a lot of rewriting atutomations, scenes, etc because of the different entities. 
Luckily both integrations can be used parallel. So I will give the new integration a try on my production system after the update.

**Comment by patrick-blom** [comment]
Hey all, 
I did'nt find a solution for the problem so I deactivated the integration and switched to Meross LAN. The new beta 2.4.0 works well for me at 2021.11.5 and I'm finally able to control my devices again. 

***But*** and that's the trade off, I had to reconfigure all my automations and scences! That was a lot of work, but worth it in my opinion.

**Comment by Raul-7-7** [comment]
Thanks for the update @patrick-blom , curious, did you go the MQTT path or the HTTP with that integration?

**Comment by robertolamm** [comment]
Thank you Patrick,
I am migrating the main sensors on ESPHome, then I will try to migrate to the Meross LAN Integration.

From my point of view Meross is not more efficient with HA. The values, when they works, are slow.

So my decision to go to D1 mini and sensors GY-21 , without battery problems :)

Cheers



Inviato da iPhone

**Comment by patrick-blom** [comment]
@Raul-7-7 I went for the HTTP way because I still want to control my devices using Google Assistant 🤓

@robertolamm I 💙 ESPHome because it so versatile, but for sensor data I would always prefer Tasmota especially when combining senors. But you should use what fits best for you 😉 E.g. in my case I use an ESPHome ESP32 Device as a bluetooth hub for collection Temp and Humid data from my Xaiomi sensors and a Tasmota device for my DIY PIR sensor to control some lights. 

I use Meross devices to control plug sockets and lamps. Sensor data isn't that much important their 😉 

Cheers Patrick

**Comment by tomsruk** [comment]
Integration is horribly unreliable currently. I don’t want to jump ship after so long using this integration to Meross LAN. 

I’d love to know how @albertogeniola is getting on with their version of the local network only version of this?

**Comment by Raul-7-7** [comment]
@tomsruk have you tried this:
- Restart HA
- Wait 5 min or so 
- Reload the Meross integration 
This works for me (so far at least) until next HA restart!

**Comment by tomsruk** [comment]
@Raul-7-7 Thanks for this. Unfortunately it didn’t fix the issue for me.

**Comment by Raul-7-7** [comment]
@tomsruk sorry about that, for me it sure fixed it, about 5 days and no issue. 
What version of HA are you running?

**Comment by Whytey** [comment]
I am another user running into this.  I have had it re-occur within 30mins of reloading the integration or restarting HA.  I just enabled rate limiting with default values - will see how it goes.  Strange that it appears to be linked to a specific version of HA - implies it isn't necessarily a Meross API issue.

**Comment by tomsruk** [comment]
This continues to be an issue. I also have another problem that I'm not sure is related or not. Intermittently the UI will not load at all and I'll have to restart by pulling power. This is totally new behaviour and coincides with the Meross integration issue. 

I'm on 11.5 btw @Raul-7-7

**Comment by robertolamm** [comment]
Hi to all, to avoid all these problems I migrated my environ to the “Meross LAN” project; with the http method is quite simple and quick to do. It’s working better and without problems with the latest HA release.

My impression is that this project is no more supported at the time.

Keep in touch
Inviato da iPhone

**Comment by tomsruk** [comment]
Regrettably I've now installed Meross LAN. It's a real shame. If HA V12 doesn't by some miracle fix, I'll spend a few hours migrating everything over to the Meross LAN integration.

**Comment by Raul-7-7** [comment]
@robertolamm @tomsruk I started having issues again after 4-5 days , reload fixes it though. However, I am also thinking of switching to Meross Lan. Another user in the other thread tried it, might do the same.

**Comment by patrick-blom** [comment]
Hey all,
I can confirm that Meross LAN works faultless since the latest version. I first used the beta and now the latest release since nearly two weeks, without any problems. I highly recommend to switch to these integration because it just works and its actively maintained. 

Cheers

**Comment by albertogeniola** [comment]
Hi all!
Version **v1.2.0rc1-dev** is out and should make things a bit better. However, I agree Meross-Lan is an awesome component and works flawlessly for LAN-only installations. This component works very differently from it and aims at supporting also cloud features that the other component does not. So, if you don't need any specific need to rely on cloud features, the other component is a great starting point until the local-lan addon sees the light :)
