### ISSUE TITLE
Integration errors after about 1 day

### ISSUE THREAD

**Issue by nigelspowage** [albertogeniola/meross-homeassistant#287]
I have the integration working but I have found it errors after about a day. Restarting the integration fixes it for another day.

This was on home assistant core-2021.11.4, running on a raspberrypi.

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/meross_cloud/sensor.py:401
Integration: Meross Cloud IoT
First occurred: 16 November 2021, 23:11:46 (77087 occurrences)
Last logged: 20:56:36

Update for sensor.kitchen_cupboard_lights_mss310_power_sensor_v_0 fails
Update for sensor.living_room_lamp_mss310_power_sensor_v_0 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/meross_cloud/sensor.py", line 401, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/electricity.py", line 43, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 915, in _async_send_and_wait_ack
    message_info = client.publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)
```

**Comment by Raul-7-7** [comment]
Same here, if you reload the integration it goes away.

**Comment by jasonhyland** [comment]
I'm getting the same, "ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)" - requires a reboot daily.

**Comment by nigelspowage** [comment]
I've updated homeassistant-core to 2021-11.5 and the issue still happens.

**Comment by patrick-blom** [comment]
Same problem as in issue: https://github.com/albertogeniola/meross-homeassistant/issues/286

**Comment by lkroeker** [comment]
I've got the same/similar issue. Reloading solves it temporarily.

**Comment by K3ndaar** [comment]
Same issue here, reload is solving temoprarily for me too

**Comment by tomsruk** [comment]
This continues to be an issue. I also have another issue that I'm not sure is related or not. Intermittently the UI will not load at all and I'll have to restart my pulling power. This is totally new behaviour and coincides with the Meross integration issue.

**Comment by alessandrovecchio** [comment]
Same here, I confirm that Reload fixes. 

core-2021.11.5
supervisor-2021.10.8
HACS-1.18.0

**Comment by jsaare** [comment]
Hello!
Having same issues as described here. HA restart does the trick for maximum a day. Then the issue repeats.

HA environment information:
core-2021.12.3
supervisor-2021.12.2
HACS 1.18.0
Meross custom component 1.1.4
6 meross devices (plugs, switches, extension cord)

`[core-ssh config]$ cat home-assistant.log
2021-12-18 17:11:58 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meross_cloud which has not been tested                                                                                                                       by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-18 17:11:58 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration unifiprotect which has not been tested                                                                                                                       by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-18 17:11:58 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Hom                                                                                                                      e Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-18 17:11:58 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home                                                                                                                       Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-18 17:12:32 WARNING (MainThread) [custom_components.meross_cloud] Skip MQTT cert validation option set to: True
2021-12-18 17:12:33 WARNING (MainThread) [custom_components.meross_cloud]
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.2.2
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here:
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- TV cabinet (mss425f) - OnlineStatus.ONLINE
- Balcony (mss550l) - OnlineStatus.ONLINE
- Phone charger (mss310) - OnlineStatus.ONLINE
- Front lights (mss510h) - OnlineStatus.ONLINE
- Lobby (mss550l) - OnlineStatus.ONLINE
- Water pump (mss310) - OnlineStatus.ONLINE
===============================
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device Front lights (mss510h, HW 3.0.0, FW 3.1.3, class: mss5                                                                                                                      10h:3.0.0:3.1.3) that has become online while we were offline.
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device Water pump (mss310, HW 2.0.0, FW 2.1.16, class: mss310                                                                                                                      :2.0.0:2.1.16) that has become online while we were offline.
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device Phone charger (mss310, HW 2.0.0, FW 2.1.16, class: mss                                                                                                                      310:2.0.0:2.1.16) that has become online while we were offline.
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device Balcony (mss550l, HW 2.0.0, FW 2.1.6, class: mss550l:2                                                                                                                      .0.0:2.1.6) that has become online while we were offline.
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device Lobby (mss550l, HW 2.0.0, FW 2.1.6, class: mss550l:2.0                                                                                                                      .0:2.1.6) that has become online while we were offline.
2021-12-18 17:12:35 WARNING (MainThread) [meross_iot.manager] Found a new device TV cabinet (mss425f, HW 3.0.0, FW 3.1.2, class: mss425                                                                                                                      f:3.0.0:3.1.2) that has become online while we were offline.
2021-12-18 17:12:45 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform meross_cloud is taking over 10 seco                                                                                                                      nds.
2021-12-18 17:12:45 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from":                                                                                                                       "/app/452003-c1e4648f5d0e116835b747ea4981bcfa/subscribe", "messageId": "52d44053a65d5f5cc2b1d848b5a0b0c0", "method": "GET", "namespace                                                                                                                      ": "Appliance.System.All", "payloadVersion": 1, "sign": "d56ceaf0e3dd29afc366424aaeb4bea8", "timestamp": 1639840355}, "payload": {}}' s                                                                                                                      ent to device uuid 1909203162406490802148e1e95252a3. Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.Global manager stat                                                                                                                      s (last minute): Issued -> 23, Delayed -> 0, Dropped -> 0
2021-12-18 17:12:45 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
-------------------------------------
Component version: 0.4.2.2
Device info:
        Name: TV cabinet
        UUID: 1909203162406490802148e1e95252a3
        Type: mss425f
        HW Version: 3.0.0
        FW Version: 3.1.2
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 919, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/switch.py", line 53, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 934, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2021-12-18 17:12:45 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from":                                                                                                                       "/app/452003-c1e4648f5d0e116835b747ea4981bcfa/subscribe", "messageId": "bffbad27c1bbaee97b79812510cb1454", "method": "GET", "namespace                                                                                                                      ": "Appliance.System.All", "payloadVersion": 1, "sign": "80c4dd83f86c4bd5789ade419a3b54d0", "timestamp": 1639840355}, "payload": {}}' s                                                                                                                      ent to device uuid 1909203162406490802148e1e95252a3. Timeout was: 10.0 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.Global manager stat                                                                                                                      s (last minute): Issued -> 23, Delayed -> 0, Dropped -> 0
2021-12-18 17:12:45 ERROR (MainThread) [custom_components.meross_cloud.switch] Error occurred.
`

**Comment by Raul-7-7** [comment]
@jsaare you can fix it by reloading the integration everytime it happens, or switch to https://github.com/krahabb/meross_lan

**Comment by albertogeniola** [comment]
Hi guys,
unfortunately that happens to be an anti-flood system adopted by the Meross Cloud. I'll try to investigate this issue, but I belive there is little we can do to workaround this problem unless switching to local-only addons. You can, for the moment, rely on the MerossLAN great integration, or just wait until the local-addon is completed (I'm working on it).
