### ISSUE TITLE
Problem with meross plug

### ISSUE THREAD

**Issue by cargen123** [albertogeniola/meross-homeassistant#306]
**Describe the bug**

**Your environment**
HomeAssistant version: -- PLEASE SPECIFY --
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: -- PLEASE SPECIFY --

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

_________

This error originated from a custom integration.

Logger: custom_components.meross_cloud.sensor
Source: custom_components/meross_cloud/sensor.py:330
Integration: Meross Cloud IoT
First occurred: 15:57:52 (1 occurrences)
Last logged: 15:57:52

Error occurred. ------------------------------------- Component version: 0.4.2.2 Device info: Name: Espresso Machine UUID: 19121883744828251h2848e1e913e71b Type: mss310 HW Version: 2.0.0 FW Version: 2.1.16 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/manager.py", line 919, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cargen/.homeassistant/custom_components/meross_cloud/sensor.py", line 330, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/controller/mixins/electricity.py", line 43, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/home/cargen/hass/lib/python3.9/site-packages/meross_iot/manager.py", line 934, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError

**Comment by Raul-7-7** [comment]
I am not sure if this Repo is being actively maintained, have you tried https://github.com/krahabb/meross_lan

**Comment by albertogeniola** [comment]
Hi @cargen123 ,
Sometimes the Meross cloud might not respond to sensor update request. In such cases, that error might occur. Did the error repeat? Have you tried the component v.1.2rc0?

**Comment by albertogeniola** [comment]
Closing for inactivity. Feel free to reopen it if necessary.
