### ISSUE TITLE
Update for sensor.bedroom_mts100v3_temperature_sensor_degc_0 fails

### ISSUE THREAD

**Issue by GrayFarkas** [albertogeniola/meross-homeassistant#310]
Hello Alberto!

Today I got the errors is under the log. This happend 686 times under 3 hours. Now I restarted the Merot Iot integrations and the sensor value is updated without errors. If you need some more information please let me know.

**Your environment**
HomeAssistant version: -- core-2021.12.7 --
Hassio Version (if applicable): -- not used --
Hardware environment: -- Linux 5.4.0-92-generic on a HP ProLiant Microserver --

**Logs taken when the issue happened**
```


Logger: homeassistant.helpers.entity
Source: custom_components/meross_cloud/sensor.py:296
Integration: Meross Cloud IoT
First occurred: 15:10:07 (686 occurrences)
Last logged: 18:01:23
Update for sensor.bedroom_mts100v3_temperature_sensor_degc_0 fails

Traceback (most recent call last):
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/var/snap/home-assistant-snap/462/custom_components/meross_cloud/sensor.py", line 296, in async_update
    await self._device.async_get_temperature()
  File "/root/snap/home-assistant-snap/462/.local/lib/python3.9/site-packages/meross_iot/controller/known/subdevice.py", line 235, in async_get_temperature
    res = await self._hub._execute_command(method="GET", namespace=Namespace.HUB_MTS100_TEMPERATURE,
  File "/root/snap/home-assistant-snap/462/.local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/root/snap/home-assistant-snap/462/.local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/root/snap/home-assistant-snap/462/.local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/root/snap/home-assistant-snap/462/.local/lib/python3.9/site-packages/meross_iot/manager.py", line 915, in _async_send_and_wait_ack
    message_info = client.publish(
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/snap/home-assistant-snap/462/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/snap/home-assistant-snap/462/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)


```

**Comment by Raul-7-7** [comment]
I am not sure if this Repo is being actively maintained, have you tried https://github.com/krahabb/meross_lan

**Comment by albertogeniola** [comment]
Hi!
Have you rebooted HA? That error looks like a SSL problem when dealing with the Meross Cloud.

**Comment by albertogeniola** [comment]
Closing as this issue is related to #318 .
