### ISSUE TITLE
Meross Power Strip - `Timeout occurred while waiting a response for message`

### ISSUE THREAD

**Issue by alec-pinson** [albertogeniola/meross-homeassistant#317]
**Describe the bug**
I've installed the latest version `V1.2.0 RC0` but constant stream of errors in my home-assistant logs (see below). I don't think this is actually causing me problems (I don't actually use the power strip in HA I use other plugs) however after reading about the ddos/spamming Meross I thought i'd create an issue.

Fyi I've never used your plugin before I got these plugs today and decided to set them up, so have never used any previous versions.

**Your environment**
HomeAssistant version: `2021.12.9`
Hardware environment: `Raspberry Pi 3B`

**Logs taken when the issue happened**
```
2022-01-13 15:12:00 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/xxxxxxxx-9717f48a26264b33b3138f549xxxxxxx/subscribe", "messageId": "xxxxxxxxxxx7f47b585c8ccxxxxxxxxx", "method": "GET", "namespace": "Appliance.System.All", "payloadVersion": 1, "sign": "xxxxxxxxxxf69e5d812fc17xxxxxxxxx", "timestamp": 1642086710}, "payload": {}}' sent to device uuid xxxxxxxxx4549590856448e1xxxxxxxx. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
2022-01-13 15:12:00 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
-------------------------------------
Component version: 0.4.4.2
Device info:
	Name: Power Strip
	UUID: xxxxxxxxxxx49590856448xxxxxxxxxx
	Type: mss420f
	HW Version: 3.0.0
	FW Version: 3.2.2
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 860, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 243, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 278, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 823, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 844, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 867, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
```

**Comment by albertogeniola** [comment]
Hi! Can you please try with latest release and see if that's still an issue?

**Comment by tslpre** [comment]
I've been using the 1.2.0rc2 since a few days and seen the exact same issue, however, in the last couple of days, I've noticed it once per day, maybe it's just a temporary issue when trying to reach the cloud mqtt server. I will keep this under observation as well and provide any significant update.

FYI, automations are working and the power strips can be controlled from HA. I've NOT used the "Enable API rate limits", but will enable it today, let's see if it's the server rejecting us.

**Comment by albertogeniola** [comment]
Hi @tslpre ,
thanks for reporting. I'm afraid that the API limit section is now useless as the underlying library is no more implementing such API limiting algorithms. In the next versions of this component such configuration options will be removed entirely.

The main thing here is to keep the HA integration on and see if the strip remain controllable. If they do, then such messages are not a big deal. It simply means that the Meross cloud is refusing to answer to all the messages we send. 

Be careful though: aggressive polling with automations might cause issues to your Meross account. Keep that in mind and be gentle with Meross API polling.
