### ISSUE TITLE
Error occurred while executing looper

### ISSUE THREAD

**Issue by atmezferix** [albertogeniola/meross-homeassistant#318]
**Describe the bug**
Following update to Meross component this morning... Now getting the following error and CPU time increased.

Error occurred while executing looper

**Your environment**
HomeAssistant version: 2021.12.9
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: HA Blue

**Logs taken when the issue happened**
Logger: meross_iot.manager
Source: /usr/local/lib/python3.9/site-packages/meross_iot/manager.py:322
First occurred: 07:15:52 (4211798 occurrences)
Last logged: 15:54:38

Error occurred while executing looper
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 298, in _async_loop
    await self._loop.run_in_executor(None, client.loop, 0.1)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1120, in loop
    return self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in _loop
    rc = self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2483)

**Comment by albertogeniola** [comment]
Hi!
Which version of Meross-Homeassistant are you using?

**Comment by atmezferix** [comment]
Hi,

Sorry its v1.2.0rc0

**Comment by klejejs** [comment]
Hello! I am unfortunately facing a similar issue in the same line of code, but with a different error message. I am not 100% sure, but I have a hunch that this issue caused my server CPU usage to max out and crashed my system 😞 

Here are the logs:
```
2022-01-15 13:14:49 ERROR (MainThread) [meross_iot.manager] Error occurred while executing looper
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 298, in _async_loop
    await self._loop.run_in_executor(None, client.loop, 0.1)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1120, in loop
    return self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3331, in _handle_publish
    return self._send_puback(message.mid)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2601, in _send_puback
    return self._send_command_with_mid(PUBACK, mid, False)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2710, in _send_command_with_mid
    return self._packet_queue(command, packet, mid, 1)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)
```

I have the same v1.2.0rc0 version.

**Comment by NicciZar** [comment]
Yea since the newest update my rpi is on heavy load

![image](https://user-images.githubusercontent.com/43537611/149640250-adfc381e-b9b9-47ad-b60b-3c4c043129de.png)

Also my meross devices only work from time to time with the addon. Sometimes it seems they are not connected and I get an error...

using addon version 1.2.0rc0

<html>
<body>


Version | core-2021.12.9
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.63-v8
CPU Architecture | aarch64


</body>
</html>

<html>
<body>


Host Operating System | Home Assistant OS 7.1
-- | --
Update Channel | stable
Supervisor Version | supervisor-2021.12.2
Docker Version | 20.10.9


</body>
</html>

**Comment by seagull2000** [comment]
Hi,

I also have the same issue:

`2022-01-17 18:03:29 ERROR (MainThread) [meross_iot.manager] Error occurred while executing looper
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 298, in _async_loop
    await self._loop.run_in_executor(None, client.loop, 0.1)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1120, in loop
    return self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3331, in _handle_publish
    return self._send_puback(message.mid)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2601, in _send_puback
    return self._send_command_with_mid(PUBACK, mid, False)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2710, in _send_command_with_mid
    return self._packet_queue(command, packet, mid, 1)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2483)`


Same v1.2.0rc0 version. I have had to roll back to 1.1.4 to prevent my system crashing.
The issue causes 30-40% CPU and the log file fills up at around 1Mbps repeating the above text.

**Comment by albertogeniola** [comment]
Hi guys,

I think I spotted the issue. I've released `v1.2.0rc1-dev` pre-release. You should be able to test it (you can also enable pre-release via HACS). Can you please try that one and tell if this makes the integration more stable?

**Comment by seagull2000** [comment]
> Hi guys,
> 
> I think I spotted the issue. I've released `v1.2.0rc2` pre-release. You should be able to test it (you can also enable pre-release via HACS). Can you please try that one and tell if this makes the integration more stable?

It looks like this has resolved the problem for me. :) 
I have been running v1.2.0rc2 for 24 hours now without an issue.

Thanks for looking at this so quickly 👍

**Comment by albertogeniola** [comment]
Hi @seagull2000 ,

Thanks for sharing. Let's give it some more time: can you please report in a week if that's still all ok?
How about others in this thread? Maybe @NicciZar or @klejejs ?

**Comment by NicciZar** [comment]
After installing the newest version and enabling the devices again ( I disabled the Integration and I needed to enable each device again for it to work)

It seems to be working right now and processor use is not increased!
Thx for the update

**Comment by klejejs** [comment]
I have also been using the new update for about 24 hours now and haven't seen any issues yet.
It seems that the fix works. Thank you!

**Comment by NicciZar** [comment]
Not sure if its because of the update but I keep getting this one

![image](https://user-images.githubusercontent.com/43537611/150349576-89e63d41-dbec-46e5-bc63-b043f2920655.png)

![image](https://user-images.githubusercontent.com/43537611/150349737-51da5c93-f562-4464-bbab-29f0149354da.png)

**Comment by albertogeniola** [comment]
Hi @NicciZar ,

that's probably an unrelated error. Please uninstall the integration, delete all pending entities, reboot HA, reinstall the integration and reboot once again. It should solve the issue.

I'm now closing the thread as it seems that the original has been finally solved!
Thank you all guys.
