### ISSUE TITLE
Doesn‘t work since today

### ISSUE THREAD

**Issue by Friedi1970** [albertogeniola/meross-homeassistant#329]
**Describe the bug**
Since this morning or maybe earlier in the night the integration doesn‘t work. I get the information at the integration‘s page that I shall try a new setup.
When I then try to configure I get asked for “Custom http user agent for API polling“. I don’t know what to put in so I tried https://iot.meross.com/. Then I get a success message but nothing works.

**Your environment**
HomeAssistant version: core-2021.12.10, supervisor-2022.01.1, 
Hassio Version (if applicable): Home Assistant OS 7.2
Hardware environment: RPi 4

**Logs taken when the issue happened**
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:336 
Integration: Meross Cloud IoT 
First occurred: 18:08:43 (12 occurrences) 
Last logged: 18:20:24

Error occurred. ------------------------------------- Component version: 0.4.4.4 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 438, in async_setup_entry
    await meross_coordinator.initial_setup()
  File "/config/custom_components/meross_cloud/__init__.py", line 145, in initial_setup
    self._client, http_devices, creds_renewed = await get_or_renew_creds(
  File "/config/custom_components/meross_cloud/__init__.py", line 336, in get_or_renew_creds
    http_devices = await http_client.async_list_devices()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 408, in async_list_devices
    result = await MerossHttpClient._async_authenticated_post(url=url,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 276, in _async_authenticated_post
    async with session.post(url, data=payload, headers=headers, proxy=http_proxy) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

```

**Comment by albertogeniola** [comment]
Hi @Friedi1970 ,
Did you try to restart Hassio/the Raspberry PI?
