### ISSUE TITLE
TONS of log errors about mss425f device (that works fine)

### ISSUE THREAD

**Issue by luixal** [albertogeniola/meross-homeassistant#335]
**Describe the bug**
I'm using a multi-switch device model `mss425f` (more details in the log trace) and everything seems to work fine: i can toggle states, states are changed when manually using the device, etc... but I get **TONS** of errors in HA log. It seem to be MQTT related but it's working fine.

**Your environment**
HomeAssistant version: 2022.2.1
Hassio Version (if applicable): N/A
Hardware environment: Intel i7 running HA on docker.

**Logs taken when the issue happened**
```
2022-02-15 22:11:56 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-15 22:11:56 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-7ccf8dbb6427f0fb44867a58915ad449/subscribe","messageId":"94c....cd4","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"7586f....c2fa","timestamp":1644959507,"triggerSrc":"Android","uuid":"2001164....83"},"payload":{}}' sent to device uuid 2001164...83. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
2022-02-15 22:11:56 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
-------------------------------------
Component version: 0.4.4.4
Device info: 
	Name: Regleta
	UUID: 200116...83
	Type: mss425f
	HW Version: 3.0.0
	FW Version: 3.1.2
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 806, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 238, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 278, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 766, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 787, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 813, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2022-02-15 22:11:56 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-15 22:11:56 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/69....915ad449/subscribe","messageId":"9a77...95","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"21e3...11","timestamp":1644959507,"triggerSrc":"Android","uuid":"200116...83"},"payload":{}}' sent to device uuid 200116...83. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
```

**Comment by luixal** [comment]
Just to add some more useful info, I'm getting this errors continously:

```
2022-02-16 13:41:04 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.videoportero] Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsps://****:****@aws-tractor2.tuyaeu.com:443/v1/proxy/echo_show/71696473...fdba
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:41:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:43:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:45:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:47:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:47:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:47:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:47:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
2022-02-16 13:47:47 ERROR (MainThread) [meross_iot.controller.device] Please invoke async_update() for this device (Regleta) before accessing its state. Failure to do so may result in inconsistent state.
```

**Comment by TheHolyRoger** [comment]
Your first error is nothing to worry about thankfully :)

The meross iot library is a bit rubbish and when it timeouts alberto chose to log a full traceback

Second error, I've not seen that I'm afraid

**Comment by luixal** [comment]
Oh, ok. I though this plugin was the one not catching or logging the traceback.

Thanks!
