### ISSUE TITLE
Thermostat integration HA timeout error

### ISSUE THREAD

**Issue by ivanovd** [albertogeniola/meross-homeassistant#34]
How often do you get these timeouts? 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 74, in notify_message_received
    self._callback(self._error, self._response)
  File "/config/custom_components/meross_cloud/climate.py", line 119, in action
    self._device.set_mode(ThermostatV3Mode.CUSTOM)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/thermostats.py", line 196, in set_mode
    self.execute_command('SET', HUB_MTS100_MODE, {'mode': [{'id': self.subdevice_id, 'state': mode.value}]})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
Connection lost. Reconnecting…
```

**Comment by albertogeniola** [comment]
It's usually a network related problem. Make sure your thermostat are close enough to the wifi AP.
