### ISSUE TITLE
Meross warning: Service Termination of Your meross Smart Device

### ISSUE THREAD

**Issue by baldus88** [albertogeniola/meross-homeassistant#345]
**Describe the bug**
Hi.
From the meross support receive this support:

Dear Customer,

This is meross cloud security team contacting you.

First of all, thanks for choosing meross products and we hope that you enjoy smart life with our smart products.

Recently our cloud security system has noticed that your devices are communicating with the could server at an **extremely high frequency.** We consider these behaviours abnormal and are concerned about the security of your devices.

Due to the security concerns and the intent to avoid any further potential damage, we will terminate the cloud services of these devices for now to protect your devices.

If you are sure that your devices are safe, NOT hacked, and are performing as expected. Please first lower your periodic request rate to no more than one message every ten seconds and then send an email to <[support@meross.com](mailto:support@meross.com)>. We will resume cloud service for you within 24 hours.

**Your environment**
HomeAssistant version: Home Assistant 2022.3.8
Hassio Version (if applicable): N/A
Hardware environment:
Python Version	3.9.9
Operating System Family	Linux
Operating System Version	5.10.103-v7+
CPU Architecture	armv7l

**Logs taken when the issue happened**
```
Logger: meross_iot.manager
Source: /srv/homeassistant/lib/python3.9/site-packages/meross_iot/manager.py:809
First occurred: April 3, 2022, 6:24:07 PM (8 occurrences)
Last logged: 9:12:30 AM

Timeout occurred while waiting a response for message b'{"header":{"from":"/app/526215-3dcb09542549cf331813ace7eb1e64d0/subscribe","messageId":"6adf9e5896d1d22c87307f39090bbc34","method":"GET","namespace":"Appliance.Hub.Mts100.Temperature","payloadVersion":1,"sign":"2f622ed58696ea8a6b164e1cbf936e97","timestamp":1649003049,"triggerSrc":"Android","uuid":"1911080489325026280348e1e9114e91"},"payload":{"temperature":[{"id":"01009A6D"}]}}' sent to device uuid 1911080489325026280348e1e9114e91. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/526215-3dcb09542549cf331813ace7eb1e64d0/subscribe","messageId":"82dc122ebb179c43929bff8b8b1f8ccf","method":"GET","namespace":"Appliance.Hub.Mts100.Temperature","payloadVersion":1,"sign":"8583c95e12a685f4a8ce47ea889a6e6d","timestamp":1649003068,"triggerSrc":"Android","uuid":"1911080489325026280348e1e9114e91"},"payload":{"temperature":[{"id":"01009D4F"}]}}' sent to device uuid 1911080489325026280348e1e9114e91. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/526215-3dcb09542549cf331813ace7eb1e64d0/subscribe","messageId":"52475b51404289a1cb545ddfcbc825cb","method":"GET","namespace":"Appliance.Hub.Mts100.Temperature","payloadVersion":1,"sign":"cbf1eb0b542f17d41622479d4643ef43","timestamp":1649003068,"triggerSrc":"Android","uuid":"1911080489325026280348e1e9114e91"},"payload":{"temperature":[{"id":"01009F16"}]}}' sent to device uuid 1911080489325026280348e1e9114e91. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/526215-3dcb09542549cf331813ace7eb1e64d0/subscribe","messageId":"a7f49bc68976054d90871970c5290aed","method":"GET","namespace":"Appliance.Hub.Mts100.Temperature","payloadVersion":1,"sign":"665219ea25fe3ec553a68db2b2efcb84","timestamp":1649185964,"triggerSrc":"Android","uuid":"1911080489325026280348e1e9114e91"},"payload":{"temperature":[{"id":"01009A6D"}]}}' sent to device uuid 1911080489325026280348e1e9114e91. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/526215-3dcb09542549cf331813ace7eb1e64d0/subscribe","messageId":"8fcb491c9006fcded9134b1f96626c06","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"03a63b248471c07f2411d00160f717c6","timestamp":1649229140,"triggerSrc":"Android","uuid":"1911080489325026280348e1e9114e91"},"payload":{}}' sent to device uuid 1911080489325026280348e1e9114e91. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
```
```
Logger: meross_iot.controller.mixins.hub
Source: /srv/homeassistant/lib/python3.9/site-packages/meross_iot/controller/mixins/hub.py:156
First occurred: 9:12:30 AM (1 occurrences)
Last logged: 9:12:30 AM

Error occurred during subdevice update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/manager.py", line 806, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/controller/mixins/hub.py", line 140, in async_update
    await super().async_update(timeout=timeout, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/controller/mixins/hub.py", line 72, in async_update
    await super().async_update(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/controller/device.py", line 278, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/manager.py", line 766, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/manager.py", line 787, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/srv/homeassistant/lib/python3.9/site-packages/meross_iot/manager.py", line 813, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError

```

Could you help me?

Regards

**Comment by Friedi1970** [comment]
Today I got the same Mail from Meross.
Please solve the problem.

**Comment by thunder2k** [comment]
Same here, got one on April 25th, asked them to revert and they did..now I got another one.

Any possible fix on your end?

Thanks

Bye

**Comment by johnywar** [comment]
Hi all,

I have same issue. 
Anyone have solution?

Many thanks

**Comment by belikh** [comment]
Out of curiosity, how many meross devices do people with this issue have connected?

**Comment by baldus88** [comment]
> Out of curiosity, how many meross devices do people with this issue have connected?

In my case have 5 valve

**Comment by BillKen** [comment]
4 configured with 3 currently on the network.  I got the mail but the devices started working again a few hours later with no action on my part.  Maybe a problem their end?
BillK

**Comment by belikh** [comment]
I have an automation that restarts HA every 5 hours and i don't see any issues like this.  It's not great but I'm mostly concerned with collecting energy data at the moment and this keeps the data coming in.

**Comment by gilsonbeckman** [comment]
Hi,
I have added Meross integration in my Homeassistant and just after 2 hours I got my account locked. "Meross Cloud
Too many tokens have been issued to this account. The Remote API refused to issue a new one." 
I got a message in my phone app saying I have exceeded the limit of requests and asking to contact Meross support.
I have 6 meross device and added only one of them to my HA dashboard to monitor Watts and Volts.
Any idea to avoid it happen again (If I am able to unlock my account) ?

Thanks.

**Comment by josntrm** [comment]
Hello, 

I have the same kind of issue. I have 4 Meross MSS310 plugs and while everyhting works fine when i start the integration, the integration stops to work after just a few hours. Cannot activate the plugs from HA anymore and there is no power data coming from Meross. Looking at logs i got the same kind of timeout messages.
The plugs are working fine with power data on Meross cloud and app.

The only that works is manually reloading Meross integration or restarting HA.

Please help
