### ISSUE TITLE
Could not connect to the Meross cloud. Please check your internet connection and your Meross credentials

### ISSUE THREAD

**Issue by tukadafoonday** [albertogeniola/meross-homeassistant#36]
Just started having an issue whereby approximatel 18 hours ago, Meross has stopped authenticating with the server and says it's either can not make contact or my username/password is wrong.

I can login to the Meross account from my phone, and I have changed password numerous times today trying to get this working.

Any ideas?

`2020-01-05 22:49:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-05 22:49:09 ERROR (MainThread) [meross.api] Error occurred when logging in.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 92, in _login
    response_data = self._authenticated_post(_LOGIN_URL, params_data=data)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 75, in _authenticated_post
    raise AuthenticatedPostException()
meross_iot.api.AuthenticatedPostException
2020-01-05 22:49:09 ERROR (MainThread) [custom_components.meross_cloud] Your Meross login credentials are invalid or the network could not be reached at the moment.
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 43, in async_setup_entry
    manager = MerossManager(meross_email=config_entry.data.get(CONF_USERNAME), meross_password=config_entry.data.get(CONF_PASSWORD))
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 39, in __init__
    self._cloud_creds = self._http_client.get_cloud_credentials()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/api.py", line 126, in get_cloud_credentials
    raise UnauthorizedException()
meross_iot.api.UnauthorizedException`

**Comment by tukadafoonday** [comment]
This has now seemed to resolve itself.

**Comment by albertogeniola** [comment]
Great. That was probably something happening on Meross side. Glad you solved.
