### ISSUE TITLE
urllib3 not found after HA upgrade, error on startup, component not working

### ISSUE THREAD

**Issue by EvilItalianK** [albertogeniola/meross-homeassistant#384]
**Describe the bug**
The extension fails with two warnings after the upgrade

**Your environment**
HomeAssistant version: 2022.8.5
Hardware environment: ARM Ampere A1 server, 4 cores 24GB of RAM, AARCH64

**Logs taken when the issue happened**
Unexpected exception importing component custom_components.meross_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3037, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3028, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 638, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/__init__.py", line 16, in <module>
    from meross_iot.http_api import MerossHttpClient, ErrorCodes
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 37, in <module>
    _MODULE_VERSION = current_version()
  File "/usr/local/lib/python3.10/site-packages/meross_iot/utilities/misc.py", line 8, in current_version
    return pkg_resources.get_distribution(name).version
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2755, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3039, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3048, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3030, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1431, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1635, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/urllib3-1.26.11.dist-info/METADATA'

**Comment by EvilItalianK** [comment]
still having the issue
