### ISSUE TITLE
Almost every morning I need to restart HA since api changed.

### ISSUE THREAD

**Issue by TecnoTalarn** [albertogeniola/meross-homeassistant#417]
Almost every morning I find that the data from the grouper devices in my installation do not respond
restarting HA fixes it.
It's the same with thermometers as with switches.

No issues on log... I think. just not respond.
```
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.5.7
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here:
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
List of devices reported by HTTP API:

Caldera (mss310) - OnlineStatus.ONLINE
piscina (mss310) - OnlineStatus.ONLINE
Ràdio (mss310) - OnlineStatus.ONLINE
IC-7300 (mss710) - OnlineStatus.ONLINE
cal menjador (mss710) - OnlineStatus.ONLINE
cal habitació (mss710) - OnlineStatus.ONLINE
Hub. casa rebedor (msh300) - OnlineStatus.ONLINE
===============================
2023-01-08 09:18:39.800 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform saj_esolar is taking over 10 seconds.
2023-01-08 09:18:42.501 WARNING (MainThread) [meross_iot.device_factory] Device Hub. casa rebedor (msh300, uuid 2103044511338226281048e1e9604a43) reported ability Appliance.Digest.Hub. Assuming this is a full-featured HUB.
2023-01-08 09:18:47.075 WARNING (MainThread) [meross_iot.manager] Found a new device Caldera (mss310, HW 6.0.0, FW 6.3.21, class: mss310:6.0.0:6.3.21) that has become online while we were offline.
2023-01-08 09:18:47.079 WARNING (MainThread) [meross_iot.manager] Found a new device piscina (mss310, HW 6.0.0, FW 6.3.21, class: mss310:6.0.0:6.3.21) that has become online while we were offline.
2023-01-08 09:18:47.080 WARNING (MainThread) [meross_iot.manager] Found a new device Ràdio (mss310, HW 6.0.0, FW 6.3.21, class: mss310:6.0.0:6.3.21) that has become online while we were offline.
2023-01-08 09:18:47.082 WARNING (MainThread) [meross_iot.manager] Found a new device IC-7300 (mss710, HW 6.0.0, FW 6.3.2, class: mss710:6.0.0:6.3.2) that has become online while we were offline.
2023-01-08 09:18:47.090 WARNING (MainThread) [meross_iot.manager] Found a new device cal menjador (mss710, HW 6.0.0, FW 6.3.2, class: mss710:6.0.0:6.3.2) that has become online while we were offline.
2023-01-08 09:18:47.092 WARNING (MainThread) [meross_iot.manager] Found a new device cal habitació (mss710, HW 6.0.0, FW 6.3.2, class: mss710:6.0.0:6.3.2) that has become online while we were offline.
2023-01-08 09:18:47.093 WARNING (MainThread) [meross_iot.manager] Found a new device Hub. casa rebedor (msh300, HW 4.0.0, FW 4.1.26, class: msh300:4.0.0:4.1.26) that has become online while we were offline.
2023-01-08 09:18:47.100 WARNING (MainThread) [meross_iot.manager] Found a new device termòstat entrada (ms100, HW unknown, FW unknown, class: Ms100Sensor) that has become online while we were offline.
2023-01-08 09:18:47.102 WARNING (MainThread) [meross_iot.manager] Found a new device Menjador (ms100, HW unknown, FW unknown, class: Ms100Sensor) that has become online while we were offline.
2023-01-08 09:18:47.106 WARNING (MainThread) [meross_iot.manager] Found a new device termòstat habitació (ms100, HW unknown, FW unknown, class: Ms100Sensor) that has become online while we were offline.
2023-01-08 09:18:52.749 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.solar_radiation (<class 'custom_components.ecowitt.sensor.EcowittSensor'>) is using native unit of measurement 'W/m^2' which is not a valid unit for the device class ('illuminance') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by TecnoTalarn** [comment]
adding some logs, but is running meanwile...
is seems a no reponse from server.


2023-01-08 12:58:21.543 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) - Main channel reported online event.
2023-01-08 12:58:21.571 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) power W - Main channel reported online event.
2023-01-08 12:58:21.577 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) current A - Main channel reported online event.
2023-01-08 12:58:21.580 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) voltage V - Main channel reported online event.
2023-01-08 12:58:31.384 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.caldera_mss310_power_w_main_channel is taking over 10 seconds
2023-01-08 12:58:31.387 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.caldera_mss310_current_a_main_channel is taking over 10 seconds
2023-01-08 12:58:31.389 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/1757042-d6707feda37e78d1cf45600210821f9c/subscribe","messageId":"1af0e494b7a4e39ef4a5329daabaedce","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"0e5d98625c081f720600a944508987f9","timestamp":1673179101,"triggerSrc":"Android","uuid":"2211011631009151080148e1e9adacb3"},"payload":{"channel":0}}' sent to device uuid 2211011631009151080148e1e9adacb3. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
2023-01-08 12:58:31.398 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: Caldera
	UUID: 2211011631009151080148e1e9adacb3
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 147, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-08 12:58:31.417 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/1757042-d6707feda37e78d1cf45600210821f9c/subscribe","messageId":"7d9b58423fa9fc63230edc8e3b50c649","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"4daf3521da65cc97ff32bed9e95727de","timestamp":1673179101,"triggerSrc":"Android","uuid":"2211011631009151080148e1e9adacb3"},"payload":{"channel":0}}' sent to device uuid 2211011631009151080148e1e9adacb3. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
2023-01-08 12:58:31.418 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: Caldera
	UUID: 2211011631009151080148e1e9adacb3
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 186, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-08 13:00:37.780 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) - Main channel reported online event.
2023-01-08 13:00:37.781 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) power W - Main channel reported online event.
2023-01-08 13:00:37.782 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) current A - Main channel reported online event.
2023-01-08 13:00:37.791 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) voltage V - Main channel reported online event.

**Comment by albertogeniola** [comment]
Hi!
Can you please post a screenshot of the HA dashboard where the 'frozen' control is displayed when the issue occurs? I'd like to understand if the device is reported as offline or if simply does not work when you issue commands. 

Moreover, what about the other components? Do you have other Meross devices on that HA instance? Do they continue working when the other one gets stuck?

**Comment by PatrickMaul** [comment]
Hi 😀
I have the same problems with my installation. Unfortunately I have restarted my home assistant right now, so I can't help out with a screenshot now.

In my case all Meross devices just don't work, still displayed as online. All other devices (Kasa or my TV) works well.

But I recognised that I also have a notification that there was a failed login attempt from localhost.

More details maybe tomorrow 😊

**Comment by PatrickMaul** [comment]
Okay here is one dashboard with Meross devices. "Fernseher" and "PlayStation 4" working pretty good. All other devices are Meross devices.

![image](https://user-images.githubusercontent.com/97639335/212467550-9c0acb1a-c017-4c7d-8563-2b5e886ae201.png)![image](https://user-images.githubusercontent.com/97639335/212467556-78f815de-e115-490c-b6f1-a1217aaff04e.png)

**Comment by albertogeniola** [comment]
Hi @PatrickMaul ,

thanks for the info. I see you posted the activity logs of the entity; that's fine, but it is not what I meant: I was not clear enough, my bad. The logs we need are the ones you find under "settings"->"System"->"Logs" -> "Load Full Logs".

So, what you should do is the following:
1. Open two HomeAssistant tabs in your browser: one pointing to the Dashboard where you can turn on and off the devices; another one should point to the LOGS section as I mentioned above.
2. Turn on or off the devices
3. Load the full logs and collect the ones in the time-range when you operated the devices. 

Those logs will teel us what's wrong with the device when you issued the commands.

**Comment by PatrickMaul** [comment]
```
2023-01-15 14:58:50.366 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch Lampe (mss310) power W - Main channel reported online event.
2023-01-15 14:58:50.371 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch Lampe (mss310) current A - Main channel reported online event.
2023-01-15 14:58:50.374 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch Lampe (mss310) voltage V - Main channel reported online event.
2023-01-15 14:58:50.377 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch Lampe (mss310) - Main channel reported online event.
2023-01-15 14:58:50.379 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch (mss310) power W - Main channel reported online event.
2023-01-15 14:58:50.381 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch (mss310) voltage V - Main channel reported online event.
2023-01-15 14:58:50.382 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch (mss310) current A - Main channel reported online event.
2023-01-15 14:58:50.384 WARNING (MainThread) [custom_components.meross_cloud] Device Schreibtisch (mss310) - Main channel reported online event.
2023-01-15 14:58:50.386 WARNING (MainThread) [custom_components.meross_cloud] Device Kühlschrank (mss310) power W - Main channel reported online event.
2023-01-15 14:58:50.388 WARNING (MainThread) [custom_components.meross_cloud] Device Kühlschrank (mss310) voltage V - Main channel reported online event.
2023-01-15 14:58:50.390 WARNING (MainThread) [custom_components.meross_cloud] Device Kühlschrank (mss310) current A - Main channel reported online event.
2023-01-15 14:58:50.392 WARNING (MainThread) [custom_components.meross_cloud] Device Kühlschrank (mss310) - Main channel reported online event.
2023-01-15 14:58:50.394 WARNING (MainThread) [custom_components.meross_cloud] Device Spülmaschine (mss310) power W - Main channel reported online event.
2023-01-15 14:58:50.396 WARNING (MainThread) [custom_components.meross_cloud] Device Spülmaschine (mss310) current A - Main channel reported online event.
2023-01-15 14:58:50.398 WARNING (MainThread) [custom_components.meross_cloud] Device Spülmaschine (mss310) voltage V - Main channel reported online event.
2023-01-15 14:58:50.400 WARNING (MainThread) [custom_components.meross_cloud] Device Spülmaschine (mss310) - Main channel reported online event.
2023-01-15 14:58:50.402 WARNING (MainThread) [custom_components.meross_cloud] Device Waschmaschine (mss310) power W - Main channel reported online event.
2023-01-15 14:58:50.405 WARNING (MainThread) [custom_components.meross_cloud] Device Waschmaschine (mss310) current A - Main channel reported online event.
2023-01-15 14:58:50.407 WARNING (MainThread) [custom_components.meross_cloud] Device Waschmaschine (mss310) voltage V - Main channel reported online event.
2023-01-15 14:58:50.409 WARNING (MainThread) [custom_components.meross_cloud] Device Waschmaschine (mss310) - Main channel reported online event.
2023-01-15 14:58:50.411 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - Main channel reported online event.
2023-01-15 14:58:50.413 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - Leer reported online event.
2023-01-15 14:58:50.415 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - Leer reported online event.
2023-01-15 14:58:50.416 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - Mondlampe reported online event.
2023-01-15 14:58:50.418 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - Stehlampe reported online event.
2023-01-15 14:58:50.420 WARNING (MainThread) [custom_components.meross_cloud] Device Steckdosenleiste hinter Sofa (mss425f) - USB reported online event.
2023-01-15 14:58:50.422 WARNING (MainThread) [custom_components.meross_cloud] Device Küchenlicht (mss510h) - Main channel reported online event.
2023-01-15 14:59:04.608 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
await waiter
File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
ssldata, appdata = self._sslpipe.feed_ssldata(data)
File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
self._sslobj.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1170, in get
data, content_type = await player.async_get_media_image()
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 586, in async_get_media_image
return await self._async_fetch_image_from_cache(url)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1088, in _async_fetch_image_from_cache
(content, content_type) = await self._async_fetch_image(url)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1099, in _async_fetch_image
return await async_fetch_image(_LOGGER, self.hass, url)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1264, in async_fetch_image
response = await websession.get(url)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host 192.168.178.39:3001 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]
```
