### ISSUE TITLE
Merros disconnects (timeout?)

### ISSUE THREAD

**Issue by babsz02** [albertogeniola/meross-homeassistant#425]
**Describe the bug**

Every day at 1am, Merros disconnects and I don't get any feedback about the consumption of my connected plugs.
I am forced to reboot HA to get it working again.

**Your environment**
HomeAssistant version: Home Assistant 2023.1.7
Hassio Version (if applicable): 1.30.0
Hardware environment: Proxmox VM

**Logs taken when the issue happened**
```

-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: plante
	UUID: 2104028766676351806048e1e969bb32
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 147, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-25 19:54:33.844 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/1432918-7db0b3cf716a283888f298c8da00eae9/subscribe","messageId":"e79df00a790e197da3ea4679fdf219a3","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"847f722e6eabcc0ec38bdd4e4e3bea9d","timestamp":1674672864,"triggerSrc":"Android","uuid":"2104028766676351806048e1e969bb32"},"payload":{"channel":0}}' sent to device uuid 2104028766676351806048e1e969bb32. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-2.meross.com:443.
2023-01-25 19:54:33.844 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: plante
	UUID: 2104028766676351806048e1e969bb32
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 230, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-25 23:11:52.285 WARNING (Thread-11) [pychromecast.socket_client] [Téléviseur du salon(192.168.1.18):8009] Heartbeat timeout, resetting connection
2023-01-25 23:12:10.717 ERROR (Thread-11) [pychromecast.socket_client] [Téléviseur du salon(192.168.1.18):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.18', 8009)), retrying in 5.0s
2023-01-26 00:56:15.829 WARNING (MainThread) [custom_components.meross_cloud] Device Klipper (mss310) power W - Main channel reported online event.
2023-01-26 00:56:15.831 WARNING (MainThread) [custom_components.meross_cloud] Device Klipper (mss310) voltage V - Main channel reported online event.
2023-01-26 00:56:15.831 WARNING (MainThread) [custom_components.meross_cloud] Device Klipper (mss310) current A - Main channel reported online event.
2023-01-26 00:56:15.832 WARNING (MainThread) [custom_components.meross_cloud] Device Klipper (mss310) - Main channel reported online event.
2023-01-26 00:56:15.833 WARNING (MainThread) [custom_components.meross_cloud] Device Imprimante 3D (mss310) power W - Main channel reported online event.
2023-01-26 00:56:15.833 WARNING (MainThread) [custom_components.meross_cloud] Device Imprimante 3D (mss310) voltage V - Main channel reported online event.
2023-01-26 00:56:15.834 WARNING (MainThread) [custom_components.meross_cloud] Device Imprimante 3D (mss310) current A - Main channel reported online event.
2023-01-26 00:56:15.835 WARNING (MainThread) [custom_components.meross_cloud] Device Imprimante 3D (mss310) - Main channel reported online event.
2023-01-26 00:56:15.836 WARNING (MainThread) [custom_components.meross_cloud] Device plante (mss310) power W - Main channel reported online event.
```

**Comment by TecnoTalarn** [comment]
I have same errors the last 2 days
My only change is I add 2 mss310 to my home. 

maybe is a limitation on meross web? many calls for hour?
After the last api issue I modify from 30 to 60s:
HA_SENSOR_POLL_INTERVAL_SECONDS = 60     # HA sensor polling interval
in order to make less calls to web.
this make me more stable but now I have 2 more devices anb timeout returns! 




-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: Caldera
	UUID: 2211011631009151080148e1e9adacb3
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  **File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 147, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-26 11:49:12.936 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.caldera_mss310_current_a_main_channel is taking over 10 seconds
2023-01-26 11:49:12.938 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/1757042-11bf7660d40d48bbe97995380fba649f/subscribe","messageId":"73f40623d79742831f07c419ce628162","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"2ad03227e871f02a8f42629cb6a84125","timestamp":1674730143,"triggerSrc":"Android","uuid":"2211011631009151080148e1e9adacb3"},"payload":{"channel":0}}' sent to device uuid 2211011631009151080148e1e9adacb3. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
2023-01-26 11:49:12.939 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.5.7
Device info: 
	Name: Caldera
	UUID: 2211011631009151080148e1e9adacb3
	Type: mss310
	HW Version: 6.0.0
	FW Version: 6.3.21
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 186, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.10/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.10/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2023-01-26 11:50:20.254 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.finestra_e71786309] Error from stream worker: Error opening stream (ERRORTYPE_113, Host is unreachable) rtsp://****:****@192.168.254.93:554
2023-01-26 11:50:49.897 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) - Main channel reported online event.
2023-01-26 11:50:49.898 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) power W - Main channel reported online event.
2023-01-26 11:50:49.900 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) current A - Main channel reported online event.
2023-01-26 11:50:49.903 WARNING (MainThread) [custom_components.meross_cloud] Device Caldera (mss310) voltage V - Main channel reported online event.

**Comment by babsz02** [comment]
Thank you very much for your answer, 
Indeed I have 9 meross entities and I think I make too many requests
How do you modify the variable HA_SENSOR_POLL_INTERVAL_SECONDS = 60 ?
I am still a beginner in Home Assistant.

And I also tried to switch to local but I get back the Voltage and Watt consumption data, I can only modify the state (on/off) of my connected socket

**Comment by mlarchet** [comment]
Same error for me every day, hour is a little bit different but I think it's related to timezone.
This crashes all my morning automations.

**Comment by zuan35** [comment]
> Thank you very much for your answer, Indeed I have 9 meross entities and I think I make too many requests How do you modify the variable HA_SENSOR_POLL_INTERVAL_SECONDS = 60 ? I am still a beginner in Home Assistant.
> 
> And I also tried to switch to local but I get back the Voltage and Watt consumption data, I can only modify the state (on/off) of my connected socket

To change the interval time, you have to go through "File editor" and open file "/config/custom_components/meross_cloud/common.py"

Look for the line "HA_SENSOR_POLL_INTERVAL_SECONDS = 30 # HA sensor polling interval" then enter the value you want.

I'm not sure that your modification remains after an update.

**Comment by RaoulSargent** [comment]
Seeing similar with a couple of MSS310.
If I power-cycle (remove from socket and reinsert) the MSS310 they work happily for 12-18 hours then become unavailable in HA.  They are still connected to WIFI and still respond to ping.
'Restart integration' in HA does not resolve this. (looking for a solution less than restarting the whole of HA).

I have all of my MSS310 devices blocked from Internet access, except ntp (as I previously thought being unable to reach ntp was the problem).

Of my 11x MSS310 this problem is only affecting 2x of them, those on firmware v6.3.6.

2x   HW v6.0.0   FW v6.3.6     <<< Affected
6x   HW v6.0.0   FW v6.1.12   NOT affected
3x   HW v2.0.0   FW v2.1.15   NOT affected

Ultimately I want to use meross-lan fully offline with my own MQTT broker.  Sadly this is only working for my devices on HW v2.0.0 whilst those on HW v6.0.0 (both FW v6.1.12 and FW v6.3.6) cannot be configured with the meross setup utility.

**Comment by Wozzagonebush** [comment]
I can confirm this survives a restart,  but there is still a problem with losing connectivity to the remote devices. ---- On Thu, 16 Feb 2023 19:10:22 +1100  ***@***.***  wrote ----

Thank you very much for your answer, Indeed I have 9 meross entities and I think I make too many requests How do you modify the variable HA_SENSOR_POLL_INTERVAL_SECONDS = 60 ? I am still a beginner in Home Assistant.
And I also tried to switch to local but I get back the Voltage and Watt consumption data, I can only modify the state (on/off) of my connected socket

To change the interval time, you have to go through "File editor" and open file "/config/custom_components/meross_cloud/common.py"
Look for the line "HA_SENSOR_POLL_INTERVAL_SECONDS = 30 # HA sensor polling interval" then enter the value you want.
I'm not sure that your modification remains after an update.

**Comment by flouck** [comment]
> I can confirm this survives a restart,  but there is still a problem with losing connectivity to the remote devices. ---- On Thu, 16 Feb 2023 19:10:22 +1100 ***@***.*** wrote ---- Thank you very much for your answer, Indeed I have 9 meross entities and I think I make too many requests How do you modify the variable HA_SENSOR_POLL_INTERVAL_SECONDS = 60 ? I am still a beginner in Home Assistant. And I also tried to switch to local but I get back the Voltage and Watt consumption data, I can only modify the state (on/off) of my connected socket To change the interval time, you have to go through "File editor" and open file "/config/custom_components/meross_cloud/common.py" Look for the line "HA_SENSOR_POLL_INTERVAL_SECONDS = 30 # HA sensor polling interval" then enter the value you want. I'm not sure that your modification remains after an update. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Was this a good solution?
