### ISSUE TITLE
Add-on stopped working and can't be found in HACS anymore

### ISSUE THREAD

**Issue by slackstarr** [albertogeniola/meross-homeassistant#429]
**Describe the bug**
All my Merros devices weren't working anymore and I tried to fix it by downloading the Merros add-on again. It seems to be gone. 

**Your environment**
HACS Version 1.31.0
HomeAssistant version: -- Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0 - latest--
Hardware environment: -- Raspberry Pi4--

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```

**Comment by rmoff** [comment]
Same here. Found this log in my `home-assistant.log`: 

```
2023-03-02 04:34:15.625 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.meross_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3038, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3029, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/__init__.py", line 16, in <module>
    from meross_iot.http_api import MerossHttpClient, ErrorCodes
  File "/usr/local/lib/python3.10/site-packages/meross_iot/http_api.py", line 37, in <module>
    _MODULE_VERSION = current_version()
  File "/usr/local/lib/python3.10/site-packages/meross_iot/utilities/misc.py", line 8, in current_version
    return pkg_resources.get_distribution(name).version
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 820, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2754, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3040, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3049, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3031, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1475, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1684, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/charset_normalizer-3.0.1.dist-info/METADATA'
2023-03-02 04:34:16.020 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration meross_cloud: Unable to import component: Exception importing custom_components.meross_cloud
```

Running Home Assistant 2023.3.0 on Docker. 
HACS version:	1.31.0

**Comment by rursache** [comment]
same issue here, @albertogeniola any plans on fixing it?

**Comment by frepelkweeltje** [comment]
I also encountered this issue after updating Home Assistant to 2023.3.0. However, the Meross integration started working again after an additional restart.

**Comment by slackstarr** [comment]
An Update from my side. I restarted HA this morning, added the Meross integration again through HACS and then I was able to authenticate and configure the Meross integration in HA's device settings. I did this before the latest HA core update and it didn't work.

**Comment by rursache** [comment]
> I also encountered this issue after updating Home Assistant to 2023.3.0. However, the Meross integration started working again after an additional restart of Home Assistant.

indeed, restarting HASS fixed it for me

**Comment by rmoff** [comment]
+1 restart of HASS worked. Thanks @albertogeniola for a great plugin 👍
