### ISSUE TITLE
Meross MSS425F Power Strip not working properly

### ISSUE THREAD

**Issue by luixal** [albertogeniola/meross-homeassistant#453]
**Describe the bug**
The device itself is found and added to HA, but status isn't sync with the Meross app and you can't control it neither.

All switches from the power strip are shown as `on`, doesn't matter if you turn them off in the meross app.

If you try to turn any of them to off from HA, they are shown as `off` for a few seconds and then, they come back to `on` and stay there.

**Your environment**
HomeAssistant version: 2023.8.2
Hassio Version (if applicable): Supervisor 2023.08.1, Operating System 10.4
Hardware environment: Using power strip `mss425f` version `3.0.0`, firmware `3.1.2`.

**Logs taken when the issue happened**
There are a bunch of logs so I'm pasting them separately as HA shows them:

Something related to `meross_cloud` not generating unique IDs. Seems related to other devices that are working well.
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:613
Integration: Sensor (documentation, issues)
First occurred: 15:51:30 (182 occurrences)
Last logged: 16:51:37

Platform meross_cloud does not generate unique IDs. ID sensor:#BASE:20031743053249251h3648e1e91903c1:0:power:W already exists - ignoring sensor.lamapara_salon_mss310_power_w_main_channel
Platform meross_cloud does not generate unique IDs. ID sensor:#BASE:20031743053249251h3648e1e91903c1:0:voltage:V already exists - ignoring sensor.lamapara_salon_mss310_voltage_v_main_channel
Platform meross_cloud does not generate unique IDs. ID sensor:#BASE:20031743053249251h3648e1e91903c1:0:current:A already exists - ignoring sensor.lamapara_salon_mss310_current_a_main_channel
Platform meross_cloud does not generate unique IDs. ID sensor:#BASE:20031795378348251h3648e1e9190c1a:0:power:W already exists - ignoring sensor.nissan_leaf_mss310_power_w_main_channel
Platform meross_cloud does not generate unique IDs. ID sensor:#BASE:20031795378348251h3648e1e9190c1a:0:voltage:V already exists - ignoring sensor.nissan_leaf_mss310_voltage_v_main_channel
```

Got the same IDs logs about the power strip (named `smart_surge_protector`):
```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:613
Integration: Interruptor (documentation, issues)
First occurred: 15:55:17 (220 occurrences)
Last logged: 16:51:27

Platform meross_cloud does not generate unique IDs. ID switch:#BASE:2001164408781490808248e1e916e683:1 already exists - ignoring switch.smart_surge_protector_mss425f_switch_1
Platform meross_cloud does not generate unique IDs. ID switch:#BASE:2001164408781490808248e1e916e683:2 already exists - ignoring switch.smart_surge_protector_mss425f_switch_2
Platform meross_cloud does not generate unique IDs. ID switch:#BASE:2001164408781490808248e1e916e683:3 already exists - ignoring switch.smart_surge_protector_mss425f_switch_3
Platform meross_cloud does not generate unique IDs. ID switch:#BASE:2001164408781490808248e1e916e683:4 already exists - ignoring switch.smart_surge_protector_mss425f_switch_4
Platform meross_cloud does not generate unique IDs. ID switch:#BASE:2001164408781490808248e1e916e683:5 already exists - ignoring switch.smart_surge_protector_mss425f_usb
```

Next, I got this error logs about some timeouts:

```Este error se originó a partir de una integración personalizada.

Logger: meross_iot.manager
Source: custom_components/meross_cloud/__init__.py:243
Integration: Meross Cloud IoT
First occurred: 15:51:31 (84 occurrences)
Last logged: 16:51:27

Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-1044d426c61f9746210ac8ae92410635/subscribe","messageId":"595d38cbc1952057c6da0986765ab5a9","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"f1620cc4be272fbd0958ebe8f1dd1e6f","timestamp":1692024557,"triggerSrc":"Android","uuid":"2001164408781490808248e1e916e683"},"payload":{}}' sent to device uuid 2001164408781490808248e1e916e683. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-1044d426c61f9746210ac8ae92410635/subscribe","messageId":"fe5484074a73165f1f199d8b4fc76d94","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"9e813706408b98acd4454b6b99817ffd","timestamp":1692024557,"triggerSrc":"Android","uuid":"2001164408781490808248e1e916e683"},"payload":{}}' sent to device uuid 2001164408781490808248e1e916e683. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-1044d426c61f9746210ac8ae92410635/subscribe","messageId":"b293d84e2dabd7498f89ed6704b277b3","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"db799e6f3edb7e3f5590fa0cc3c21596","timestamp":1692024677,"triggerSrc":"Android","uuid":"2001164408781490808248e1e916e683"},"payload":{}}' sent to device uuid 2001164408781490808248e1e916e683. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-1044d426c61f9746210ac8ae92410635/subscribe","messageId":"d68659180940753b21b7bf5a4fbaf5f4","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"1bcc317eaeef885f43bad31ae84d106a","timestamp":1692024677,"triggerSrc":"Android","uuid":"2001164408781490808248e1e916e683"},"payload":{}}' sent to device uuid 2001164408781490808248e1e916e683. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
Timeout occurred while waiting a response for message b'{"header":{"from":"/app/691778-1044d426c61f9746210ac8ae92410635/subscribe","messageId":"78d47d09375fdc0e901970aea0ef3d6d","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"f11cf34376bf4fcfd1852afa8ac0fd63","timestamp":1692024677,"triggerSrc":"Android","uuid":"20031795378348251h3648e1e9190c1a"},"payload":{}}' sent to device uuid 20031795378348251h3648e1e9190c1a. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
```

and then, this exception in `__init__.py`@243 which I guess is the exception from the timeout:

```
Este error se originó a partir de una integración personalizada.

Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:243
Integration: Meross Cloud IoT
First occurred: 15:51:31 (84 occurrences)
Last logged: 16:51:27

Error occurred. ------------------------------------- Component version: 0.4.5.7 Device info: Name: Smart Surge Protector UUID: 2001164408781490808248e1e916e683 Type: mss425f HW Version: 3.0.0 FW Version: 3.1.2 Error Message: "An exception occurred"
Error occurred. ------------------------------------- Component version: 0.4.5.7 Device info: Name: Nissan Leaf UUID: 20031795378348251h3648e1e9190c1a Type: mss310 HW Version: 2.0.0 FW Version: 2.1.17 Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 243, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.11/site-packages/meross_iot/controller/mixins/runtime.py", line 49, in async_update
    await super().async_update(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/meross_iot/controller/mixins/system.py", line 22, in async_update
    result = await self._execute_command(method="GET",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/controller/device.py", line 302, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
```

Thing is, I get these 3 kind of logs for every Meross device I have, but the power strip (just added) is the only one not working.

After cleaning the logs and trying to turn off switch from the power strip, I get this warning log:

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:833
First occurred: 16:59:16 (1 occurrences)
Last logged: 16:59:16

Referenced entities switch.smart_surge_protector_mss425f_switch_2 are missing or not currently available
```

**Comment by luixal** [comment]
I just noticed my other meross switches/plugs stopped working from HA.

Looking around the issues I noticed some old (closed) ones talking about an API limit or somethings like that so I've tried removing one existing switch and everything is working fine.

Sadly, I can0t try adding it again, as it was an old one I didn't own anymore.
