### ISSUE TITLE
After MQTT update today (1st Sep) Meross unable to communicate with iot.meross.com

### ISSUE THREAD

**Issue by geidorei** [albertogeniola/meross-homeassistant#456]
As of today all Meross devices are unknown, log as below:

2023-09-01 13:03:02.379 ERROR (MainThread) [homeassistant.components.light] Platform meross_cloud does not generate unique IDs. ID light:#BASE:2303178149795559100148e1e9c06656:0 already exists - ignoring light.stubby_light_msl450_main_channel
2023-09-01 13:03:02.381 ERROR (MainThread) [homeassistant.components.climate] Platform meross_cloud does not generate unique IDs. ID climate:#BASE:2208026208188660120248e1e99cdf77:0 already exists - ignoring climate.central_heating_mts200b_main_channel

I have rebooted router, and HA (restarted and full power off). No difference.

**Comment by tyron** [comment]
I'm also having issues with Methods devices, but started yesterday before the MQTT update as far as I can see from the lows. Devices go unavailable and back online every 10 minutes or so.

**Comment by uowis** [comment]
i have this kind of error : 
```
Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}, {'topic': 'zigbee2mqtt/general power/availability'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'identifiers': ['zigbee2mqtt_0x00158d0005ce7748'], 'manufacturer': 'LiXee', 'model': 'Lixee ZLinky (ZLinky_TIC)', 'name': 'general power', 'sw_version': '4000-0013'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/general power', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/general power', 'name': None, 'object_id': 'general_power', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.33.0', 'url': 'https://www.zigbee2mqtt.io'}, 'payload_install': '{"id": "0x00158d0005ce7748"}', 'state_topic': 'zigbee2mqtt/general power', 'unique_id': '0x00158d0005ce7748_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}, {'topic': 'zigbee2mqtt/prise cuisine frigot/availability'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'identifiers': ['zigbee2mqtt_0xa4c13809a557ad78'], 'manufacturer': 'TuYa', 'model': 'Smart plug (with power monitoring) (TS011F_plug_1)', 'name': 'prise cuisine frigot'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/prise cuisine frigot', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/prise cuisine frigot', 'name': None, 'object_id': 'prise_cuisine_frigot', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.33.0', 'url': 'https://www.zigbee2mqtt.io'}, 'payload_install': '{"id": "0xa4c13809a557ad78"}', 'state_topic': 'zigbee2mqtt/prise cuisine frigot', 'unique_id': '0xa4c13809a557ad78_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}, {'topic': 'zigbee2mqtt/chauffage sdb/availability'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'identifiers': ['zigbee2mqtt_0xa4c1383a10604800'], 'manufacturer': 'TuYa', 'model': 'Smart plug (with power monitoring) (TS011F_plug_1)', 'name': 'chauffage sdb'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/chauffage sdb', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/chauffage sdb', 'name': None, 'object_id': 'chauffage_sdb', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.33.0', 'url': 'https://www.zigbee2mqtt.io'}, 'payload_install': '{"id": "0xa4c1383a10604800"}', 'state_topic': 'zigbee2mqtt/chauffage sdb', 'unique_id': '0xa4c1383a10604800_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}, {'topic': 'zigbee2mqtt/Lave vaiselle/availability'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'identifiers': ['zigbee2mqtt_0xa4c13846652f658e'], 'manufacturer': 'TuYa', 'model': 'Smart plug (with power monitoring) (TS011F_plug_1)', 'name': 'Lave vaiselle'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/Lave vaiselle', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/Lave vaiselle', 'name': None, 'object_id': 'lave_vaiselle', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.33.0', 'url': 'https://www.zigbee2mqtt.io'}, 'payload_install': '{"id": "0xa4c13846652f658e"}', 'state_topic': 'zigbee2mqtt/Lave vaiselle', 'unique_id': '0xa4c13846652f658e_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
Exception in async_discover when dispatching 'mqtt_discovery_new_update_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}, {'topic': 'zigbee2mqtt/Deshumidificateur/availability'}], 'availability_mode': 'all', 'command_topic': 'zigbee2mqtt/bridge/request/device/ota_update/update', 'device': {'identifiers': ['zigbee2mqtt_0xa4c1385cbf1bdbe4'], 'manufacturer': 'TuYa', 'model': 'Smart plug (with power monitoring) (TS011F_plug_1)', 'name': 'Deshumidificateur'}, 'device_class': 'firmware', 'entity_picture': 'https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png', 'json_attributes_topic': 'zigbee2mqtt/Deshumidificateur', 'latest_version_template': "{{ value_json['update']['latest_version'] }}", 'latest_version_topic': 'zigbee2mqtt/Deshumidificateur', 'name': None, 'object_id': 'deshumidificateur', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.33.0', 'url': 'https://www.zigbee2mqtt.io'}, 'payload_install': '{"id": "0xa4c1385cbf1bdbe4"}', 'state_topic': 'zigbee2mqtt/Deshumidificateur', 'unique_id': '0xa4c1385cbf1bdbe4_update_zigbee2mqtt', 'value_template': "{{ value_json['update']['installed_version'] }}", 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
```

**Comment by albertogeniola** [comment]
Hi!

Does it still occur or was it a transient error?

**Comment by albertogeniola** [comment]
Closing. Feel free to re-open if needed.
