### ISSUE TITLE
Local-only setup fails on v1.2.10

### ISSUE THREAD

**Issue by PenguinPofi** [albertogeniola/meross-homeassistant#469]
**Describe the bug**
Local-only setup fails on version 1.2.10 with a message "An unexpected error occured" after submitting my login info.
I am *not* using a cloud account and want to have everything entire local. The devices are paired only to the Local Meross Broker, Version 0.0.1-rc0
Going back to version 1.2.5rc5 of Meross-homeassistant - local only setup succeeds and finds all 4 of my mss310 devices successfully. The installation attempts were done back to back, so all other variables should be near identical.

From the logs it looks to me like (despite me selecting local install) there's an attempt to communicate with Meross cloud, which of course fails without me using a real account.

**Your environment**
HomeAssistant version: 2023.10.5
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: Raspi 3

**Logs taken when the issue happened**
2023-10-24 23:09:25.216 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api, ex: Failed request to API. Response code: 500
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/config_flow.py", line 271, in async_step_configure_manager
    creds = await self._test_authorization(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_cloud/config_flow.py", line 360, in _test_authorization
    client = await MerossHttpClient.async_from_user_password(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 117, in async_from_user_password
    creds = await cls.async_login(email=email,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 246, in async_login
    response_data = await MerossHttpClient._async_authenticated_post(url=url,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 342, in _async_authenticated_post
    raise AuthenticatedPostException("Failed request to API. Response code: %s" % str(response.status))
meross_iot.model.http.exception.AuthenticatedPostException: Failed request to API. Response code: 500

**Comment by albertogeniola** [comment]
Hi @PenguinPofi ,

can you post the logs of the local-addon when this error occurrs?

**Comment by olivermaor** [comment]
Version 1.2.8 works fine with me.

**Comment by fireheadman** [comment]
here is a screenshot if this option....
Select the integration...
Select local
![image](https://github.com/albertogeniola/meross-homeassistant/assets/19847195/53a36c38-ea4f-4518-b6db-7e3fdd43be02)

enter creds... Unexpected error happens
![image](https://github.com/albertogeniola/meross-homeassistant/assets/19847195/e665f6c1-1e21-4482-99a8-df4937420b0e)

**Comment by fireheadman** [comment]
```
2023-10-31 13:18:41.845 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api, ex: Failed request to API. Response code: 500
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/config_flow.py", line 271, in async_step_configure_manager
    creds = await self._test_authorization(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_cloud/config_flow.py", line 360, in _test_authorization
    client = await MerossHttpClient.async_from_user_password(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 117, in async_from_user_password
    creds = await cls.async_login(email=email,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 246, in async_login
    response_data = await MerossHttpClient._async_authenticated_post(url=url,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/http_api.py", line 342, in _async_authenticated_post
    raise AuthenticatedPostException("Failed request to API. Response code: %s" % str(response.status))
meross_iot.model.http.exception.AuthenticatedPostException: Failed request to API. Response code: 500
```

**Comment by fireheadman** [comment]
think I understand more about the strange hostname... each time I attempt to configure this integration it creates a different one.    I also reverted back to 1.2.5rc5 and that doesn't work either...
unsure what to do at this point

```
2023-10-31 13:29:15.347 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found 2 mdns services.
2023-10-31 13:29:15.347 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found [1] Local Meross API service listening on shield6334.local.:2003
2023-10-31 13:29:15.347 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found [1] Local Meross MQTT service listening on shield6334.local.:2001
2023-10-31 13:29:27.420 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api: Invalid username/Password combination
```

Here is version 1.2.5rc5 logs
```
2023-10-31 13:31:05.073 INFO (SyncWorker_15) [homeassistant.util.package] Attempting install of meross_iot==0.4.4.7
2023-10-31 13:31:18.258 INFO (MainThread) [custom_components.meross_cloud.version] MerossIot Version: 0.4.5.7
2023-10-31 13:31:18.258 INFO (MainThread) [custom_components.meross_cloud.version] Integration Version: 1.2.5rc5
2023-10-31 13:32:02.596 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found 2 mdns services.
2023-10-31 13:32:02.597 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found [1] Local Meross MQTT service listening on shield4961.local.:2001
2023-10-31 13:32:02.597 INFO (MainThread) [custom_components.meross_cloud.config_flow] Found [1] Local Meross API service listening on shield4961.local.:2003
2023-10-31 13:32:51.643 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Unable to connect to Meross HTTP api: Invalid username/Password combination
```

**Comment by fireheadman** [comment]
Another error this time...

`2023-10-31 13:39:46.306 ERROR (MainThread) [custom_components.meross_cloud.config_flow] Connection ERROR to HTTP api: Cannot connect to host shield9600.local:2003 ssl:default [Try again]`

**Comment by albertogeniola** [comment]
Hi guys,

The current version of the add-on is not working with the Meross component due to a change in the MerossIot library. This change was necessary as the Meross team changed the login API and I had to comply with it. This inevitably has side effects also on the addon.

I am currently working on a temporary fix to address this issue. However this will probably require some reconfiguration of the addon.

I'll keep you posted.

**Comment by Kedryn** [comment]
Any update on this?

**Comment by jaredcat** [comment]
@albertogeniola any update on this? I'm currently waiting on 1.2.8

**Comment by Nosnahc** [comment]
@jaredcat [Meross LAN](https://github.com/krahabb/meross_lan)
