### ISSUE TITLE
The device Termo sala (xxxxxx) is offline. The command cannot be executed

### ISSUE THREAD

**Issue by Gobolin80** [albertogeniola/meross-homeassistant#47]
With Hassio 0.105.3 and last version Merros Cloud Iot I recive this error.
In real my termo valve are ON and available with Meross app.
If I restart Hassio the addon restart to work fine
Thanks for your support

Dettagli registro (ERROR)
Fri Feb 14 2020 23:02:32 GMT+0100 (Ora standard dell’Europa centrale)
The device Termo sala (1811063738569229086034298f17d209) is offline. The command cannot be executed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 384, in _handle_service_platform_call
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 438, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/common.py", line 109, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/climate.py", line 193, in set_preset_mode
    self._device.set_mode(ThermostatMode[preset_mode])
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/thermostats.py", line 196, in set_mode
    self.execute_command('SET', HUB_MTS100_MODE, {'mode': [{'id': self.subdevice_id, 'state': mode.value}]})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 141, in execute_command
    (self.name, self.uuid))
meross_iot.cloud.exceptions.OfflineDeviceException.OfflineDeviceException: The device Termo sala (1811063738569229086034298f17d209) is offline. The command cannot be executed

**Comment by ivanovd** [comment]
I am getting the same with my smart thermostats. A lot of timeout errors, even though the Meross app works just fine. If I restart HA everything is back to normal for a while and then the same thing happens again.

**Comment by maltemosler** [comment]
Hassio 105.4 doesn't work too. Even if it doesn't die on start like both error messages below it isn't working. The thermostats are reporting the right temperature but changing temps doesn't work.
And it's also impossible to change the state of smart outlet strips, if I try to change the state I get immediately the error message that it timed out. Shouldn't a timeout take 10 seconds and not like 0.3 seconds?

Meross app is always working so it seems like the integration is broken :/

Error while setting up meross_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/meross_cloud/sensor.py", line 128, in async_setup_entry
    elif plug.type.startswith("mss310") or plug.supports_consumption_reading():
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 179, in supports_consumption_reading
    return CONSUMPTIONX in self.get_abilities()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 151, in get_abilities
    self._abilities = self.execute_command("GET", ABILITY, {})['ability']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 309, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
Connection lost. Reconnecting…





An exception occurred while setting up the meross manager.
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 49, in async_setup_entry
    manager.start()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 50, in start
    self._discover_devices()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 167, in _discover_devices
    self._handle_device_discovered(dev=subdev, parent_hub=discovered)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 214, in _handle_device_discovered
    evt = DeviceOnlineStatusEvent(device, device.online)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 43, in online
    self._sync_status()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 49, in _sync_status
    res = self._hub.execute_command('GET', HUB_MTS100_ALL, payload)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 309, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

**Comment by albertogeniola** [comment]
Hi guys,

this issue is linked to #46 . The latest version of the library fixes that bug. Could you please update to the latest release and let me know if that worked?

**Comment by maltemosler** [comment]
Thanks for the update! Everything is working fine now but I still get error messages. Unfortunately I can't say when they appear. (3x in the last 2 hours) If I find more out I update you, maybe it was really just a timeout?

Failed to process message.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in _on_message
    self._push_message_callback(message, from_myself=from_myself)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 128, in _dispatch_push_notification
    self._discover_devices()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 167, in _discover_devices
    self._handle_device_discovered(dev=subdev, parent_hub=discovered)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 214, in _handle_device_discovered
    evt = DeviceOnlineStatusEvent(device, device.online)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 43, in online
    self._sync_status()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 49, in _sync_status
    res = self._hub.execute_command('GET', HUB_MTS100_ALL, payload, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 309, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

**Comment by albertogeniola** [comment]
Yes, that is still a known bug. Will be fixed in the next release.

**Comment by ivanovd** [comment]
I can also confirm that it is working now. Thanks for the quick turnaround Alberto!

**Comment by albertogeniola** [comment]
Closing. In case the problem persists, please reopen the issue or start a new one.

**Comment by ivanovd** [comment]
I was a bit too early in confirming this. It worked fine for one day then again I started getting timeouts and Device unavailable statuses.

**Comment by albertogeniola** [comment]
Hi @ivanovd ,
Can you please attach error logs? It seems that the error is confined to power sensors only. Is it?

**Comment by ivanovd** [comment]
> Hi @ivanovd ,
> Can you please attach error logs? It seems that the error is confined to power sensors only. Is it?

It is related to the thermostats in my case, but the behavior is the same ... timeouts during the commands and unavailable status after some time.

```
A timeout exception occurred while executing function <function ValveEntityWrapper.set_preset_mode at 0x70ff9270> 
Connection lost. Reconnecting…
```

```
Unhandled/ignored event: <meross_iot.meross_event.DeviceSwitchStatusEvent object at 0x6c65a8b0>
Connection lost. Reconnecting…
```

**Comment by Gobolin80** [comment]
> 
> It is related to the thermostats in my case, but the behavior is the same ... timeouts during the commands and unavailable status after some time.
> 
> ```
> A timeout exception occurred while executing function <function ValveEntityWrapper.set_preset_mode at 0x70ff9270> 
> Connection lost. Reconnecting…
> ```
> 
> ```
> Unhandled/ignored event: <meross_iot.meross_event.DeviceSwitchStatusEvent object at 0x6c65a8b0>
> Connection lost. Reconnecting…
> ```

Hi @ivanovd,
I don't know if can resolve your problem, but after last release I had same problem that I had before.
I relinstalled the addon (by specific button in HACS interface) and now it works fine.
I hope it can help you

**Comment by ivanovd** [comment]
I will try reinstalling it. Thanks.

**Comment by maltemosler** [comment]
I have the same problem. If I turn my thermostats manually per app or per lovelace on it works as expected. When I use automations I get the same device offline error (for all 5 thermostats but its the same scheme):

automations.yaml:
```
- id: "Arbeits-Wecker-Heizung"
  alias: Arbeits-Wecker-Heizung
  trigger:
    - platform: time
      at: '6:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: time
        after: '06:00:00'
        before: '07:00:00'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: group.all_heatings
        preset_mode: 'HEAT'
```

groups.yaml:
```
all_heatings:
  name: Heizungen
  entities:
    - climate.badezimmer_heizung
    - climate.kuchen_heizung
    - climate.wohnzimmer_heizung
    - climate.schlafzimmer_heizung

```

Error while executing automation automation.turn_heating_afternoon_on. Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 397, in async_trigger
    await self.action_script.async_run(variables, trigger_context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 96, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 384, in _handle_service_platform_call
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 438, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/common.py", line 67, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/climate.py", line 201, in set_preset_mode
    self._device.set_mode(ThermostatV3Mode[preset_mode])
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/thermostats.py", line 196, in set_mode
    self.execute_command('SET', HUB_MTS100_MODE, {'mode': [{'id': self.subdevice_id, 'state': mode.value}]})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 141, in execute_command
    (self.name, self.uuid))
meross_iot.cloud.exceptions.OfflineDeviceException.OfflineDeviceException: The device Badezimmer Heizung (1811064346913229086034298f17ce00) is offline. The command cannot be executed

--

Additionally It seems that meross implemented another namespace (I don't have any schedules in the meross app but yeah): 

Unknown/Unsupported namespace/command: Appliance.Hub.Mts100.ScheduleB

--

I also get this error for my power outlet(mss425f, firmware version 2.1.8, hardware: 2.0.0, Wi-Fi signal: 78%):

Failed to update data for device Steckdosenleiste lowboard - Main Switch

**Comment by ivanovd** [comment]
I reinstalled the plugin and it worked once again for a while. But then once again I start getting errors and cannot control the thermostats from HA.

```
Failed to process message.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in _on_message
    self._push_message_callback(message, from_myself=from_myself)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 128, in _dispatch_push_notification
    self._discover_devices()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 167, in _discover_devices
    self._handle_device_discovered(dev=subdev, parent_hub=discovered)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 214, in _handle_device_discovered
    evt = DeviceOnlineStatusEvent(device, device.online)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 43, in online
    self._sync_status()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 49, in _sync_status
    res = self._hub.execute_command('GET', HUB_MTS100_ALL, payload, online_check=False)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 309, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
Connection lost. Reconnecting…

```

**Comment by albertogeniola** [comment]
Hi,
last version (20200222.4) should make it a bit more stable. Could you test it and report back if that's true?

**Comment by ivanovd** [comment]
![Screenshot_2020-02-23-13-13-26-672_com microsoft emmx](https://user-images.githubusercontent.com/4889583/75111076-8b1b3a80-563e-11ea-92c2-ccf6184a5f0f.jpg)
Still fails to change presets after some time. After restart it works for few hours.

**Comment by albertogeniola** [comment]
Hi @Gobolin80 ,

would please try the latest version I've released today?

**Comment by Gobolin80** [comment]
> Hi @Gobolin80 ,
> 
> would please try the latest version I've released today?

Hi @albertogeniola ,
I downloaded last version and now it works.
I'm testing it and I will give you a feedback.
Thanks for your work

**Comment by Gobolin80** [comment]
> Hi @Gobolin80 ,
> 
> would please try the latest version I've released today?

Hi @albertogeniola ,
I'm testing from 2 days and these are my consideration:
I haven't errors in my log, but the calls work only sometimes.
For example, today, in lovelace I see HOT, but on the app is ECONOMY.
The state on lovelace change istantly, but command don't arrive always to my valves

**Comment by Gobolin80** [comment]
Ciao @albertogeniola,
innanzitutto come stai? Immagino tu sia italiano :)
Mi auguro tutto bene!

Ti riporto un'eccezione che mi capita di vedere spesso:

Dettagli registro (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/meross_cloud/climate.py:86
First occurred: 15:39:37 (3 occurrences)
Last logged: 15:39:37

Update for climate.termo_bagno fails
Update for climate.termo_cucina fails
Update for climate.termo_sala fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/common.py", line 68, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/climate.py", line 86, in update
    state = self._device.get_status(True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 71, in get_status
    return self._sync_status(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 57, in _sync_status
    res = self._hub.execute_command('GET', status_token, payload)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 141, in execute_command
    (self.name, self.uuid))
meross_iot.cloud.exceptions.OfflineDeviceException.OfflineDeviceException: The device Smart Hub (xxxxxxxxxxxxxxx) is offline. The command cannot be executed

**Comment by albertogeniola** [comment]
Hi @Gobolin80 ,

could you please test the latest version and let me know?

**Comment by Gobolin80** [comment]
> Hi @Gobolin80 ,
> 
> could you please test the latest version and let me know?

ok @albertogeniola!

**Comment by Gobolin80** [comment]
@albertogeniola immediately i see this error:

Logger: meross.hub
Source: /usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/hubs.py:102
First occurred: 17:50:31 (2 occurrences)
Last logged: 17:50:43

Unknown/Unsupported namespace/command: Appliance.Control.Upgrade

**Comment by Gobolin80** [comment]
Hi @albertogeniola ,
This morning I'm seeing this error:

Logger: meross.hub
Source: /usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/hubs.py:102
First occurred: 6:17:53 (1 occurrences)
Last logged: 6:17:53

Unknown/Unsupported namespace/command: Appliance.Hub.Mts100.ScheduleB

**Comment by Gobolin80** [comment]
Hi @albertogeniola ,
I also receive this error:

Dettagli registro (ERROR)
Logger: custom_components.meross_cloud.common
Source: custom_components/meross_cloud/climate.py:57
First occurred: 11:59:26 (2 occurrences)
Last logged: 15:03:20

Component version: unknown, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 79, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/climate.py", line 57, in update
    self._device.get_status(force_status_refresh=True)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 71, in get_status
    return self._sync_status(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 57, in _sync_status
    res = self._hub.execute_command('GET', status_token, payload)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 143, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 321, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

**Comment by Gobolin80** [comment]
Hi @albertogeniola ,
I update addon now but I receive this new error.
NB: I **don't** use cover.

Dettagli registro (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/meross_cloud/cover.py:41
First occurred: 13:26:06 (1 occurrences)
Last logged: 13:26:06

Error setting up entry myMail@xxxxxx.com for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 148, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 244, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/cover.py", line 18, in <module>
    class OpenGarageCover(CoverDevice):
  File "/config/custom_components/meross_cloud/cover.py", line 41, in OpenGarageCover
    @cloud_io()
NameError: name 'cloud_io' is not defined

**Comment by Gobolin80** [comment]
Hi @albertogeniola .
With last update the error on cover.py seems to be resolved.
For now I'm only seeing this error at startup:

Dettagli registro (ERROR)
Logger: meross.connection
Source: /usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py:251
First occurred: 8:56:27 (2 occurrences)
Last logged: 8:56:38

Error occurred while invoking message handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 244, in _on_message
    handle.notify_message_received(error=None, response=message)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 67, in notify_message_received
    if self._event is not None:
AttributeError: 'PendingMessageResponse' object has no attribute '_event'

**Comment by albertogeniola** [comment]
Hi @Gobolin80 ,
thanks for the report. I've spotted the problem: it's about the low-level library. 
Latest version should have fixed it. Please try it and let me know.
