### ISSUE TITLE
A timeout occurred while waiting for the ACK

### ISSUE THREAD

**Issue by harkor** [albertogeniola/meross-homeassistant#50]
```
OS Debian 10 (Docker)
Home Assistant Core 0.105.5
HACS 0.21.5
Meross Cloud IoT 20200216.1 (same problem with 20200109.5)
Device mss310 1.0.0 (Firmware 1.1.18)
```
Hello,

When Home Assistant just started, no problem, I have the power voltage but after a random time (sometimes 30 minutes, sometimes 10 hours). The power voltage stop to be updated on home assistant.

If I check with the Meross mobile app, is fine, I have the actual power consumption but not with Home Assistant.

If I restart home assistant, problem gone but reappear after a time.

In SSH, I can ping external IP address and resolv domain so it's probably not a dns or connexion issue.

I have this type of log every 30-31 secondes.

`2020-02-18 08:30:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ordinateur_julien fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 42, in async_update
    sensor_info = self._device.get_electricity()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 144, in get_electricity
    return self._get_electricity()['electricity']
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 21, in _get_electricity
    return self.execute_command("GET", ELECTRICITY, {})
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 126, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)`

Any clue ?

In an old version the status went into "unavailable" => https://github.com/albertogeniola/meross-homeassistant/issues/42

**Comment by albertogeniola** [comment]
Closing in favor of #51 . We'll keep that issue as the main one. Thanks for sharing.
