### ISSUE TITLE
Getting lots of warning messages about Meross upon Home Assistant startup. 

### ISSUE THREAD

**Issue by devangapatel** [albertogeniola/meross-homeassistant#520]
**Describe the bug**
Lately, I have been seeing a lot of warning messages regarding the Meross cloud integration when Home Assistant is starting. 

**Your environment**
Core 2024.10.0b1
Supervisor 2024.10.4
Operating System 13.1
Frontend 20240926.0
Running on a Synology VM 

**Logs taken when the issue happened**
```
2024-10-31 15:51:09.093 WARNING (MainThread) [custom_components.meross_cloud] 
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.7.3
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Smart Garage Door Opener (msg200) - OnlineStatus.ONLINE
===============================
2024-10-31 15:51:09.258 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f55ec02df50>,) inside the event loop by custom integration 'meross_cloud' at custom_components/meross_cloud/__init__.py, line 189: await self._manager.async_device_discovery() (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/albertogeniola/meross-homeassistant
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/meross_cloud/__init__.py", line 419, in async_setup_entry
    await meross_coordinator.initial_setup()
  File "/config/custom_components/meross_cloud/__init__.py", line 189, in initial_setup
    await self._manager.async_device_discovery()
```

**Comment by z3ky** [comment]
+1

**Comment by ilbagatta** [comment]
+1

**Comment by rscheuermann** [comment]
+1 

And this one:

```
2024-11-23 12:21:24.503 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'meross_cloud' calls async_forward_entry_setup for integration, meross_cloud with title: https://iot.meross.com and entry_id: 01JD3H2PTV1286RGX21K5M05J7, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/meross_cloud/__init__.py, line 426: hass.async_create_task(, please create a bug report at https://github.com/albertogeniola/meross-homeassistant
```

**Comment by HomeAssistentHochleitner** [comment]
+1

**Comment by ezp1** [comment]
+1

**Comment by jorgepersal** [comment]
+1

**Comment by gonzonia** [comment]
+1

**Comment by Whizzykid** [comment]
+1

**Comment by keltakmaster** [comment]
+1

**Comment by albertogeniola** [comment]
Closing as this has been solved in v1.3.10
