### ISSUE TITLE
Meross crashing HA

### ISSUE THREAD

**Issue by Ehrenholm** [albertogeniola/meross-homeassistant#524]
**Describe the bug**
There are alot of loggentrys and eventually HA is crashing after update to HAOS 14 only application in logs casuing error is the Merros add-on.
Below is one i belive is the one the rest of meross error derives from.

**Your environment**
Core
2024.11.3
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241106.2

**Logs taken when the issue happened**
241205
--- PASTE LOGS HERE ---
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:728
integration: Sensor (documentation, issues)
First occurred: 10:11:48 (24 occurrences)
Last logged: 10:56:00

meross_cloud: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/meross_cloud/sensor.py", line 313, in async_update
    await super().async_update()
  File "/config/custom_components/meross_cloud/__init__.py", line 241, in async_update
    await self._device.async_update()
  File "/usr/local/lib/python3.12/site-packages/meross_iot/controller/device.py", line 454, in async_update
    result = await self._hub._execute_command(method="GET",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/meross_iot/controller/device.py", line 308, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/meross_iot/manager.py", line 852, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/meross_iot/manager.py", line 901, in async_execute_cmd_client
    message, message_id = self._build_mqtt_message(method, namespace, payload, destination_device_uuid)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/meross_iot/manager.py", line 977, in _build_mqtt_message
    raise ValueError("Namespace parameter must be a Namespace enum or a string.")
ValueError: Namespace parameter must be a Namespace enum or a string.

------
More on other loggs
This error originated from a custom integration.

Logger: meross_iot.controller.device
Source: custom_components/meross_cloud/__init__.py:241
integration: Meross Cloud IoT
First occurred: 12:07:55 (94 occurrences)
Last logged: 13:43:52

GenericSubDevice does not implement any GET_ALL namespace. Update won't be performed.
Unhandled/NotImplemented event handler for Namespace.HUB_SENSOR_ALL (data: {"id": "2800BF0A7150", "online": {"status": 1, "lastActiveTime": 1733394929}, "smokeAlarm": {"status": 170, "lmtime": 1733394929, "interConn": 0}}) - Subdevice 2800BF0A7150 (hub 2204268171399262080248e1e990bfd3)
Unhandled/NotImplemented event handler for Namespace.HUB_SENSOR_ALL (data: {"id": "2800BF0A7150", "online": {"status": 1, "lastActiveTime": 1733398591}, "smokeAlarm": {"status": 170, "lmtime": 1733398591, "interConn": 0}}) - Subdevice 2800BF0A7150 (hub 2204268171399262080248e1e990bfd3)
Unhandled/NotImplemented event handler for Namespace.HUB_SENSOR_ALL (data: {"id": "2800BF0A7150", "online": {"status": 1, "lastActiveTime": 1733402246}, "smokeAlarm": {"status": 170, "lmtime": 1733402246, "interConn": 0}}) - Subdevice 2800BF0A7150 (hub 2204268171399262080248e1e990bfd3)

**Comment by kwkid** [comment]
Same errors listed above

Your environment
Core
2024.12.5
Supervisor
2024.12.0
Operating System
14.1
Home Assistant OS

**Comment by albertogeniola** [comment]
Please update to the latest release (v1.3.11), and that solves the issue.
