### ISSUE TITLE
Metadata file not found 

### ISSUE THREAD

**Issue by ralpho1337** [albertogeniola/meross-homeassistant#526]
**Describe the bug**
Meross integration does not load anymore with the errors below.

**Your environment**
HomeAssistant version: 2024.12.3
Hassio Version (if applicable): 14.0

**Logs taken when the issue happened**
```
--- PASTE LOGS HERE ---
```
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 19:50:48 (1 Vorkommnisse)
Zuletzt protokolliert: 19:50:48

Setup failed for custom integration 'meross_cloud': Unable to import component: Exception importing custom_components.meross_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3400, in _dep_map
    return self.__dep_map
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3180, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3391, in _parsed_pkg_info
    return self._pkg_info
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3180, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info. Did you mean: 'egg_info'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/__init__.py", line 16, in <module>
    from meross_iot.http_api import MerossHttpClient, ErrorCodes
  File "/usr/local/lib/python3.13/site-packages/meross_iot/http_api.py", line 36, in <module>
    _MODULE_VERSION = current_version()
  File "/usr/local/lib/python3.13/site-packages/meross_iot/utilities/misc.py", line 8, in current_version
    return pkg_resources.get_distribution(name).version
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 529, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 412, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                            ~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1065, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 897, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3103, in requires
    dm = self._dep_map
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3402, in _dep_map
    self.__dep_map = self._compute_dependencies()
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3411, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3393, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1696, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1912, in _get
    with open(path, 'rb') as stream:
         ~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.13/site-packages/aiosignal-1.3.1.dist-info/METADATA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.meross_cloud

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3400, in _dep_map
    return self.__dep_map
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3180, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3391, in _parsed_pkg_info
    return self._pkg_info
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3180, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info. Did you mean: 'egg_info'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/__init__.py", line 16, in <module>
    from meross_iot.http_api import MerossHttpClient, ErrorCodes
  File "/usr/local/lib/python3.13/site-packages/meross_iot/http_api.py", line 36, in <module>
    _MODULE_VERSION = current_version()
  File "/usr/local/lib/python3.13/site-packages/meross_iot/utilities/misc.py", line 8, in current_version
    return pkg_resources.get_distribution(name).version
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 529, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 412, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                            ~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1065, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 897, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3103, in requires
    dm = self._dep_map
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3402, in _dep_map
    self.__dep_map = self._compute_dependencies()
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3411, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3393, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1696, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1912, in _get
    with open(path, 'rb') as stream:
         ~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.13/site-packages/certifi-2024.8.30.dist-info/METADATA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.meross_cloud

**Comment by ralpho1337** [comment]
Hi,

i rolled back to homeassistant version 2024.11.3 - this fixed the issue for me.

Best
Ralph
