### ISSUE TITLE
Covers stopped working

### ISSUE THREAD

**Issue by Skyhog** [albertogeniola/meross-homeassistant#62]
Hello,

I've been using your custom component for the last month or so, and it has pretty much worked flawlessly.  Recently, with the update to HA108, and the recent updates to this component, my 2 MSG100s stopped working.

To see if I could correct this, I removed the component, and deleted all references to it in the .storage folder, then reinstalled.  Upon reinstallation, the covers are no longer being detected.  They work fine in the Meross app, but not in HomeAssistant.

From the logs, the following error has started appearing:

`2020-04-13 00:08:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry brennan.nick.d@gmail.com for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 148, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 244, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/cover.py", line 18, in <module>
    class OpenGarageCover(CoverDevice):
  File "/config/custom_components/meross_cloud/cover.py", line 41, in OpenGarageCover
    @cloud_io()
NameError: name 'cloud_io' is not defined`

**Comment by albertogeniola** [comment]
Hi @Skyhog , that was a regression bug in the previous release. Could you please update to the latest version and report if that's fixed?

**Comment by Skyhog** [comment]
Yep! That fixed it. Thank you.

**Comment by albertogeniola** [comment]
Glad it worked.
