### ISSUE TITLE
name 'cloud_io' is not defined error

### ISSUE THREAD

**Issue by DarwinData** [albertogeniola/meross-homeassistant#69]
I do not have any garage door or cover devices but yet this custom component no longer works. It was working before the last update.
thanks

2020-04-19 06:38:17 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *******@gmail.com for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 148, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 154, in async_setup_entry
    platform_type,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 244, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross_cloud/cover.py", line 18, in <module>
    class OpenGarageCover(CoverDevice):
  File "/config/custom_components/meross_cloud/cover.py", line 41, in OpenGarageCover
    @cloud_io()
NameError: name 'cloud_io' is not defined

**Comment by Florian-Schmidt** [comment]
I'm using a garage door opener. After update got same message.

**Comment by albertogeniola** [comment]
Hi @Florian-Schmidt ,
can you try version 20200419.2, it should fix the problem.

Let me know,
Alberto

**Comment by Florian-Schmidt** [comment]
Good morning @albertogeniola,

I guess, I already did it yesterday but just let me check it again....

Best regards
Florian

**Comment by Florian-Schmidt** [comment]
@albertogeniola. I see in repository that you did some changes last night. Seems to work again, greate job!

**Comment by DarwinData** [comment]
Hi, I am now getting the following error with the newest version:
`2020-04-20 21:46:34 WARNING (Thread-2) [meross.connection] Client has been disconnected, however auto_reconnect flag is set. Won't stop the looping thread, as it will retry to connect.`

**Comment by Florian-Schmidt** [comment]
Hi,

newest version means 20200419.2? This version worked for me yesterday. Then I started testing the beta version which also seems to be working.

HA up to date? 

Perhaps this belongs to mentioned connection issue from meross servers in development branch?

**Comment by Florian-Schmidt** [comment]
Just found that my HA also had this message 04:13:00 tonight. But this is the time my ISP is reconnecting and should be ok. Actually my garage door seems to be connected sucessfully and moves.

**Comment by DarwinData** [comment]
yes, version 20200419.2.  It initially worked earlier yesterday but then stopped in the evening.  I noticed because my garden lights stayed on last night and then I checked the log this morning.

**Comment by Florian-Schmidt** [comment]
Ok, you are using other devices. I only use meross for my garage opener.

As this issue is closed as "cloud_io" is fixed, I guess you need to create a new issue.

Perhaps development beta release could be an option for you:
#67
