### ISSUE TITLE
Meross component becomes unresponsive after losing and restoring Internet connection (20200419.2)

### ISSUE THREAD

**Issue by logicup-dev** [albertogeniola/meross-homeassistant#70]
Since I'm frequently losing internet connection, I realized that my meross devices becomes unreponsive in HA with the latest version...

Latest release 20200419.2

Home Assistant: 0.108.6 with Supervisor 217 HassOS 3.13
Devices: 
mss510 1.0.0 / firmware 1.1.15 (1)
mss110 1.0.0 / firmware 1.1.28 (2)

Here the log after 10 minutes with Internet connection restored :

```
2020-04-21 12:42:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

2020-04-21 12:44:12 WARNING (Thread-5) [pychromecast.socket_client] [Chromecast:8009] Heartbeat timeout, resetting connection

2020-04-21 12:44:15 ERROR (SyncWorker_2) [custom_components.meross_cloud.common] Component version: 0.3.4.3-2, Message: "A command timeout occurred while handling cloud_io function."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/config/custom_components/meross_cloud/switch.py", line 101, in turn_on
    self._device.turn_on_channel(self._channel_id)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 160, in turn_on_channel
    return self._channel_control_impl(c, 1, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 30, in _channel_control_impl
    return self._togglex(channel, status, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 24, in _togglex
    return self.execute_command("SET", TOGGLEX, payload, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 294, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

2020-04-21 12:44:40 WARNING (Thread-2) [meross.connection] Client has been disconnected, however auto_reconnect flag is set. Won't stop the looping thread, as it will retry to connect.

2020-04-21 12:44:40 WARNING (Thread-2) [meross.connection] Client has been disconnected, however auto_reconnect flag is set. Won't stop the looping thread, as it will retry to connect.

2020-04-21 12:44:42 ERROR (Thread-5) [pychromecast.socket_client] [Chromecast:8009] Failed to connect to service Chromecast-xxxxxxxxxxxxxxx._googlecast._tcp.local., retrying in 5.0s

2020-04-21 12:55:09 ERROR (MainThread) [homeassistant.components.system_log.external] manual log
```

Regards,
Mathieu

**Comment by mapoloco** [comment]
mine too :(

**Comment by mapoloco** [comment]
2020-04-21 21:35:45 ERROR (SyncWorker_14) [custom_components.meross_cloud.common] Component version: 0.3.4.3-2, Message: "A command timeout occurred while handling cloud_io functi                                                     
on."                                                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                      
  File "/config/custom_components/meross_cloud/common.py", line 83, in func_wrapper                                                                                                                                                     
    return func(*args, **kwargs)                                                                                                                                                                                                        
  File "/config/custom_components/meross_cloud/switch.py", line 101, in turn_on                                                                                                                                                         
    self._device.turn_on_channel(self._channel_id)                                                                                                                                                                                      
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 160, in turn_on_channel                                                                                                                   
    return self._channel_control_impl(c, 1, callback=callback)                                                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 30, in _channel_control_impl                                                                                                              
    return self._togglex(channel, status, callback=callback)                                                                                                                                                                            
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 24, in _togglex                                                                                                                           
    return self.execute_command("SET", TOGGLEX, payload, callback=callback)                                                                                                                                                             
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command                                                                                                                                
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)                                                                                                                  
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 294, in execute_cmd                                                                                                                                    
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)                                                                                                                                         
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

**Comment by dominik-doll** [comment]
Same here, every night reconnect from provider - every night losing meross

**Comment by maxcanna** [comment]
A side effect of this problem is that after the error occurs the automations keep triggered over and over. E.g. I made an automation to be informed when the dishwasher/washing machine/dryer finishes (watching its power consumption) and I receive tons of notification when this bug occurs 😞

**Comment by Florian-Schmidt** [comment]
Same here since some days with one msg100 garage door opener. Every morning it's unavailable.

**Comment by grea09** [comment]
I suggest a more accurate title since the issue seems to also happen with stable internet connection.

I must also add that this issue completely breaks my installation to the point where it won't boot, not even in safe mode when the custom component is loaded.

I'm available for any testing.

**Comment by maxcanna** [comment]
I confirm that it happens even without any connectivity problems. My internet connection is totally fine but I have this problem. Count on me to test new versions!

**Comment by Florian-Schmidt** [comment]
Seems to be better during the last days:
![grafik](https://user-images.githubusercontent.com/62351739/81787588-91180d80-9501-11ea-9bf5-d4e314f9400c.png)

**Comment by dominik-doll** [comment]
Same here - even with the nightly DSL reconnect I have the component working flawless.

**Comment by maxcanna** [comment]
I disagree, problem is not solved. I have to restart mi HA Core docker container several times to get it working. If this problem happens during HA startup it will hang. Each time I update the config I've to cross my fingers 😅 🍀 🤞

**Comment by dominik-doll** [comment]
> I disagree, problem is not solved. I have to restart mi HA Core docker container several times to get it working. If this problem happens during HA startup it will hang. Each time I update the config I've to cross my fingers 😅 🍀 🤞

Can you share your versions?

Meross Cloud IoT
Installed: 20200429.3

Hassio in Docker on NUC
Supervisor Version 220
System Ubuntu 18.04.4 LTS

arch x86_64
dev  false
docker  true
hassio  true
os_name  Linux
os_version  5.3.0-46-generic
python_version  3.7.7
timezone  Europe/Berlin
version  0.109.6
virtualenv  false

**Comment by maxcanna** [comment]
Here they are

Meross Cloud IoT | 20200429.3
---|---
arch | armv7l
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.19.75-v7l+
python_version | 3.7.7
timezone | Europe/Rome
version | 0.109.6
virtualenv | false

**Comment by Florian-Schmidt** [comment]
Meross Cloud IoT | 20200429.3
-- | --
arch | armv7l
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.19.102-v7l+
python_version | 3.7.7
timezone | Europe/Rome
version | 0.109.6
virtualenv | false

**Comment by calexandre** [comment]
I have the same issue. I even reinstalled the Meross plugin, and the same issue persists.
Unfortunately, HA is unable to start due to this... I was forced to uninstall the component until this issue is fixed :(

**Comment by maxcanna** [comment]
@calexandre keep trying restarting HA, it'll go up eventually

**Comment by calexandre** [comment]
It's been like this for the past 30 min... I have lots of stuff going with HA, i cannot have such a big downtime :(

**Comment by maxcanna** [comment]
I usually manage to solve after a couple of restarts. You don't have to leave it if it's not working, it'll never recover. You've to restart it again and again until it goes up

**Comment by shadowblocker** [comment]
The bigger issue is not that meross cloud keeps breaking but that this component endlessly retries its connections and physically prevents homeassistant from starting. It needs some kind of error handling logic to be implemented so that it will not block or prevent HA from running in the event of a failure.

**Comment by maxcanna** [comment]
The author already said he's working on a complete rewrite of the library and this component (https://github.com/albertogeniola/MerossIot/issues/97#issuecomment-626038232) Please be patient 🙂

**Comment by jugla** [comment]
Hello,
I have the same issue . Since last version of home assistant (0.111.x) , it seems to be more frequent.
Here after "prise salon" refer to a plug in my living room.
But if fails all my plugs.

`    
2020-06-18 07:56:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.prise_salon is taking over 10 seconds
2020-06-18 07:56:14 ERROR (SyncWorker_10) [custom_components.meross_cloud.switch] Error occurred.

-------------------------------------
Component version: 0.3.4.4-3
Device info:
        Name: prise salon
        UUID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        Type: mss310
        HW Version: 2.0.0
        FW Version: 2.1.11
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/switch.py", line 44, in update
    self._device.get_status(force_status_refresh=True)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-06-18 07:56:14 ERROR (SyncWorker_1) [meross.connection] The underlying mqtt client is not connected.
2020-06-18 07:56:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.prise_salon fails
`

**Comment by jugla** [comment]
NB: when I restart my raspberry pi , it works again.

**Comment by jugla** [comment]
Hello,
The error is coming more and more often :-(
`meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10`

It seems to occurs after a certain amount of time.

I have fiber optic, and my raspberry is on ethernet cable. I don't think it's a pb of internet connection.

`
2020-06-22 19:56:16 ERROR (SyncWorker_9) [custom_components.meross_cloud.switch] Error occurred.

Component version: 0.3.4.4-3
Device info:
        Name: prise salon
        UUID: xxxxxxxxxxxxxxxxxxxxxx
        Type: mss310
        HW Version: 2.0.0
        FW Version: 2.1.11
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/meross_cloud/switch.py", line 44, in update
    self._device.get_status(force_status_refresh=True)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 134, in get_status
    self._state = self._get_status_impl()
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/devices/power_plugs.py", line 88, in _get_status_impl
    data = self.get_sys_data()['all']
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
2020-06-22 19:56:16 ERROR (SyncWorker_12) [meross.connection] The underlying mqtt client is not connected.
`

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
