### ISSUE TITLE
Complete crash with 20200428.3 - Error setting up entry

### ISSUE THREAD

**Issue by pzdaniel** [albertogeniola/meross-homeassistant#75]
Hi Alberto,
first of all, thanks for your amazing work 👍 
I updated to 20200428.3, which resulted in a complete crash of meross-homeassistant. The log shows this:

```
2020-04-29 06:22:25 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.xxx for meross_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/meross_cloud/__init__.py", line 80, in async_setup_entry
    issued_on = datetime.fromisoformat(str_creds.get('issued_on'))
AttributeError: 'NoneType' object has no attribute 'get'
```

Fortunately rolling back to 202004.2 works (change Version in HACS and click on reinstall (all data is stored, no worries) - in case anyone has the same issues).

**Comment by albertogeniola** [comment]
Hi @pzdaniel ,

thanks for the great spot. It was a regression bug introduced with previous release. I've fixed it in the newst. Would you please check if the new one works as expected?

**Comment by pzdaniel** [comment]
Thanks, updated to 20200429.3, the above mentioned bug is gone. Everything works as expected so far 😃👍 

FYI: the log is throwing some new warnings:

```
2020-04-29 21:01:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 55: http_client = MerossHttpClient.from_user_password(email=email, password=password)
2020-04-29 21:01:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()
2020-04-29 21:02:09 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform meross_cloud is taking over 10 seconds.
2020-04-29 21:02:09 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform meross_cloud is taking over 10 seconds.
2020-04-29 21:02:18 WARNING (MainThread) [homeassistant.helpers.translation] meross_cloud: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
```

**Comment by albertogeniola** [comment]
Glad it worked. 
About IO inside event loop, I'm tracking it with https://github.com/albertogeniola/meross-homeassistant/issues/74
