### ISSUE TITLE
Thr

### ISSUE THREAD

**Issue by pgdg71** [albertogeniola/meross-homeassistant#79]
I have a problem with Smart Thermostast Valve. 
I don't have any devices registered after installing last versions of Meross IoT.

Follows the error in HA log:

Dettagli registro (ERROR)
Logger: homeassistant.components.climate
Source: custom_components/meross_cloud/climate.py:59
Integration: Termostato (documentation, issues)
First occurred: 14:32:24 (2 occurrences)
Last logged: 14:32:24

meross_cloud: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross_cloud/climate.py", line 59, in update
    if self._device.online:
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 47, in online
    self._sync_status()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/devices/subdevices/generic.py", line 59, in _sync_status
    res = self._hub.execute_command('GET', status_token, payload, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/meross_iot/cloud/client.py", line 273, in execute_cmd
    if not self._mqtt_client.is_connected():
AttributeError: 'Client' object has no attribute 'is_connected'

**Comment by albertogeniola** [comment]
Please update to the latest version (v1.0.0) which fixes the problem and introduces various improvements. Please follow update instructions [here](https://github.com/albertogeniola/meross-homeassistant#updating-from-legacy-versions).
