### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by DanyGijon** [albertogeniola/meross-homeassistant#90]
Hi, 

Just installed this component but the following issue arised: 

2020-05-26 19:39:29 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()
2020-05-26 19:39:29 INFO (MainThread) [custom_components.meross_cloud]
[...]
List of devices reported by HTTP API:
[...]
Component version: 0.3.4.4-3
Device info:
<Unavailable>
Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/Users/DanyG/.homeassistant/custom_components/meross_cloud/__init__.py", line 114, in async_setup_entry
    manager.start(wait_for_first_discovery=True)
  File "/Users/DanyG/homeassistant/lib/python3.8/site-packages/meross_iot/manager.py", line 55, in start
    self._cloud_client.connect()
  File "/Users/DanyG/homeassistant/lib/python3.8/site-packages/meross_iot/cloud/client.py", line 147, in connect
    self._mqtt_client.connect(self._domain, self._port, keepalive=30)
  File "/Users/DanyG/homeassistant/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/Users/DanyG/homeassistant/lib/python3.8/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
2020-05-26 19:39:29 WARNING (MainThread) [homeassistant.config_entries] Config entry for meross_cloud not ready yet. Retrying in 80 seconds.

Any help appreciated

**Comment by DanyGijon** [comment]
My bad. Already solved by installing python certificates using Install certificates.command in the right python version.
