### ISSUE TITLE
4.0.0 alpha2 test ssl Certificate error

### ISSUE THREAD

**Issue by Anjielon** [albertogeniola/meross-homeassistant#99]
Hi,

First of all... thanks.

I'm just checking this new apha integration, but i Had this error:

Error occurred. ------------------------------------- Component version: 0.3.4.4-3 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/custom_components/meross_cloud/__init__.py", line 114, in async_setup_entry
    manager.start(wait_for_first_discovery=True)
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/deps/lib/python3.8/site-packages/meross_iot/manager.py", line 55, in start
    self._cloud_client.connect()
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/deps/lib/python3.8/site-packages/meross_iot/cloud/client.py", line 147, in connect
    self._mqtt_client.connect(self._domain, self._port, keepalive=30)
  File "/opt/Home-Assistant/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/opt/Home-Assistant/lib/python3.8/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/opt/Home-Assistant/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

Is something i forgot to configure?

Thank you

**Comment by albertogeniola** [comment]
Hi @Anjielon ,

from the log you posted it is clear that you are not using the latest Alpha, but version 0.3.4.4-3.

**Comment by Anjielon** [comment]
Hi @albertogeniola,

just reinstalled, but the error perstists also for version 0.4.0.0rc14:

Logger: custom_components.meross_cloud
Source: deps/lib/python3.8/site-packages/meross_iot/http_api.py:143
Integration: Meross Cloud IoT (documentation)
First occurred: 1:11:11 (4 occurrences)
Last logged: 1:12:02

Error occurred. ------------------------------------- Component version: **0.4.0.0rc14** Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/opt/Home-Assistant/lib/python3.8/asyncio/base_events.py", line 1046, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/opt/Home-Assistant/lib/python3.8/asyncio/base_events.py", line 1076, in _create_connection_transport
    await waiter
  File "/opt/Home-Assistant/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/opt/Home-Assistant/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/opt/Home-Assistant/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: **[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/custom_components/meross_cloud/__init__.py", line 108, in async_setup_entry
    client, http_devices, creds_renewed = await get_or_renew_creds(email=email, password=password, stored_creds=creds)
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/custom_components/meross_cloud/__init__.py", line 69, in get_or_renew_creds
    http_devices = await http_client.async_list_devices()
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/deps/lib/python3.8/site-packages/meross_iot/http_api.py", line 212, in async_list_devices
    result = await self._async_authenticated_post(_DEV_LIST, {}, cloud_creds=self._cloud_creds)
  File "/share/MD0_DATA/.qpkg/Home-Assistant/CONFIG_DIR/deps/lib/python3.8/site-packages/meross_iot/http_api.py", line 143, in _async_authenticated_post
    async with session.post(url, data=payload, headers=headers) as response:
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host iot.meross.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Home Assistant has started!


I hope this help you.

Angelo

**Comment by albertogeniola** [comment]
You probably need to update Hassio or Hassbian...
